### ISSUE TITLE
Implement name search

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#1]
See https://sp2000.github.io/colplus/api/staging.html#resource-9 for response model.

We should start and try to do the first implementation purely in postgres.
Requirements needed:
 - regular search only matching entire words, i.e. name "tokens". A search for "alba" should then return all names of the genus "Alba" or names that have an epithet "alba" either at species or infraspecific level
 - autocomplete functionality matching a left anchored search string
 - case insensitive

Options to consider
 - ascii folding for umlauts, ligatures and other non ascii chars
 - optional small fuzzy search, e.g. via [Levenshtein distance of 1](https://www.postgresql.org/docs/9.6/static/fuzzystrmatch.html)

**Comment by ayco-at-naturalis** [comment]
Initial, "workable" version; kingdom needs to be infered from nomenclatural code; ranking of search results must be improved. This will be dealt with in separate issues

**Comment by mdoering** [comment]
@ayco-at-naturalis can you link the new ranking issue from here please?
