### ISSUE TITLE
Dataset search API update:

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#133]
New parameters needed to support https://github.com/Sp2000/colplus/blob/master/docs/EDITORIAL-TOOLS.md#main-editorial-dashboard

- sortBy=KEY,CREATED,MODIFIED,SIZE
- format=ACEF,DWCA
- catalogue=PROV,SCRUT
- code=BACTERIAL,BOTANICAL,CULTIVARS,VIRUS,ZOOLOGICAL
- type=NOMENCLATOR, TAXONOMIC, NATIONAL, PERSONAL, OTHER

Update Dataset class properties:

 - releaseDate -> released
 - trusted -> catalogue=PROVISIONAL, SCRUTINIZED
 - size (taken from last import, not stored in dataset table)

**Comment by thomasstjerne** [comment]
Source for provisional and scrutinized should also be included

**Comment by mdoering** [comment]
and https://github.com/Sp2000/colplus-backend/commit/8f6fac52e36c9106ec81befc03dd35dec1d16ce0
