### ISSUE TITLE
Idea for metrics and API

### ISSUE THREAD

**Issue by MortenHofft** [Sp2000/colplus-backend#135]
If I understand correctly [data(sub)set metrics](http://api.col.plus/dataset/1018/import) would be useful to detect change. But for that to be really useful I guess it should be relative to a previous version. 

That previous version isn't simply the last import I would assume. The last 20 imports could have no or few changes. Instead it is rather the dataset version in use in my composite master (e.g. provCat). 

To do useful diffs it would be useful to a) get specific versions (e.g. by date) from the API. And b) have a way for the user to select what version to compare with (e.g. getting the version in use in the provCat)

**Comment by mdoering** [comment]
I think you should be able to just list all imports with state=finished to get the list of all imports with metrics that actually made it to the database. How these get used as a source in the 2 catalogues is much harder and needs to be thought about still as its only subparts that get used.
