### ISSUE TITLE
Include childCount or hasChildren in api response for nicer tree browsing

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#137]
Would it be possible to this response decorated with either a childCount (best option) or hasChildren:
http://api.col.plus/dataset/1133/taxon/.LGn_/children?limit=100&offset=0
This is in order to know whether a node is a leaf without having to fetch children.

```json
{

        "id":"Pso-1191717",

        "childCount": 0,  <-----

         "datasetKey":1133,

         "verbatimKey":28111962,

         "name":{  
            "id":"Pso-1191717"
         },

      }
```

**Comment by mdoering** [comment]
Sure this can be done. Counts might need to be preprocessed, but that can be done.
When discussing the need for a tree manipulation API I just wonder if it makes sense to have a minimal tree API that specializes on the tree navigation and leaves out most of the other Taxon information?

Basically some flat object like this:

```
{
  "id": ...,
  "parentId": ...,
  "name": ...,
  "authorship": ...,
  "rank": ...,
  "status": ...,
  "childCount": ...
}

```

**Comment by thomasstjerne** [comment]
Currently I am just doing a tree browser within a specific dataset.
But for the main Col tree we need the ColSources, est species count etc.

**Comment by mdoering** [comment]
So a new tree endpoint with minimal object properties like given above sounds good?

**Comment by mdoering** [comment]
added to Taxon API and also created new slim tree endpoint:
```
# root nodes
dataset/{dkey}/tree

# node and its parents
dataset/{dkey}/tree/{id}

# all children
dataset/{dkey}/tree/{id}/children
```
