### ISSUE TITLE
Name formatting

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#150]
Add html formatted full names in responses for proper frontend presentation.
Ideally, these should also be in the tree responses e.g. http://api.col.plus/dataset/1007/tree

They could be look up one by one by the client but in some cases that would need 3000 + requests in a large genus

**Comment by mdoering** [comment]
I was thinking about that too. Let's do that.
Any preference on what the formatting should actually look like? I would love to keep it real simple and not very semantic as we have the structured json already for that. How about this most basic version?

```<i>Abies alba</i> subsp. <i>alpina</i> (Miller) Brandell```

You probably want the authorship marked up?

**Comment by thomasstjerne** [comment]
Yes thats perfect. If there are cases where formatting of the authorship is needed, they should be formatted as well.
The use case is: blindly put formattedName in a html tag and it will render with any need formatting.

**Comment by mdoering** [comment]
Available in API now: http://api.col.plus/dataset/1140/taxon/fer-1370

**Comment by mdoering** [comment]
tree API to come

**Comment by mdoering** [comment]
done
