### ISSUE TITLE
Elastic Indexing Error

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#155]
```
Error while populating index nu1500: org.elasticsearch.client.ResponseException: method [POST], host [http://db.col.plus:9200], URI [/_bulk], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}
```

Logs dont tell which dataset this belongs to.
@ayco-at-naturalis can we try to log a dataset context in MDC when indexing with other threads? Maybe this isn't relevant anymore for the synchroneous indexing. You can reuse the static method here: https://github.com/Sp2000/colplus-backend/blob/master/colplus-admin/src/main/java/org/col/admin/importer/ImportJob.java#L68

**Comment by ayco-at-naturalis** [comment]
ok - although can't access admin module classes from the dao module, so I need to get around that

**Comment by mdoering** [comment]
lets add a common LoggingUtils class and move it there. But are you creating new threads? The main importer thread which calls the indexDataset from ImportJob sets the MDC already

**Comment by ayco-at-naturalis** [comment]
OK ... no, new threads ... but indexAsync would have

**Comment by mdoering** [comment]
Probably not an issue. The Exception eventually is propagated to the calling thread in NameUsageIndexService where we log it. Looks like there is a different reason why the dataset parameter is not picked up in Kibana: https://logs.gbif.org/goto/7eebdfeed865adc7cce1b7765ad371cd

**Comment by mdoering** [comment]
We should make sure its populated cause that is going to be a way to look into import logs for each dataset if sth goes unexpected. So its going to be linked from the editorial tools

**Comment by ayco-at-naturalis** [comment]
ok ... I anyhow created the LoggingUtils class ... but it seems like the index service is provided with empty batches ... causing empty request bodies ... let's wait and see what happens with non-async indexing

**Comment by ayco-at-naturalis** [comment]
This problem seems to have gone
