### ISSUE TITLE
Admin command to batch create a full ES index

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#156]
For desaster recovery and changing index mappings we need to be able to rebuild the full ES index from all content in the Clearinghouse.

This should be an admin command like InitDbCmd that we can run from the terminal with its own config file so we can use a different index name and only later alias it.

**Comment by ayco-at-naturalis** [comment]
The easiest way to implement an index-only job obviously is to introduce an **indexOnly** boolean flag, or maybe an **ImportPhase** enum, or just maybe some sort of optional **ImportInstruction** object/bitset. if indexOnly == true, then we skip everything in ImportJob.importDataset except the indexing.

Quick and easy, but a bit murky. ImportJob already is a pretty big class.

Also it has the disadvantage that it doesn't lend itself well to finer grained indexing (possibly required if when col editors are allowed to make fine-grained edits.

For speed's sake we could start with a course-grained index-only job via the 1st method, then possibly implement a separate trail (IndexRrequest -> IndexJob -> IndexManager -> index resource method) for fine-grained indexing, and then possibly throw away the 1st method

**Comment by ayco-at-naturalis** [comment]
OK - understood

**Comment by ayco-at-naturalis** [comment]
Also added a shell script to colplus-repo to re-index all datasets into ES

**Comment by mdoering** [comment]
nice!
