### ISSUE TITLE
Implement dataset search

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#16]
As there will be many more datasets in the clearinghouse than now in CoL we should offer at least a basic search.

Initial proposal:
 - ascii folding (pg: unaccent)
 - case insensitive
 - full text search on all text like properties (title, description, gbif key, contact and organisation)

Try to use native text search in Pstgresql https://www.postgresql.org/docs/10/static/textsearch-intro.html

**Comment by mdoering** [comment]
separate column to store the tsvector looks good and setweight should be used to allow much higher ranking of hits to the title (the rest can probably be all the same)

**Comment by mdoering** [comment]
Useful blog post: http://rachbelaid.com/postgres-full-text-search-is-good-enough/

**Comment by ayco-at-naturalis** [comment]
5977df71080d3b012a5cd37735f384aed15cae1d
