### ISSUE TITLE
Decorate response from Managment Class. tree endpoint with sector and source

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#162]
```
{
   "childCount":6,
   "id":"41642230",
   "name":"Megaloptera",
   "parentId":"41641781",
   "rank":"order",
   "speciesCount":0,
   "speciesEstimate":380,
   "speciesEstimateReferenceId":".neodb.94QL",
   "status":"accepted",
   "sector":{
      "key":3,
      "colSourceKey":1055,
      "colSource":{
         "key":1055,
         "datasetKey":1055,
         "title":"LDL NSW",
         "alias":"1055"
      },
      "root":{
         "id":"41642230",
         "name":"Megaloptera",
         "rank":"order"
      },
      "attachment":{
         "id":".e!k9",
         "name":"Megaloptera",
         "rank":"order"
      },
      "created":"2018-10-17T10:06:50.487779"
   }
}
```

**Comment by mdoering** [comment]
would just `colSourceKey ` be enough to pull the sector from the client? Decoration in Dropwizard is not as simple as in Javascript.

Note for myself: link the sectors by datasetKey & id only - IDs need to be potentially updated when datasets change

**Comment by mdoering** [comment]
@thomasstjerne should sectors just show in the draft (attachment side) or also in any of the source datasets (root)?

**Comment by thomasstjerne** [comment]
Maybe I have the wrong understanding of root and attachment.
I thought the root was the node in the Management Classification/ draft, and the attachment was the node in the ColSource.
But its opposite?

Anyways, yes they should only show in the Management classification, not the ColSource.

> would just colSourceKey be enough to pull the sector from the client? Decoration in Dropwizard is not as simple as in Javascript.

If thats easy, then lets try it.

**Comment by mdoering** [comment]
yes, it is the other way around. The root is attached to the MC. Ill try to expose that then

**Comment by mdoering** [comment]
I will also add 2 methods listing broken sectors that cannot be linked to the Draft or Source anymore

**Comment by mdoering** [comment]
The flag is `col`:
http://api.col.plus/sector/broken?col=true

**Comment by mdoering** [comment]
see also #180

**Comment by thomasstjerne** [comment]
I still cant see the colSourceKey in the responses
I would expect to see a on the first item in this list: http://api.col.plus/dataset/3/tree/41641825/children

From which I should be able to retrieve the sector: http://api.col.plus/sector?sourceKey=1028

**Comment by mdoering** [comment]
agree, sth wrong

**Comment by mdoering** [comment]
works with latest deploy!
