### ISSUE TITLE
Unique constraint on sectors

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#166]
It is possible to create multiple sector with same combination of (source, root, attachment)

http://api.col.plus/sector?sourceKey=2000

Either throw an error or silently ignore

**Comment by mdoering** [comment]
Agree. I think we should set a unique constraint on sourceKey & root id alone

**Comment by mdoering** [comment]
what error would you expect in case of duplicates? 500 it is for now. 400 more appropriate?
