### ISSUE TITLE
Mark tree nodes in the Management Classification with hasUnMappedChildren=true

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#167]
If a node has a path to a Leaf without meeting a Sector on the way. This means that some subtree is not covered in the MC.

**Comment by mdoering** [comment]
so it is true if there is **at least one** descendant leaf node without a sector, not all? Which means a kingdom would always be flagged if there is some unmapped node (which there probably is always). Thats correct?

**Comment by thomasstjerne** [comment]
There can be a leaf node without a sector - but then that leaf node has to have an ancestor with a sector. For example a family leaf without a sector is OK if the order above has a sector.

**Comment by mdoering** [comment]
that was my understanding of your proposal. But doesnt that mean real high taxa are always marked? Is it useful over flagging the ones that are entirely void, i.e. taxa where **all descendants** have no sector? And probably expose those in searches too

**Comment by mdoering** [comment]
Superceeded by https://github.com/Sp2000/colplus-backend/issues/321
