### ISSUE TITLE
What happens when a sector is removed?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#168]
When a sector is removed, all data from that sector needs to be removed from the draft catalogue. Ideally the shadowed management classification should then reappear. But from where? Or would it better to just keep all higher taxa down to e.g. family?

**Comment by mdoering** [comment]
@thomasstjerne and @yroskov has that been discussed yet?

**Comment by thomasstjerne** [comment]
If the default Management Classification is always the latest published version, then that should also be the fallback.

**Comment by yroskov** [comment]
Ideal solution would be an opportunity to roll classification in removed sector back to any point in recorded history.

**Comment by yroskov** [comment]
>>I'd suggest to always do families
I agree.

**Comment by mdoering** [comment]
see also https://github.com/Sp2000/colplus-backend/issues/279 where we remove all data.
@yroskov should we instead keep the classification down to genera and only delete (infra)species?
That would also be wrong in many cases.

How about we allow a sector to optionally specify a lowest rank filter for inclusion.
If a sector then gets removed we could still use the source to provide the classification down to family or genus level? But I guess we would not like to see these taxa as coming from a dataset but instead from CoL?

**Comment by mdoering** [comment]
Well, it rather sounds like IRMNG will be the new source sector to fill the gap in cases when we pull out a dataset. Therefore closing this

**Comment by yroskov** [comment]
>>If a sector then gets removed we could still use the source to provide the classification down to family or genus level?
There was no such practice in CoL since 2001. If we replace GSD, a new source came in with its own classification. If AlgaeBase has requested to withdraw their data, we obliged to remove ALL data, including classification.   
Regarding IRMNG: just few sectors are available for use in CoL. Tony notifies us which taxa have a good level of scrutiny and ready to be taken in CoL gaps.

**Comment by mdoering** [comment]
then I guess we need to take actions on a case to case basis manually

**Comment by yroskov** [comment]
Agree
