### ISSUE TITLE
Urls as IDs makes tree endpoints break

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#169]
Probably also affects other endpoints where we get taxon by id

Get the root nodes:
http://api.col.plus/dataset/2083/tree

But trying to get children:
http://api.col.plus/dataset/2083/tree/http://services.snsb.info/DTNtaxonlists/rest/v0.1/names/DiversityTaxonNames_Insecta/5009538//children

**Comment by mdoering** [comment]
ids need to be url encoded when constructing the API URL:

http://api.col.plus/dataset/2083/tree/http%3A%2F%2Fservices.snsb.info%2FDTNtaxonlists%2Frest%2Fv0.1%2Fnames%2FDiversityTaxonNames_Insecta%2F5009538%2F/children

Still sth goes wrong

**Comment by mdoering** [comment]
Looks like the 404 for url encoded resources is caused by the apache proxy.
It works hitting Dropwizard directly

**Comment by mdoering** [comment]
Now working: http://api.col.plus/dataset/2083/tree/http%3A%2F%2Fservices.snsb.info%2FDTNtaxonlists%2Frest%2Fv0.1%2Fnames%2FDiversityTaxonNames_Insecta%2F5009538%2F/children

It needed both `AllowEncodedSlashes On` and `nocanon` as keyword for ProxyPass in he VirtualHost config:

https://stackoverflow.com/questions/4390436/need-to-allow-encoded-slashes-on-apache

http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-deploy/commit/321009f779842ee1ced282c325204208af943157
