### ISSUE TITLE
Basic search specs

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#171]
Receive a [NameSearchRequest](https://github.com/Sp2000/colplus-backend/blob/master/colplus-api/src/main/java/org/col/api/search/NameSearchRequest.java) and return a [NameSearchResponse](https://github.com/Sp2000/colplus-backend/blob/master/colplus-api/src/main/java/org/col/api/search/NameSearchResponse.java)

From the request the following features should be working:
- the req.content defining which fields the q search parameter is applied to
- q search parameter
- filter parameter inside the core MultivaluedHashMap<NameSearchParameter, String>. Different parameters should be logically AND-ed while multiple values are OR-ed.

Ideally support also the following:
- req.sortBy

If they are not implemented in this Milestone please create a new issue and push to next search milestone

**Comment by ayco-at-naturalis** [comment]
Implemented as described here
