### ISSUE TITLE
http://api.col.plus/dataset - filtering and sorting

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#175]
Based on input from @yroskov 
We need to be able to
* orderBy
  * created
  * modified
  * title
  * author
```
api.col.plus/dataset?orderBy=["created", "DESC"]
```

We also want to be able to filter the dataset list to see only
* datasets created after last release of scrutinized cat
* datasets modified after last release of scrutinized cat

Since the client has access to the date of the last release, this could simply be
```
api.col.plus/dataset?modified={"gt": "2018-10-25"}
```
i.e. allowing json params for greaterthan and lessthan operators

**Comment by thomasstjerne** [comment]
Maybe simpler
```
api.col.plus/dataset?min-modified=2018-10-25
```

**Comment by mdoering** [comment]
I'd like to avoid passing json parameters, but the min-modified/created solution looks fine to me.
Sorting seems straight forward. What field exactly should `author` be, contactPerson?

**Comment by thomasstjerne** [comment]
> What field exactly should author be, contactPerson?

authorsAndEditors

**Comment by mdoering** [comment]
ok, then use the first entry of authorsAndEditors which is a list

**Comment by thomasstjerne** [comment]
Yes

**Comment by yroskov** [comment]
Contact Person and Author/Editor have different roles. Author/Editor generates content. Contact Person is quite often an another person who is responsible for export and holds routine communications.

**Comment by mdoering** [comment]
Implemented: 
Extended existing [sortBy parameter](https://github.com/Sp2000/colplus-backend/blob/354b5d14083399dd74630383946f078887c5d282/colplus-api/src/main/java/org/col/api/search/DatasetSearchRequest.java#L16)

Extend the search request with modified, created and released props that all act as minimum dates

**Comment by mdoering** [comment]
Also added a `reverse` parameter that rerverses the sort order:
https://github.com/Sp2000/colplus-backend/commit/afc8ef9377b12c5ac9095bd9afc823a9166e7328
