### ISSUE TITLE
3 new fields on the ColSource model

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#176]
Extracted from @yroskov s testing (2018-10-23)
*  “Completeness” [values: 1 to 100%] (Percentage of completeness of species list of the taxon provided by the Source Database)
* “Checklist Confidence” [values: 1, 2, 3, 4, 5] (Quality of taxonomic checklist with values 1 to 5; quality is stated by the custodian in agreement with CoL editor. Confidence indicators are described at http://www.catalogueoflife.org/col/info/databases).
* “Editor’s comments” [this field is new; it was not implemented in old structure. Perhaps later it should be extended into number of fields with management information].

**Comment by mdoering** [comment]
completeness was left out on purpose as I felt this should better be calculated from the species estimates for the sector roots.

confidence should be set at source or dataset level?

comments are already on dataset.notes, do we need both?

ColSource is restricted to the CoL but allows more fine grained metadata.
Dataset level metadata also applies to the provisional catalogue and lists not involved in any catalogue yet. I think its useful to have notes on that level

**Comment by thomasstjerne** [comment]
> confidence should be set at source or dataset level?
On Source (at least thats what @yroskov proposes in his doc)

> comments are already on dataset.notes, do we need both?
@yroskov asked for it, and I see the relevance for dataset split into several sources

In many ways it seems that the ColSource has the more important Meta Data for the editor

**Comment by yroskov** [comment]
Completeness of entire GSD in the metadata is an evaluation of data provider. Completeness, which calculated in the Tree, based on Estimates sometime taken from another authority. Different kind of data.

**Comment by mdoering** [comment]
@yroskov but isn't this redundant and confusing for a user? I never understood and still do not understand the difference in the current CoL portal

**Comment by yroskov** [comment]
There is no redundancy and confusion. Just a simple example, the GSD may include set of 100%-complete genera and another set of 15%-complete genera; and completeness of entire GSD may be evaluated by the author as 65%. 
All 3 Database Qualifiers are subjective evaluation of GSD by its author, his message to the users.

**Comment by mdoering** [comment]
But should those 2 sets then not better be given as estimates for the 2 groups? I must be missing something

**Comment by mdoering** [comment]
If the root taxa of all sectors had species estimates - would we not be able to derive the completeness?

**Comment by yroskov** [comment]
GSD Completeness should stay in metadata. Estimate figure should stay with each taxon above species (where data available).

**Comment by mdoering** [comment]
as you can see in the commit above I already did that.

But can you please try to explain why it is needed in addition to species estimates? It usually helps if we all understand the reasoning

**Comment by yroskov** [comment]
One more. As we discussed in Champaign: we need an option to copy actual number of species into Estimate field, where GSD author ask to do this. This is the only case when GSD Completeness will be equal to all 100%-completed taxa inside GSD sectors.

**Comment by yroskov** [comment]
> If the root taxa of all sectors had species estimates - would we not be able to derive the completeness?
Estimates for taxa of different ranks may come from different sources. In the CoL model, it is not an additive sum. This is a problem of biodiversity science: there is no yet conventional source for species estimates through whole biota, as well as there is no yet complete checklist for all species (CoL is in progress) . As soon as CoL will be completed, we may switch to automatic calculation of estimates in parent taxa from their children, not before.
