### ISSUE TITLE
Name search ordering

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#177]
What name search result ordering is needed from the interface?
The NameSearchRequest now defines: RELEVANCE, NAME, KEY

But is there the need for it?
The only sorting I can foresee is a modification of the NAME order that includes the rank from highest rank to lowest. Sort first by rank, then by scientificName.

Do we ever need sth else? Maybe a plain name ordering without rank if comparing duplicates regardless of their rank?

**Comment by thomasstjerne** [comment]
Yes, plain name ordering is needed as well for dplicate comparison.

**Comment by mdoering** [comment]
so just two sort orders, NAME and TAXONOMIC (1st rank, 2nd name) ?

**Comment by mdoering** [comment]
relevance and key can go?

**Comment by thomasstjerne** [comment]
I think we should also keep the Key - this is often the id provided by the GSD, not just a database id, so it could be useful as well

**Comment by mdoering** [comment]
what is the id provided by GSD? The current GSD ids in the CoL like 10 for Fishbase?
These are all managed, nothing from the sources. And we stick to them in the Clearinghouse to some degree by having their ACEF counterpart to be 1000+ the GSD ID from CoL. But this will vanish over time as the datasets mix so it really is just an opaque database id

**Comment by ayco-at-naturalis** [comment]
You can currently still sort on relevance, and somehow es even calculates score for straight term (equals) queries, and certainly for ngram queries. Unfortunately we use ngram queries for our autocomplete, which we just want to be as fast as possible I guess. For now I kept this a "scoring" query, but I think it would be better to suppress that

**Comment by mdoering** [comment]
We still need a TAXONOMIC sorting which I believe is the default for the UI.
First rank, then name

**Comment by ayco-at-naturalis** [comment]
sounds good (to be honesy it IS now the default), but I have now implemented TAXONOMIC sorting. Will implement it. So we have
NATIVE (default)
NAME
TAXONOMIC

And wse remove KEY

**Comment by mdoering** [comment]
Is the taxonomic search really working? This looks suspicuous to me:

http://api.col.plus/name/search?limit=100&q=poa&sortBy=taxonomic

One of the first records should be a genus called "Poa".
Here the first matches are:

```
Poaphilus (gen)
Poacevirus: (gen)
Poanopsis (gen)
Poaspis (gen)
```

This is not sorted alphabetically

**Comment by ayco-at-naturalis** [comment]
Works now for provided example (and with unit tests)

**Comment by mdoering** [comment]
We are needing a new sort order based on the names index ID (Name.indexNameID) called `INDEX_NAME_ID`

**Comment by ayco-at-naturalis** [comment]
ok could be done quickly
