### ISSUE TITLE
Add modified and authorAndEditors field to dataset response

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#179]
Currently, only created is in the results.
This is needed to be able to filter the list for datasets that have changed since last release.
http://api.col.plus/dataset?limit=100&offset=0&sortBy=modified

**Comment by mdoering** [comment]
modified should only be there once an import has happended. For new datasets its null and we just wiped all

**Comment by mdoering** [comment]
but the ordering seems wrong, the datasets with modified are at the end:
http://api.col.plus/dataset?limit=100&offset=200&sortBy=modified

**Comment by mdoering** [comment]
same thing with authorAndEditors, they are all empty if not indexed as the init script does not provide them

**Comment by mdoering** [comment]
Closing for now, please reopen when sth needs to be changed

**Comment by thomasstjerne** [comment]
Ahh forgot that they could still be indexing, sorry
