### ISSUE TITLE
Search response highlighting

### ISSUE THREAD

**Issue by ayco-at-naturalis** [Sp2000/colplus-backend#181]
- Do we need highlighting, and how do we modify the current response object for it?

**Comment by mdoering** [comment]
Unless @thomasstjerne requires proper highlighting my proposal would be to:

- show which of the currently 3 SearchContent has matched in a new `matchType (SearchContent)` field so we can show results differently 
- show the corresponding matched full string, i.e. either vernacular name, scientificName or authorship in a new `match (String)` field

**Comment by mdoering** [comment]
We do need highlighting

**Comment by ayco-at-naturalis** [comment]
Should I pick this up with priority? NB I've decided to make monday my ColPlus day.

**Comment by mdoering** [comment]
medium prio, but please do before working on a ref search

**Comment by mdoering** [comment]
@ayco-at-naturalis can this be closed?

**Comment by ayco-at-naturalis** [comment]
It's coded & unit tested, but don't know if it satisfies @thomasstjerne yet. Nevertheless I'll close it know. Thomas can of course open it again if he has some requests or find bugs
