### ISSUE TITLE
Temporary 500 internal server errors 

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#182]
This one could be a little tricky, since it is not stable.
But the Taxon info and synonyms endpoints often returns a 500 
However, it may disaapear on a reolad and can therefore not be reproduced in a consistent way.

I have seen both of these return good results and 500´s within few minutes:

http://api.col.plus/dataset/1601/taxon/Thr-1/info
http://api.col.plus/dataset/1601/taxon/Thr-1/synonyms

**Comment by mdoering** [comment]
cant reproduce the errors, @thomasstjerne could you please log here the time when you see those again so we can dig into logs?

**Comment by thomasstjerne** [comment]
Monday 26/11 : 14:30 

Error on taxon info endpoint: http://api.col.plus/dataset/1010/taxon/Fis-22711/info

http://test.col.plus/dataset/1010/taxon/Fis-22711

**Comment by thomasstjerne** [comment]
Monday 26/11 16:07

http://api.col.plus/dataset/1008/taxon/Rep-477/synonyms
There was an error processing your request. It has been logged (ID 86fd200ceff6af03)

http://api.col.plus/dataset/1008/taxon/Rep-477/info
There was an error processing your request. It has been logged (ID e2e8fd638032d8a3).

**Comment by mdoering** [comment]
Thats an interesting one:

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.
### The error may exist in org/col/db/mapper/SynonymMapper.xml
```

**Comment by mdoering** [comment]
shared memory was using the default which was very very low. Increased now to 5GB so this should not happen anymore
