### ISSUE TITLE
Integrity checks: Duplicate names between the GSD and CoL

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#194]
Below is a list of data validation integrity checks used for finding duplicate names between the Global Species Database (GSD) and CoL. Integrity checks also include [data validation](https://github.com/Sp2000/colplus-backend/issues/193) and [testing for duplicates within the GSD](https://github.com/Sp2000/colplus-backend/issues/195). The MySQL code for these tests is currently being updated, but will be provided as soon as possible.

## [B1](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/4.1.3.sql): GSD vs CoL: Identical order
Searching for orders in the GSD that are named identically to orders in CoL
**Typical editorial decision:** For homonyms: no action; for classification conflicts: correct CoL management classification or GSD, or delete/move overlapping sector
   - [ ] Implemented
   - [ ] Tested
## [B2](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/4.1.4.sql): GSD vs CoL: Identical superfamily
Searching for superfamilies in the GSD that are named identically to superfamilies in CoL
**Typical editorial decision:** For homonyms: no action; for classification conflicts: correct CoL management classification or GSD, or delete/move overlapping sector
   - [ ] Implemented
   - [ ] Tested
## [B3](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/4.1.5.sql): GSD vs CoL: Identical family
Searching for families in the GSD that are named identically to families in CoL
**Typical editorial decision:** For homonyms: no action; for classification conflicts: correct CoL management classification or GSD, or delete/move overlapping sector
   - [ ] Implemented
   - [ ] Tested
## [B4](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/4.1.6.sql): GSD vs CoL: Identical genus
Searching for genera in the GSD that are named identically to genera in CoL
**Typical editorial decision:** For homonyms: no action; for classification conflicts: correct CoL management classification or GSD, or delete/move overlapping sector
   - [ ] Implemented
   - [ ] Tested
## [B5](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/4.1.7.sql): GSD vs CoL: Identical accepted species name
Searching for accepted species names in the GSD that are named identically to accepted species names in CoL
**Typical editorial decision:** For homonyms: mark latest name as provisionally accepted or delete duplicated record
   - [ ] Implemented
   - [ ] Tested
## [B6](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/4.1.8.sql): GSD vs CoL: Identical GSD accepted species and CoL synonym names (ACC-SYN)
Searching for accepted species names in the GSD that are named identically to synonyms in CoL
**Typical editorial decision:** Mark synonyms as sp2000_status_id='2' (ambiguous synonym)
   - [ ] Implemented
   - [ ] Tested
## [B7](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/4.1.9.sql): GSD vs CoL: Identical GSD synonym names and CoL accepted species (SYN-ACC)
Searching for synonyms in the GSD that are named identicially to accepted names in CoL
**Typical editorial decision:** Mark synonyms as sp2000_status_id='2' (ambiguous synonym)
   - [ ] Implemented
   - [ ] Tested

**Comment by mdoering** [comment]
Done on backend via #254. Open UI issues found in Sp2000/colplus-frontend#63
