### ISSUE TITLE
Integrity checks: Duplicate names within the GSD

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#195]
Below is a list of data validation integrity checks used for finding duplicate names within a Global Species Database (GSD). Integrity checks also include [data validation](https://github.com/Sp2000/colplus-backend/issues/193), and [testing for duplicates between the GSD and CoL](https://github.com/Sp2000/colplus-backend/issues/194). For most integrity checks a link is provided to the current MySQL implementation of the integrity checks.

## [C1](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.0.0.sql): GSD duplicates: ACC-ACC species (different authors)
Searching within the GSD for duplicate accepted names with different author strings
**Examples:** Aedes burjaticus Kukharchuk, 1973; Aedes burjaticus Kuchartshuk, 1973
**Typical editorial decision:** Homonyms: Mark latest as sp2000_status_id='4' (provisionally accepted name)
   - [x] Implemented
   - [ ] Tested
## [C2](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.0.1.sql): GSD duplicates: ACC-ACC species (same authors)
Searching within the GSD for duplicate accepted names with identical author strings
**Examples:** Sphex pensylvanicus Linnaeus, 1763; Sphex pensylvanicus Linnaeus, 1763
**Typical editorial decision:** Notify GSD and delete one record or mark both as sp2000_status_id='4' if advised by GSD
   - [x] Implemented
   - [ ] Tested
## [C3](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.0.2.sql): GSD duplicates: ACC-ACC infraspecies and infraspecies marker (different authors)
Searching within the GSD for duplicate accepted infraspecies with different author strings
**Examples:** Bracon variator rytrensis Niezabitowski, 1910; Bracon variator rytrensis Telenga, 1936
**Typical editorial decision:** Homonyms: Mark latest as sp2000_status_id='4' (provisionally accepted name)
   - [x] Implemented
   - [ ] Tested
## [C4](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.0.3.sql): GSD duplicates: ACC-ACC infraspecies and infraspecies marker (same authors)
Searching within the GSD for duplicate accepted infraspecies with identical author strings
**Examples:** Afrotyphlops schlegelii petersii (Bocage, 1873); Afrotyphlops schlegelii petersii (Bocage, 1873)
**Typical editorial decision:** Notify GSD and delete one record or mark both as sp2000_status_id='4' if advised by GSD
   - [x] Implemented
   - [ ] Tested
## [C5](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.1.0.sql): GSD duplicates: ACC-SYN species (different parent, different authors)
Searching within the GSD for accepted names that are identical to a synonym assigned to a different species with different author strings
**Typical editorial decision:** Mark synonym as sp2000_status_id='2' (ambiguous synonym)
   - [x] Implemented
   - [ ] Tested
## [C6](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.1.1.sql): GSD duplicates: ACC-SYN species (different parent, same authors)
Searching within the GSD for accepted names that are identical to a synonym assigned to a different species with identical author strings
**Typical editorial decision:** Mark synonym as sp2000_status_id='2' (ambiguous synonym)
   - [x] Implemented
   - [ ] Tested
## [C7](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.1.2.sql): GSD duplicates: ACC-SYN species (same parent, same authors)
Searching within the GSD for accepted names that have an identical synonym with identicial author strings
**Typical editorial decision:** Delete synonym
   - [x] Implemented
   - [ ] Tested
## [C8](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.1.3.sql): GSD duplicates: ACC-SYN infraspecies (different parent, different authors)
Searching within the GSD for accepted infraspecies that are identical to a synonym assigned to a different species with different author strings
**Typical editorial decision:** Mark synonym as sp2000_status_id='2' (ambiguous synonym)
   - [x] Implemented
   - [ ] Tested
## [C9](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.1.4.sql): GSD duplicates: ACC-SYN infraspecies (different parent, same authors)
Searching within the GSD for accepted infraspecies that are identical to a synonym assigned to a different species with identical author strings
**Typical editorial decision:** Mark synonym as sp2000_status_id='2' (ambiguous synonym)
   - [x] Implemented
   - [ ] Tested
## [C10](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.1.5.sql): GSD duplicates: ACC-SYN infraspecies (same parent, same authors)
Searching within the GSD for accepted infraspecies that have an identical synonym with identicial author strings
**Typical editorial decision:** Delete synonym
   - [x] Implemented
   - [ ] Tested
## [C11](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.2.0.sql): GSD duplicates: SYN-SYN species (different parent, different authors)
Searching within the GSD for duplicate synonyms assigned to different accepted names with different author strings
**Examples:** Abacetus reflexicollis (Fairmaire, 1887); Abacetus reflexicollis Straneo, 1949
**Typical editorial decision:** Mark synonyms as sp2000_status_id='2' (ambiguous synonym)
   - [x] Implemented
   - [ ] Tested
## [C12](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.2.1.sql): GSD duplicates: SYN-SYN species (different parent, same authors)
Searching within the GSD for duplicate synonyms assigned to different accepted names with identical author strings
**Examples:** Abax brunnipes Letzner, 1852; Abax brunnipes Letzner, 1852
**Typical editorial decision:** Mark synonyms as sp2000_status_id='2' (ambiguous synonym)
   - [x] Implemented
   - [ ] Tested
## [C13](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.2.2.sql): GSD duplicates: SYN-SYN species (same parent, different authors)
Searching within the GSD for duplicate synonyms assigned to the same parent with different author strings
**Examples:** Abgrallaspis palmae Almeida, 1969; Abgrallaspis palmae Balachowsky, 1948
**Typical editorial decision:** No action
   - [x] Implemented
   - [ ] Tested
## [C14](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.2.3.sql): GSD duplicates: SYN-SYN species (same parent, same authors)
Searching within the GSD for duplicate synonyms assigned to the same parent with identicial author strings
**Examples:** Acanthoderes conifera Zajciw, 1970; Acanthoderes conifera Zajciw, 1970
**Typical editorial decision:** Delete one synonym
   - [x] Implemented
   - [ ] Tested
## [C15](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.2.4.sql): GSD duplicates: SYN-SYN infraspecies (different parent, different authors)
Searching within the GSD for duplicate infraspecific synonyms assigned to different accepted names with different author strings
**Typical editorial decision:** Mark synonyms as sp2000_status_id='2' (ambiguous synonym)
   - [x] Implemented
   - [ ] Tested
## [C16](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.2.5.sql): GSD duplicates: SYN-SYN infraspecies (different parent, same authors)
Searching within the GSD for duplicate infraspecific synonyms assigned to different accepted names with identical author strings
**Typical editorial decision:** Mark synonyms as sp2000_status_id='2' (ambiguous synonym)
   - [x] Implemented
   - [ ] Tested
## [C17](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.2.6.sql): GSD duplicates: SYN-SYN infraspecies (same parent, different authors)
Searching within the GSD for duplicate infraspecific synonyms assigned to the same parent with different author strings
**Typical editorial decision:** No action
   - [x] Implemented
   - [ ] Tested
## [C18](https://github.com/Sp2000/mysql-integrity-checks/blob/master/sql/5.2.7.sql): GSD duplicates: SYN-SYN infraspecies (same parent, same authors)
Searching within the GSD for duplicate infraspecific synonyms assigned to the same parent with identicial author strings
**Typical editorial decision:** Delete one synonym
   - [x] Implemented
   - [ ] Tested

**Comment by mdoering** [comment]
Is there a better terminology than just "duplicate" to differ between the following categories?
How about these:
 - same name, exact same authors: STRICT DUPLICATE
 - same name, potentially the same authors: POTENTIAL DUPLICATE
 - same name, different authors: HOMONYM

How should non existing authors be treated when compared to the same name with authors? As authors being different?

**Comment by mdoering** [comment]
Done on backend via #254. Open UI issues found in Sp2000/colplus-frontend#63
