### ISSUE TITLE
Rename Dataset.catalogue and its values

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#197]
Propose to rename the field to `Dataset.contribution` and allow values `CoL` and `provCoL` to avoid scrutinized which sounds like the dataset itself is considered to be scrutinized or provisional

**Comment by mdoering** [comment]
@thomasstjerne, @yroskov do you agree?

**Comment by yroskov** [comment]
My suggestion is to aggregate datasets (source databases) and products in different projects: "CoL" = scrutinized, "GBIF Clearinghouse", "[Any other in future]", etc. So, field name could be just a "project". Navigating inside one project, I should not see datasets from another project (this is important for my editorial tasks). Note: CoL, been a product in "CoL" project, can be also assigned as a dataset in "GBIF Clearinghouse". Selected datasets from "GBIF Clearinghouse" can be assigned as source databases in "CoL" project.
Inside "CoL" project we need to see a separation between products (such as “The Catalogue of Life”,  “Draft Catalogue of Life”) and source GSDs.  
See 2018-11-06_Editorial_Interface_YRchecks.docs for details.

**Comment by mdoering** [comment]
The "GBIF Clearinghouse" is probably not the right term, as it is not GBIF running it.
And the Clearinghouse is all datasets, not a subset, so its not worth tagging them separately.

We only have 2 highly related products for which we apparently fail to come up with good names. The CoL+ project has called these "Scrutinized Catalogue" and "Provisional Catalogue" (of Life). I am tired to discuss this question over and over again, so I would like to see a quick solution here we can accept for developments - knowing this is intermediate and needs to be revisited with the Global Team probably. Can we just agree on some working terminology for the next month?

Dataset.project, product, produces, contribution, contributesTo, participatesIn, sth like that? project I dont feel is right. How about one of the others? contributesTo feels semantically most correct to me.

And for the values how about "CoL" and "provCoL" ?

**Comment by yroskov** [comment]
Dataset.project is my first choice; contributesTo is my second choice.

>> And for the values how about "CoL" and "provCoL"
"CoL" is OK for me.

Unfortunately, term “Provisional CoL" does not reflect a mix of name lists of various nature. It is a pull of scientific names, might be taxonomically unvetted (non-scrutinised?) names. In better world, this pull should be divided in different categories: “Nomenclators”, “[Alternative] Global checklists”, “Regional checklists”, “Thematic lists”. These 4 categories covers mainly all types of lists with scientific names, which I can see at http://test.col.plus/dataset?limit=150&offset=0. Potential use (usefulness) of the name in CoL+/GBIF backbone very much depends on the category. Users must be warned from which category the name was taken in the CoL+.

What is about “Unvetted” or “Non-scrutinized”? (Hmm, regional checklists contain well scrutinised names, but often in conflicting classifications. Non-scrutinized might be also not a perfect choice).

Yuri

**Comment by yroskov** [comment]
"CoL" and "Clearinghouse"


From: Roskov, Yury
Sent: Tuesday, November 06, 2018 3:50 PM
To: 'Sp2000/colplus-backend' <reply@reply.github.com>; Sp2000/colplus-backend <colplus-backend@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Sp2000/colplus-backend] Rename Dataset.catalogue and its values (#197)

Dataset.project is my first choice; contributesTo is my second choice.

>> And for the values how about "CoL" and "provCoL"
"CoL" is OK for me.

Unfortunately, term “Provisional CoL" does not reflect a mix of name lists of various nature. It is a pull of scientific names, might be taxonomically unvetted (non-scrutinised?) names. In better world, this pull should be divided in different categories: “Nomenclators”, “[Alternative] Global checklists”, “Regional checklists”, “Thematic lists”. These 4 categories covers mainly all types of lists with scientific names, which I can see at http://test.col.plus/dataset?limit=150&offset=0. Potential use (usefulness) of the name in CoL+/GBIF backbone very much depends on the category. Users must be warned from which category the name was taken in the CoL+.

What is about “Unvetted” or “Non-scrutinized”? (Hmm, regional checklists contain well scrutinised names, but often in conflicting classifications. Non-scrutinized might be also not a perfect choice).

Yuri

**Comment by yroskov** [comment]
"CoL" and "Warehouse"
"CoL" and "WarehouseCoL" (unfortunately, not a "CoLwarehouse")


From: Roskov, Yury
Sent: Tuesday, November 06, 2018 3:56 PM
To: 'Sp2000/colplus-backend' <reply@reply.github.com>; 'Sp2000/colplus-backend' <colplus-backend@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [Sp2000/colplus-backend] Rename Dataset.catalogue and its values (#197)

"CoL" and "Clearinghouse"


From: Roskov, Yury
Sent: Tuesday, November 06, 2018 3:50 PM
To: 'Sp2000/colplus-backend' <reply@reply.github.com>; Sp2000/colplus-backend <colplus-backend@noreply.github.com<mailto:colplus-backend@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [Sp2000/colplus-backend] Rename Dataset.catalogue and its values (#197)

Dataset.project is my first choice; contributesTo is my second choice.

>> And for the values how about "CoL" and "provCoL"
"CoL" is OK for me.

Unfortunately, term “Provisional CoL" does not reflect a mix of name lists of various nature. It is a pull of scientific names, might be taxonomically unvetted (non-scrutinised?) names. In better world, this pull should be divided in different categories: “Nomenclators”, “[Alternative] Global checklists”, “Regional checklists”, “Thematic lists”. These 4 categories covers mainly all types of lists with scientific names, which I can see at http://test.col.plus/dataset?limit=150&offset=0. Potential use (usefulness) of the name in CoL+/GBIF backbone very much depends on the category. Users must be warned from which category the name was taken in the CoL+.

What is about “Unvetted” or “Non-scrutinized”? (Hmm, regional checklists contain well scrutinised names, but often in conflicting classifications. Non-scrutinized might be also not a perfect choice).

Yuri

**Comment by mdoering** [comment]
Clearinghouse is already used to refer to ALL datasets in the system. We are looking for the product that extends the CoL with provisional, unvetted information. And that product uses *some* datasets as its source, not all. We should probably stick to provisional catalogue at this stage and seek wider discussions soon

**Comment by mdoering** [comment]
`contributesTo` = `CoL` or `pCat` for now? At least much better than what there is now

**Comment by yroskov** [comment]
contributesTo = CoL or pCat - agreed!
