### ISSUE TITLE
Update webservices to use internal key parameter

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#20]
We decided to use internal keys as the primary mean to retrieve entities from the API.
The native id string is only used as an initial lookup.

The current API still uses the String id in most place. The resource paths all need revised with Name, Taxon, Reference and potentially more becoming root paths not nested under dataset

- [x] DatasetResource
- [x] NameResource
- [x] TaxonResource
- [x] ReferenceResource

**Comment by ayco-at-naturalis** [comment]
**NameResource**
/dataset/{datasetKey}/name --> /name **(list)**
/dataset/{datasetKey}/name --> /name/?datasetKey={dsKey} **(list)**
/dataset/{datasetKey}/name/search --> /name/search **(search)**
/dataset/{datasetKey}/name/{id} --> /name/{key} **(get)**
/dataset/{datasetKey}/name/{id}/basionymGroup --> /name/{key}/basionymGroup **(getSynonyms)**
/dataset/{datasetKey}/name/{id}/verbatim --> /name/{key}/verbatim **(getVerbatim)**
/dataset/{datasetKey}/name/{id}/acts --> /name/{key}/acts **(getActs)**
**New:** /name/{id}/{datasetKey} **(lookup)**

**TaxonResource**
/dataset/{datasetKey}/taxon --> /taxon **(list)**
/dataset/{datasetKey}/taxon --> /taxon/?datasetKey={dsKey} **(list)**
/dataset/{datasetKey}/taxon/{id} --> /taxon/{key} **(get)**
/dataset/{datasetKey}/taxon/{id}/info --> /taxon/{key} **(getInfo)**
**New:** /taxon/{id}/{datasetKey}  **(lookup)**

**VerbatimResource**
/dataset/{datasetKey}/verbatim --> /verbatim **(list)**
/dataset/{datasetKey}/verbatim --> /verbatim/?datasetKey={dsKey} **(list)**
/dataset/{datasetKey}/verbatim/{id} --> /verbatim/{key} **(get)**
**New:** /verbatim/{id}/{datasetKey} **(lookup)**


**ReferenceResource**
/dataset/{datasetKey}/reference --> /reference **(list)**
/dataset/{datasetKey}/reference --> /reference/?datasetKey={dsKey **(list)**
/dataset/{datasetKey}/verbatim/{id} --> /reference/{key} **(get)**
**New:** /reference/{id}/{datasetKey} **(lookup)**

**Comment by mdoering** [comment]
Small suggestions & additions:
**Name**:
/name/{key}/basionymGroup: lets call that synonyms instead

**Taxon**:
/taxon/{key}/info is missing the info in path
we need 3 more important calls to browse the tree:
/taxon/root/{datasetKey}
/taxon/{key}/parents
/taxon/{key}/children 
/taxon/{key}/synonyms

**Verbatim**:
do we need that resource at all? I dont think, its accessible via the name & taxon resources already

**Reference**:
good for now, but in the future I reckon we would like to also have a way to search and list names/acts within a given reference
 /reference/search
 /reference/{key}/acts

**Dataset**:
no changes in the API here, but for completeness:
/dataset **(list)**
/dataset/search **(search)**
/dataset/{key} **(get)**

and 2 new additions
/dataset/import **(list datasetimport)**
/dataset/import/last **(get latest successful import metric)**

**Comment by mdoering** [comment]
Here a summary again of all web resources that should exist (and be [documented in RAML ](#20)afterwards):
-----
**DatasetResource**
/dataset?q=query (page, optionally filter by full text query q)
/dataset/{key} (get)
/dataset/import (list all datasetimports, ordered by attempt)
/dataset/import/last (get latest successful import metric)

**NameResource**
/name?datasetKey={dsKey} (list or search if q exists)
/name/search (search - better move to taxon???)
/name/{id}/{datasetKey} (lookup)
/name/{key} (get)
/name/{key}/synonyms (getSynonyms, homotypic)
/name/{key}/verbatim (getVerbatim)
/name/{key}/acts (getActs)

**TaxonResource**
/taxon?datasetKey={dsKey}&root=true (page, optionally filter by datasetKey and root taxa only, i.e. parentKey=null)
/taxon/{id}/{datasetKey} (lookup)
/taxon/{key} (get)
/taxon/{key}/info (getInfo)
/taxon/{key}/parents
/taxon/{key}/children
/taxon/{key}/synonyms

**ReferenceResource**
/reference?datasetKey={dsKey}&q=query (page, optionally filter by datasetKey and full text query q)
/reference/{id}/{datasetKey} (lookup)
/reference/{key} (get)
/reference/{key}/acts.(page through all acts with referenceKey=key)

**Comment by mdoering** [comment]
Still missing resources:

- /taxon/{key}/synonyms
- /taxon: misses optional, boolean root parameter to filter to root taxa only (i.e. parentKey=null)
- /reference/{key}/acts is missing still
