### ISSUE TITLE
Enable NOT NULL searches via URLs

### ISSUE THREAD

**Issue by ayco-at-naturalis** [Sp2000/colplus-backend#202]
Client can specify IS NULL searches by including a query parameter, but without providing a value. e.g.

&datasetKey=1000&issue=

But we need a special value value for IS NOT NULL searches. Propsal: @NOT_NULL@ (case insensitive)

&datasetKey=1000&issue=@not_null@

**Comment by ayco-at-naturalis** [comment]
Markus, this is how it now works, if you agree, you can close the issue; if you like another mechanism, let me know

**Comment by mdoering** [comment]
I am not sure if you can pass NULLs like this currently. 
If we go with `@NOT_NULL@` then I propose to also use `@NULL@`

@ needs URL encoding (%40) though which isn't bad. But if we find sth that avoids that it would be better. _ ~ are ok to be used.

How about `_NULL_` and `_NOT_NULL_`?

**Comment by mdoering** [comment]
whatever it is needs to be understood by the NameSearchRequest as we do value type validation there already. So a string value like `@NOT_NULL@` will be rejected if the parameter is supposed to be an integer like datasetKey for example

**Comment by ayco-at-naturalis** [comment]
OK ... Il will anyhow move these constants out of the dao module into the NameSearchRequest class b/c they are part of the public API

**Comment by ayco-at-naturalis** [comment]
And yes ... we need to intercept these values before they converted to enums/integers

**Comment by ayco-at-naturalis** [comment]
Long since fixed
