### ISSUE TITLE
Make ES index name configurable & use alias

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#203]
We should make the ES index name being used configurable, defaulting so sth sensible.
That allows us to swap indices and rebuild them offline.
Probably a new setting in IndexConfig

**Comment by ayco-at-naturalis** [comment]
Yes. It's now a constant, but we should make it part of the IndexConfig section of EsConfig. Will do that.

**Comment by mdoering** [comment]
We now have an environment setting in EsConfig which is used to prefix all index names.
Do we need anything more? If we'd want to rebuild all indices we can do so in a new environment and then switch the prod config to point to that, e.g. prod2

**Comment by mdoering** [comment]
In order to rebuilt and update an ES schema without going offline with the main services lets go for:

 - use an alias e.g. `prod-nu` that points to the actual index that is being used, e.g. `prod-nu-2019-12-06`
 - use an iso date in the actual index name that tell us the creation date hence the schema
 - allow the backend code to accept any arbitrary index name (alias or not) to work with which will still be prefixed with the environment. So configure `nu-2019-12-6` to become `prod-nu-2019-12-6`

**Comment by mdoering** [comment]
see also #586

**Comment by mdoering** [comment]
removing EsConfig.environment in favor of a IndexConfig.name property that can be freely configured to any index or alias name. That allows us to run the rebuild index cli with a different index name than the current one used by prod
