### ISSUE TITLE
searching for smithi and smithii returns different results

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#207]
smithi matches 56, smithii only 15 name usages:
http://api.col.plus/dataset/1010/name/search?q=smithi
http://api.col.plus/dataset/1010/name/search?q=smithii

Using the [SciNameNormalizer](https://github.com/Sp2000/colplus-backend/blob/master/colplus-common/src/main/java/org/col/common/tax/SciNameNormalizer.java) as an Analyzer (for both query and indexing) this should yield the same results.

**Comment by ayco-at-naturalis** [comment]
Probably best done after facets

**Comment by ayco-at-naturalis** [comment]
Created 2 unit tests for it, and indeed works after introduction of ScieNameNormalizer
