### ISSUE TITLE
NameSearch: Allow multivalue issue param

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#208]
This should give results for both issues ( OR operator)
/dataset/1010/names?issue=inconsistent%20authorship&issue=name%20match%20ambiguous

**Comment by ayco-at-naturalis** [comment]
Are you sure this is happening? E.g. for http://api.col.plus/name/search/?issue=inconsistent%20authorship&issue=name%20match%20ambiguous you do get results where only one of the specified issues is present in the document.
