### ISSUE TITLE
Allow for finer semantics in NameSearchRequest

### ISSUE THREAD

**Issue by ayco-at-naturalis** [Sp2000/colplus-backend#216]
At some point editors will probably want to specify things like

- Give me documents that match ALL of the specified issues (rather then ANY)

- Give me documents for which ALL of the specified name fields are set

- Give me documents where NONE of the specified name fields are set

To keep semantics consistent, when a parameter has multiple values, this results in an OR query. That makes sense for issues, but (from a users perspective) maybe not for name fields. Hence at some point we probably need to enrich the NameSearchRequest object so the frontend developer can express these subtleties through it

**Comment by mdoering** [comment]
Does not seem to be an issue for now, so closing it until someone actually requests it
