### ISSUE TITLE
Add entire higher classification to search index

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#220]
For metrics about a certain higher group, e.g. a single, whole family the index needs to know about all usages that are included in such a higher taxon. We can then provide counts and a filter to restrict a search to a certain group only.

Add a List if all higher taxon ids to the NameUsageWrapper and store it in ES.
Retrieving the entire classification ids can be expensive. Try to implement a taxonomic tree iteration that starts at the top tree roots and visits all children remembering the entire path of parent ids as an alternative implementation of the [NameUsageMapper.processDatasetTaxa](https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/main/java/org/col/db/mapper/NameUsageMapper.java#L24) method

**Comment by mdoering** [comment]
@ayco-at-naturalis We also need a way to filter by higher taxa.
Suggest to add a new NameSearchParameter.TAXON_ID that gets matched against the list of taxonIDs of all parents in the index

**Comment by ayco-at-naturalis** [comment]
Ah ... I thought this request would come some time :-)

**Comment by mdoering** [comment]
All NameSearchParameter should be searchable.
I think we should do a unit test that goes thru each parameter and makes sure its supported

**Comment by ayco-at-naturalis** [comment]
All parameters are searchable as long as I include them in a simple parameter-to-field lookup; the reset happens automatically; but I will nonentheless unit test this for each and every parameter.

I was thinking, however, maybe we should include all **fields** that can either searched, sorted or aggregated on as a NameSearchParameter and in NameSearchParameter's constructor tell it what it can be used for (QUERY,SORT,FACET); this allows for even more automation, which will prbably pay of when implementing reference search.

**Comment by mdoering** [comment]
Can we keep that as an enhancement in a new issue for now? I can't see immediately what we gain having the ES fields linked with the parameter - maybe to auto construct ES queries.

Right now all params should be usable as a filter and for aggregation. Ordering is entirely different

**Comment by ayco-at-naturalis** [comment]
They  **are** currently linked and auto-constructed; it's just that I must now do separate separate lookups for query/facet fields and sort fields; it's minor and indeed I will postpone that if/when things need to become more generic when implementing ref search.
