### ISSUE TITLE
Included createdBy on sectors

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#223]
It would be nice to be able to display who created a sector:
http://api.col.plus/sector?sourceKey=1008

e.g.: 

```
   {  
      "key":3,
      "subject":{  
         "id":".ekQ9"
      },
      "created":"2018-11-30T15:52:41.021394",
      "createdBy": { 
                              "key":1,
                              "username":"thomasgbif",
                              "firstname":"Thomas Stjernegaard",
                              "lastname":"Jeppesen"
                            },
      "modified":"2018-11-30T15:52:41.021394",
      "colSourceKey":1008
      "target":{  
         "id":"root"
      },
      "mode":"attach"
   }
```

**Comment by mdoering** [comment]
the latest version actually has a created/modifiedBy that returns the int key of the user.
With upcoming graphql I would love to keep it that way and not expand the user on the server side already. But it reminds me that we dont have a way to lookup user keys yet...

**Comment by mdoering** [comment]
`/user/1234` will return the user with just key, username, first- & lastname & country
