### ISSUE TITLE
Add editorial decision to apply lifezone to all descendants

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#224]
Can a single editorial decision class be made more generic to accomodate various kind of decisions to be applied to the target taxon only or all descendants (includeDescendants flag)? A `type` enum property maybe with a Map<String, Object> value?

Should all decisions apply to the source records from a sector? Taxa managed within the CoL (e.g. newly created higher taxa) can be edited directly, but then its a different interface...

**Comment by mdoering** [comment]
Adding 3 more properties to EditorialDecision that can be used in UPDATE mode:
```
  private Boolean fossil;
  private Boolean recent;
  private Set<Lifezone> lifezones;
```

**Comment by mdoering** [comment]
Still needs to be applied on SectorSync

**Comment by mdoering** [comment]
@yroskov we agreed to apply lifezone & fossil flags changed by editorial decisions to all descendants.
But what about information from the (GSD) source? If a source claims a family is fossil and not recent should that also be applied to all descendants? Or do we want to flag issues for manual review if descendants are treated differently?

**Comment by yroskov** [comment]
Both "extinct" and "fossil" flags should be applicable on species/ifraspecies level. This is a requirement for GSD*. Status of all taxa above should be "calculated" in the CoL automatically: if all children have "extinct" flag, parent taxon is extinct; if one of children extant, parent taxon is extant. 
*>If a source claims a family is fossil and not recent should that also be applied to all descendants?
We have no mechanism to check data integrity in this area inside GSD. Thus, only information on species/infraspecies level may work.

**Comment by mdoering** [comment]
That means fossil/extinct flags from sources should be ignored for genera and above and only calculated? Also for lifezones?
IRMNG for example has really good information about fossil genera. It would be a shame to ignore that entirely. Maybe the exception in using also genera is if they are terminal taxa and do not include species.

**Comment by mdoering** [comment]
How about we have a setting on the dataset level that defines which highest rank is to be considered for fossil flags - which defaults to species but can be set to genus in IRMNG?

**Comment by yroskov** [comment]
Yes, it's a good idea.
CoL uses IRMNG sectors with zero species only. 
Possible solution: a default rule focused species, and custom option for higher taxa in sectors with zero species.

**Comment by deepreef** [comment]
Just a word of caution: technically the property of "fossil" applies to specimens, not taxa.  A species is considered a fossil species if all known specimens (or, at least the type specimen) is a fossil. If you do have a fossil flag for higher ranks, there should be a system that regularly checks for discrepancies (i.e., non-fossil children within a fossil-flagged genus or family).  These checks should probably be done anyway, to bring attention to genera & families that have both fossils and non-fossils within them, to verify whether the children are flagged appropriately.  You also need to decide whether a genus/family gets flagged as a fossil *only* when *all* children are fossils; or if a single fossil child taxon justifies the flag for the higher group; or if some ratio of fossil/non-fossil children is established as a threshold.

I like the suggestion of allowing flags on higher ranks when those names have no children.  But I'm not sure it's wise to track this at the dataset level.

**Comment by mdoering** [comment]
Thanks Rich. You point out an issue which I always wanted to ask you about.

We have two independent fossil & recent flags on the taxon, indicating whether the organism is known to have fossil records and existed in the recent time (~holocene). They can obviously be both true. 

In such cases does it matter if the type specimen is a fossil? Does that influence the applicable nomenclatural rules for a name? Should we try to capture that on for name? Originally in addition to the taxon flags we also has a fossil flag on the name, but since there are hardly any sources I decided to drop it again.

I assume it is safe to render a name with † in case it is only known from fossils, just like WoRMS does:

> Crithionina palaeozoica Conkin, 1961 † 

http://www.marinespecies.org/aphia.php?p=taxdetails&id=914032

**Comment by mdoering** [comment]
And do you know a case where the type is a fossil and the species is still alive?

**Comment by deepreef** [comment]
@mdoering -- while fossil specimens certainly can be types, and there is a rule about genus name suffixes as they apply to fossil taxa (and a few other rules related to ichnotaxa), there is nothing in the Zoological Code that I am aware of that has bearing on whether a type is a fossil or non-fossil. While (as I mentioned) the technical definition of a "fossil taxon" is "a taxon known only (or primarily?) from fossil material" (i.e., strictly speaking, taxa are not fossils; but their representative specimens are); that's probably overly pedantic for this context.  I don't think there is a strong need to push into determine whether they type specimen (or other specimens) are fossils when asserting a taxon to be flagged as "Fossil". For species, I think the implication is sufficient that the species is known primarily (or exclusively) on the basis of fossilized material.

Yes, I think rendering the name with a † symbol is the most often-used standard.

I'm not aware of any case where a type is a fossil but the species still exists, but the last time this conversation came up a number of years ago, I vaguely remember an example of a mollusk that might be known from both fossil and living examples.  Of course, a lot depends on exactly how one defines "fossil"!

**Comment by mdoering** [comment]
Thanks Rich. I am closing this issue here in favor of splitting it into 2 separate issues:
Apply editorial decisions during sector sync: #290
Calculate lifezone & fossil flags for higher taxa: #289
