### ISSUE TITLE
Include classification in indexed synonyms

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#227]
The NameUsageWrapper for synonyms should also contain the classification of the accepted taxon.
Getting it is not as straight forward as for taxa. Options to consider:

a) merge taxon and synonym method into one complex call again
b) traverse whole tree again, ignoring the taxa just collecting the classification
c) start bottom up from synonyms, looking up the classification in a separate call (can even be done in mybatis) hoping postgres does some caching

follow up from #220

**Comment by ayco-at-naturalis** [comment]
or just maybe as a postprocessing stage in ES itself (but probably not b/c you have none of the relational goodies)

**Comment by mdoering** [comment]
We should also consider that we need to update all effected usages when a single parent of a classification changes. I.e. in a managed dataset or the draft catalogue, if a phylum is renamed we need to update all its descendants (both taxa & synonyms) in ES

**Comment by ayco-at-naturalis** [comment]
What I don't understand is: does a synonym always inherit the classification of the accepted name? What if it was synonymized from a completely different family (or up) ... or does this not happen in practice?

**Comment by ayco-at-naturalis** [comment]
@mdoering I think I am close to a solution - basically your option (a). The query generated by MyBatis is (of course) monstrous and currently painfully slow. However, I noticed there are hardly any (unique) indexes or even primary keys defined in lieu of the surrogate keys that we ditched.

Also we could freeze the query into a view, hoping that Postgres at least won't waste time on figuring out an execution plan

And also, we could add an extra parameter to the processDataSetTaxa, namely either a rank or a taxonId, from which we'll work downwards. This way, we won't process the whole dataset when only a family is renamed. Would that be an idea?

**Comment by ayco-at-naturalis** [comment]
Are the id, taxon_id and name_id columns in synonym deliberately nullable columns?

**Comment by ayco-at-naturalis** [comment]
Ah - primary key constraints are not supported on partitioned tables :-( :-)
Let's see how fast things get with regular indexes

**Comment by ayco-at-naturalis** [comment]
Ouch, you can't create any index on a partitioned table.

**Comment by ayco-at-naturalis** [comment]
That must severely impact PG performance for the larger datasets, even for less than monstrous queries like the recursive one for processDataSetTaxa

**Comment by mdoering** [comment]
the indices and prinary keys are define on each partion. check out PartitionManager I think it is called. Wirh pg11 you now can also create indices and primary keys on the entire master table, but Im not sure how that performs and I think we need it only within a dataset anyways

**Comment by mdoering** [comment]
synonym should have non null name id and taxon id, but it might been lost due to partitioning (which we did with pg10 still). now on pg11 we can do that better, Ill check. Requires embedded pg11 for tests though which we dont easily get

**Comment by mdoering** [comment]
Its in [DatasetPartitionMapper.buildIndices()](https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/main/resources/org/col/db/mapper/DatasetPartitionMapper.xml#L35)

**Comment by mdoering** [comment]
If you want to test performance please use PG11, it might be very different for partitioned tables

**Comment by ayco-at-naturalis** [comment]
Yes, I figured it out, but I've found another solution that so far seems very fast (tested it on ITIS), using ES to add the classification to the synonyms. I still have another branch that does everything in SQL ,though, in case we run into non-linearity problems with the really big datasets.

However, the BatchResultHandler stubbornly seems to misreport the number of name usages to be processed (whether taxa or synonyms), even though I do now close the handler. For taxa, the number reported by the ES code corresponds to the number I get from manual SQL on the psql command line. For synonyms, the number reported by the batch handler does correspond, but  even when I started counting and adding batch size first thing after the batch handler hans them over, the numbers don't add up.

Will investigate this when I come back from vacation.


`65589 [main] DEBUG o.c.d.m.N.processDatasetTaxa - <==      Total: 157205 
66391 [main] INFO  org.col.es.NameUsageIndexServiceES - Successfully inserted 153036 name usages

colplus=# select count(*) from taxon;
 count  
--------
 153039
`

**Comment by ayco-at-naturalis** [comment]
Payload can now optionally be zipped (shrinks documents to half their original size, notably synonyms get drastically smaller)

**Comment by mdoering** [comment]
nice, good progress! If ES indexing becomes real slow now we should also consider to make it asynchroneous

**Comment by ayco-at-naturalis** [comment]
I will anyhow keep the SQL-only versie (i.e. the SQL in the mapper.xml) ... with that I can easily swap between the 2 implementations
