### ISSUE TITLE
config.yaml missing in readme

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#232]
The config.yaml is missing in the [readme](https://github.com/Sp2000/colplus-backend#run-the-col-application-locally). There is a config.yaml [here](https://github.com/Sp2000/colplus-backend/blob/master/colplus-ws/src/main/resources/config.yaml), but I don't know if it's the right one?

**Comment by mdoering** [comment]
Thats the right one, yes. For the colplus-ws at least, the colplus-admin server which does the indexing needs a slightly different one. The entire README needs an update to be honest
