### ISSUE TITLE
Can't force re-import of a changed dataset

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#239]
There's a bug currently for [Unit Test: C3](http://test.col.plus/dataset/2056/metrics) where I can't get the importer to update a zip archive that has been changed. The importer reports it as [unchanged in the clearinghouse](http://test.col.plus/imports/finished?limit=25&offset=0&state=unchanged&state=failed&state=canceled&state=finished):

Doing a manual import just causes the importer to report as unchanged again. It's not logged in Kibana because it's not detected as an error.

I copied C4.zip to C3.zip to debug something else and then replaced it again with the original C3.zip.

**Comment by gdower** [comment]
I verified that the C3.zip archive contains plant data instead of animal data.

**Comment by mdoering** [comment]
I manually checked the current C3.zip md5 hash and it was different from the last imports up to attempt 4: http://api.col.plus/dataset/2056/import?limit=100

I then triggered a new import manually and it imported the new version fine as attempt 5, now reporting the correct current MD5 hash.

Maybe it takes github a little to update its files?

**Comment by mdoering** [comment]
If you check the POST payload the frontend submits it does not set force to true:
`{datasetKey: 2056, priority: true, force: false}`

Transferred to https://github.com/Sp2000/colplus-frontend/issues/106
