### ISSUE TITLE
Upgrade to Java 11

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#241]
Java 11 is the latest stable and long running java version we should move to.
It has some nice additions for [reactive streams](https://thepracticaldeveloper.com/2018/01/31/reactive-programming-java-9-flow/) and cleaner ways of dealing with [immutable collections](https://docs.oracle.com/en/java/javase/11/core/creating-immutable-lists-sets-and-maps.html#GUID-DB0865D2-C052-40BC-A3DC-20FCB3088DC9).

Dropwizard seems not to have troubles with java11 still, but people have [succeeded](https://groups.google.com/forum/#!searchin/dropwizard-user/java$209|sort:date/dropwizard-user/m1lZsLeFteU/j70J9PAUBAAJ):
 - https://github.com/openregister/openregister-java/pull/499
 - https://github.com/dropwizard/dropwizard/issues/2589

**Comment by ayco-at-naturalis** [comment]
Dropwizard is fine (now using it for something else), but some colplus-backend tests fail because of reflection in Mockito
