### ISSUE TITLE
Create exports in order to temporarily use the "old" CoL interface

### ISSUE THREAD

**Issue by ruud-altenburg** [Sp2000/colplus-backend#242]
The current CoL interface will be temporarily used as an interface for the CoL+ database. In order to achieve this with a minimal effort, the data should be presented to the current conversion tool in the form in currently accepts. This is the Assembly_Global database.

The conversion tool does the following:

1. Verify data in Assembly_Global and create the 'taxa' table. This table is used as a the base for import into the "base scheme" database.
2. Copy the data from Assembly_Global to the "base scheme" database.
3. Create auxiliary tables in the "base scheme" database that are used mainly for searching/browsing.

This solution may not be the most elegant (it adds a further two steps to the conversion), but it will require the least work. 

Possible negatives:

1. The tools currently available to Species 2000 team should still be used to add species estimates.
2. We should have a proper look at the so-called dead ends in the tree (maintained by Yuri).

So, the requirements:

Create a set of csv files matching the contents of the Assembly_Global database (taxa table not required).

**Comment by mdoering** [comment]
It is not feasable to maintain data in the production db, i.e. species estimates have to come from CoL+.
Can we include them in the CSVs somehow?

Where is the exact assembly global schema described that you expect? Or would you be able to list all files with columns that you expect?

**Comment by ruud-altenburg** [comment]
Maintaining the estimates in CoL+ should not be a problem.

Assembly_Global is the ACEF database you probably pulled the data from to your database? I will send you a dump (MySQL...)!

**Comment by ruud-altenburg** [comment]
Available for a week at https://we.tl/t-5ctqltHGFe

**Comment by ruud-altenburg** [comment]
Here's a dump of the estimates database: https://we.tl/t-GBqd8zxO0B 

There are major flaws in this database of course. The combination of kingdom + rank + name may not be fool proof. There's a lot of redundancy for the references. But this data really could not be stuffed into the CoL database, as this is being rebuilt from scratch with every edition.

**Comment by ruud-altenburg** [comment]
Hallo @mdoering, what kind of horror stories have they been telling you? :)

The only data cleaning that's happening is when the taxa table is created. It checks for things such as valid taxa being children of synonyms and taxa/references that are being linked to through foreign keys but not being present. (Sub)genera are created when the taxa table is compiled.

I create a report of (potentially) problematic taxa at the very end of the conversion (duplicates etc), but nothing was ever done with that.

For me it would be even easier if you would create the taxa table, then we could skip that step. We do need the other tables as well though...

**Comment by mdoering** [comment]
does the taxa table habe a parent child hierarchy? that would be lovely

**Comment by ruud-altenburg** [comment]
Yes. Both parent_id and a full hierarchy (as "Kingdom_Class_Order_etc") are present.

**Comment by mdoering** [comment]
and both are needed or is parent-id enough?

**Comment by ruud-altenburg** [comment]
If the other one is needed I could easily generate it.

**Comment by mdoering** [comment]
Script is moved to https://github.com/Sp2000/colplus-repo

**Comment by mdoering** [comment]
Conversions are shown here, so far test data:
 - http://workbench.catalogueoflife.org/col_plus/
 - http://workbench.catalogueoflife.org/converter_plus/

**Comment by mdoering** [comment]
mostly done, still to be done:

- [ ] test with real data incl. common names, distributions & references
- [ ] package up logo images in archive subfolder with datasetKey as name
- [ ] rank markers

**Comment by mdoering** [comment]
@ruud-altenburg can you tell us what you need for populating the release info pages?
http://www.catalogueoflife.org/col/info/about

**Comment by mdoering** [comment]
@gdower can we host/manage the info pages even in github?

**Comment by ruud-altenburg** [comment]
@mdoering I don't if you have access to the workbench, but there's a section there where Yuri can modify some application-related pages/settings. Deployment > 3. ACI and Info pages

I have actually moved the info pages templates out of git (even though they are an integral part of the application, which crashes without them), because it was impossible to keep them up-to-date.

**Comment by ruud-altenburg** [comment]
There should be plenty of options to recreate something similar to the webmin setup. It should be behind a login obviously.

**Comment by gdower** [comment]
@mdoering, I think hosting the info pages in github.com could work in the short-term. @ruud-altenburg, the main reason why they were probably hard to keep up to date in github was because the info pages were being modified on webmin instead of on github.

**Comment by mdoering** [comment]
Created separate issue to host info pages: https://github.com/Sp2000/colplus-backend/issues/336

**Comment by gdower** [comment]
@ruud-altenburg, would it be okay if I remove this [.gitignore](https://github.com/Sp2000/AC_Interface/blob/master/application/views/scripts/.gitignore) file so that the info pages are added back to the AC_Interface? Or does it make sense to setup a separate git repo for the info pages? We'll need to pull updates to the info pages from the repo when the new CoL+ monthly editions are released, but perhaps you already pull the whole AC_Interface repo when deploying new CoL editions?

Once that's done I'll be able to complete #336.

**Comment by mdoering** [comment]
Only species estimates exports missing, creating a dedicated issue for it:
https://github.com/Sp2000/colplus-backend/issues/383
