### ISSUE TITLE
option to get a sector by dataset key

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#244]
Currently we have:
http://api-dev.col.plus/sector?sourceKey=2044

**Comment by mdoering** [comment]
Ouch, I only changed the editorial decision endpoint to use an optional datasetKey param.
Changing sectors too so you can either list them all or filter by dataset or colsource

**Comment by mdoering** [comment]
The API should list all sectors optionally filtered by datasetKey and colSourceKey:
https://github.com/Sp2000/colplus-backend/blob/master/colplus-ws/src/main/java/org/col/resources/SectorResource.java#L30

There is also a method to list broken sectors with a flag target=true that toggles between broken subjects (taxa in source dataset) or target taxa (taxa in catalogue)
