### ISSUE TITLE
datasetKey of a sector becomes the draft datasetKey

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#245]
When posting a new sector to the draft with datasetKey=2044, the datasetKey is 3 (draft) when retrieved from tree API:
http://api-dev.col.plus/dataset/3/tree/9f5bc60c-ab46-4679-8422-5f4cc802cdd0/children?limit=500&offset=0

**Comment by mdoering** [comment]
ouch
