### ISSUE TITLE
Use username as primary key for Users?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#248]
We use an integer key for users. If we would switch to the username instead we might not need to lookup users when visualizing the modified/created user on all entities.

@thomasstjerne is that reasonable and saving lookup calls for the frontend? For the backend it doesn't matter

**Comment by thomasstjerne** [comment]
It doesn´t matter a lot. There are only few calls to get usernames beacause they are not displayed in tables. It is decorating with dataset that gives lots of calls.
