### ISSUE TITLE
Add editorial decisions and sectorKey to the search index

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#255]
It should be searchable by decision type and also possible to get only names with no decision (to narrow the task list of the editor)

**Comment by mdoering** [comment]
@thomasstjerne do you want to search decisions on their own or only related to their subject name usage? I was thinking the later, so you can use decision types (mode) and their absence to filter the name usage search.

**Comment by thomasstjerne** [comment]
Yes, exactly the latter.

**Comment by mdoering** [comment]
Adding NameSearchParameter.DECISION_MODE

**Comment by mdoering** [comment]
@thomasstjerne do we also need to have sectors or at least their presence/absence in the index?

**Comment by thomasstjerne** [comment]
Not sure, but I imagine it it could be useful to know if a name belongs to a sector.
But I think it would only make sense if all descendants of the root would be marked

**Comment by mdoering** [comment]
then lets leave that out for now for the source datasets. 
But we should index the sectorKey in the catalogues though, they are present on all descendants and tell you where a taxon came from. I will add NameSearchParameter.SECTOR_KEY

**Comment by ayco-at-naturalis** [comment]
Just to be sure: I assume the entire Decision object needs to be stored.

**Comment by mdoering** [comment]
@thomasstjerne would it be good enough to return a decisionKey with each name usage just as we do with sectors? Otherwise we need to update the ES index each time we change a decision. Well, we need to do for id changes each time anyways. And if we want the decision mode as a filter parameter than also if the mode changes.

Question: can we live with just a sectorKey and decisionKey on a usage and to filter on their presence/absence only? I feel that should be ok as most usages dont have either and if they do we should be able to load them one by one

**Comment by mdoering** [comment]
The sectorKey for Taxon already exists and gets populated in mybatis on the NameUsageMapper methods, but it only ever exists on the catalogues, never regular datasets.

The decisionKey can be present on any non catalogue dataset, but its not yet in NameUsageMapper.
@ayco-at-naturalis should I add this to NameUsageMapper?

**Comment by mdoering** [comment]
__sectorKey__
 - Taxon: taxon table has a sector_key to expose
 - Synonym: the sector key from the accepted taxon should be used
 - BareName: sectorKey is always null

__decisionKey__
 - Taxon/Synonym/BareName: not on Taxon, Synonym or Name. should replace NameUsageWrapper.decision
Currently a decision can only be tight to a Taxon, but that needs to be changed. See https://github.com/Sp2000/colplus-backend/issues/283

**Comment by ayco-at-naturalis** [comment]
Given that null values for decision keys are pretty meaningful (judging from your discussions @thomasstjerne and @mdoering), is it likely that decision key is going to be used as a facet, and if yes, would you like a facet (group) for the NULL value? Currently, NULL values never become facets, but Elasticsearch allows you to create a "null bucket". I guess it's to late in the game for the global team meeting, but I could implement this later on.

**Comment by ayco-at-naturalis** [comment]
decisionKey and sectorKey added to EsNameUsage class (and hence the ES index), and created full round trips (NameUsageWrapper -> EsNameUsage -> insert -> query -> EsNameUsage -> NameUsageWrapper) for both fields in https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/test/java/org/col/es/NameSearchTestAllParamsTest.java

**Comment by mdoering** [comment]
For decision keys I dont think we will ever aggregate on them, but for sectorKey this indeed might make sense. The null value as it is would represent the CoL classification, but maybe we could also change that and create a real sector for it so its basically non null.
