### ISSUE TITLE
Should fossil, recent and lifezone properties be applied to descendants?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#256]
If a family is marked with lifezones, isFossil or isRecent - should this be applied to all included taxa?
@yroskov what do you think? I recall #224 doing this for editorial decisions

**Comment by mdoering** [comment]
If so we would also need to flag issues for contradicting flags found in descendants

**Comment by yroskov** [comment]
Information on distribution, ecological environment, etc. for taxa above species should be additive sum of children species distribution, ecological environment, etc. 
Paleo vs Recent: if ALL children species in a genus/family/etc. are known as fossilised specimens, higher taxon should be marked as paleo or extinct taxon.

**Comment by mdoering** [comment]
superceeded by https://github.com/Sp2000/colplus-backend/issues/289
