### ISSUE TITLE
Include gbifPublisherKey in name usage search index

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#257]
Especially for Plazi with thousands of published datasets we need to provide total counts across all datasets. Ideally even more flexible queries. Including the Dataset.gbifPublisherKey on all name usages in the search index would therefore be ideal

**Comment by mdoering** [comment]
Adding NameSearchParameter.PUBLISHER_KEY

**Comment by ayco-at-naturalis** [comment]
Added publisherKey field to EsNameUsage (and thus ES document type). The NameUsageWrapper's publisherKey field is properly transferred to EsNameUsage and on to the index, and can be queried back . See [NameSearchTestAllParamsTest.java] (https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/test/java/org/col/es/NameSearchTestAllParamsTest.java).
