### ISSUE TITLE
Sortordering: reverse=true ignored by name search

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#258]
This only existed for dataset search so far. I take this as a feature request?

**Comment by ayco-at-naturalis** [comment]
I had apparently already built in reverse sorting including unit tests (just waiting for the API to require it).

Reverse sorting can now be done for names. Naturally not for NATIVE sorting. For taxonomic sorting the reverse parameter is also picked up, but it reverses the ranks only, not the names. Don't know if even that makes sense.

**Comment by mdoering** [comment]
reversing the rank order for 'taxonomic' but leaving alphabetic internal ordering seems sensible to me
