### ISSUE TITLE
Sector sync creates a duplicate root taxon as child of the root

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#260]
![duplicate-root](https://user-images.githubusercontent.com/1666484/52341452-e3bb6d80-2a12-11e9-8fd2-4e1d55a3da27.png)

**Comment by mdoering** [comment]
Indeed. Its created by the UI and the sync. Can we discuss sectors again please? The target of a sector must point outside. I feel we might be better off not creating taxa in the UI automatically. Irgent issue for monday next week!

**Comment by thomasstjerne** [comment]
Closing after implementing new UI logic
