### ISSUE TITLE
sector subjects has lost their id´s

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#267]
Sector subject must have an id:
dev.col.plus/dataset/1204/sectors

These are needed to show the classification of a sector

**Comment by mdoering** [comment]
yes, but when exporting sectors from current CoL we dont have these. We only have name, rank etc that then needs to be matched AFTER the first import went through.

Also the ids might not match, so you need to rematch them.
We could of course create fake ids for the exported sectors that dont match - is that better than keeping them null initially?

We need a place to list all broken sectors and decisions and rematch them, assisted by the system.
See https://github.com/Sp2000/colplus-frontend/issues/74

**Comment by thomasstjerne** [comment]
OK. Should the UI consider a sector with no subject.id broken? Could just show the name then, but not the classification as this is based on the id

**Comment by mdoering** [comment]
Yes please
