### ISSUE TITLE
update sector & decision ids after dataset import

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#268]
WHen a dataset is (re)imported we need to rematch all sectors and decisions as ids might not be correct anymore

**Comment by mdoering** [comment]
this also solves the missing ids in the init script

**Comment by mdoering** [comment]
@yroskov @thomasstjerne @gdower we need to discuss the exact procedure.
For sectors I think it is rather safe to rematch them all based on the rank/name/authorship.

For decisions though I am in doubt how to best do this.
Decisions are used to remove duplicates, therefore the rank/name/authorship is often not enough to clearly identify which record is meant. It might happen that sources have cleaned up data and there are no more duplicates and we now block a good record. It is also random which of the duplicate records gets removed if we have no id. So preferrably we always match by ID, but very often these will change.

How about:
- we keep a settings flag on a dataset that tells us if ids are stable
- default is yes, but the importer will manage this by checking 100 random records and verify the ids have kept the same
- for datasets with stable ids no sectors and decisions are updated
- for unstable datasets we will try to match by name/rank/authorship and optionally also by status & parentName
  - if the match is unique we'll use it, if not its broken and will be reported
  - a duplicate decision can match to any of the duplicates randomly
  - we keep a _resolvesDuplicate_ flag on a decision to know this decision only applies to duplicates. If a source does not have a duplicate anymore the decision becomes broken (or should we even delete it automatically?). Is this needed if we also have status and parent stored?

**Comment by mdoering** [comment]
See also #283 which blocks decisions on synonyms

**Comment by yroskov** [comment]
Markus, protocols listed under "How about" look very much reasonable for me.

**Comment by mdoering** [comment]
matching is taken care of by https://github.com/Sp2000/colplus-backend/issues/568
