### ISSUE TITLE
Sector sync to exclude manuscript names

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#269]
and chresonyms as CoL does never want to see those

**Comment by mdoering** [comment]
see #350

**Comment by yroskov** [comment]
_Expected behavior:_ identified names with  "ined." and "comb. ined." portions in authorstrings should be included in the Issues report for further consideration by GSD authors and editors. These names should not be excluded automatically from sync.

_Rationale:_ There are about 500 provisionally proposed names in WCSP, WPlants & WFerns. GSD authors intended to present consistent classification based on modern data. We should not delete all these species without asking authors first.

**Comment by mdoering** [comment]
I have removed manuscript names from the automatic filtering.
@yroskov all of the other cases (see top) remain to be ignored automatically.

Please be aware that manuscript names are not just identified by `ined.` alone.
I have created a frontend issue to show the numbers in the tasks board.

Until then you can always find the manuscript names by [searching for type=MANUSCRIPT](https://data.catalogue.life/catalogue/3/dataset/1140/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&nomstatus=manuscript&offset=0&sortBy=taxonomic)

We have another issue here that you cannot see the manuscript names in the search, see https://github.com/Sp2000/colplus-frontend/issues/463.

**Comment by yroskov** [comment]
Thanks @mdoering for removed manuscript names from the automatic filtering. It will improve presentation of WPlants, WFerns & WCSP data in CoL significantly.   

Generally, verbatim view of authorstrings (i.e. original view as presented by GSDs) will help (a) to expose data correctly and (b) to do better match tests between "master" of AG- and CoL+ output.
