### ISSUE TITLE
Return kingdom of Name as part of name search

### ISSUE THREAD

**Issue by ayco-at-naturalis** [Sp2000/colplus-backend#27]
The kingdom to which a species belongs is shown in the current CoL's name search result. This needs to be replicated.

Employ Postgres's recursive query capabilities to figure out and return the kingdom

**Comment by mdoering** [comment]
if we need the real kingdom we should probably denormalize it and keep it with each taxon, populated by the Normalizer on import

**Comment by mdoering** [comment]
this is probably obsolete with #220
