### ISSUE TITLE
extend import states

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#271]
ES indexing and stats building are proposed new ImportState values. 

to simplify querying for running states the API could expose a running=true/false query param

**Comment by mdoering** [comment]
@thomasstjerne does that break the UI much?

**Comment by thomasstjerne** [comment]
No, the UI will be fine with this

**Comment by mdoering** [comment]
@thomasstjerne seems to me the UI does query for specific states and therefore is affected:
https://api-dev.col.plus/importer?limit=25&offset=0&state=processing&state=downloading&state=inserting

You could change that to use the new running parameter instead:
https://api-dev.col.plus/importer?running=true
https://api-dev.col.plus/importer?running=false
