### ISSUE TITLE
Sector delete should trigger data deletion

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#279]

**Comment by mdoering** [comment]
@yroskov if a whole sector gets deleted what should happen to editorial decisions in that sector?
I would think we should delete them, but maybe there is the desire to keep them for the future? That would potentially clutter editorial tools though and I would prefer to remove them

**Comment by mdoering** [comment]
@yroskov and what about nested sectors? Remove them or reattach them somewhere?

**Comment by yroskov** [comment]
Remove them

**Comment by mdoering** [comment]
Ok, when a sector is deleted we now remove the data in the (draft) CoL, delete the sector mapping and recursively apply the same to nested sectors. Decisions which are on the source datasets as you say are left as they are, even if they are not part of a sector any longer. But can therefore easily be revived if maybe parts of the former sector are now mapped elsewhere.

**Comment by yroskov** [comment]
OK
