### ISSUE TITLE
Possible to keep the root ID when a sectors syncs?

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#280]
I have the following UI workflow

1) User clicks sync on a sector root
2) The UI tries to reload all children of the root after the sync is triggered

But now the root has a new id, so the load children gives an empty response. The UI has to go one step up (parent of the root) and reload to get the new root (new id) and there after load children.

Wondering if it would be possible to keep the ID for the root when a sync starts?

**Comment by thomasstjerne** [comment]
If you are OK with https://github.com/Sp2000/colplus-frontend/issues/145
this can be ignored (for now at least)

**Comment by mdoering** [comment]
thats possible, at least for cases without a duplicate name. 

but I wonder about a few things for dealing with syncs in the UI:
 - the sync may be queued for a long time until the sector is erased
 - the sector has a source, maybe its best to show it on the right stable tree so it remains
 - the source of a sector needs to be visualised anyways, at least highlighted. maybe even eith a line connecting source and target node of the sector?
