### ISSUE TITLE
No search results returned for some issues

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#281]
Some of the issues are still generating empty search results in the frontend:

[Accepted ID Invalid](https://www.col.plus/dataset/2047/names?facet=rank&facet=issue&facet=status&issue=accepted%20id%20invalid)
[Accepted Name Missing](https://www.col.plus/dataset/2047/names?facet=rank&facet=issue&facet=status&issue=accepted%20name%20missing)

The corresponding JSON responses are empty ([Accepted ID Invalid](https://api.col.plus/dataset/2047/name/search?facet=rank&facet=issue&facet=status&issue=accepted%20id%20invalid), [Accepted Name Missing](https://api.col.plus/dataset/2047/name/search?facet=rank&facet=issue&facet=status&issue=accepted%20name%20missing)), but perhaps the ReactApp is supposed to run another search for those issues?

**Comment by mdoering** [comment]
These 53 records are verbatim synonyms that were not created as Synonyms because the accepted is missing. I would have expected these to become bare names which should then also show up in the search, but that also did not happen for some reason.

**Comment by mdoering** [comment]
There is a direct way of searching for verbatim issues that is useful in such cases:
http://api.col.plus/dataset/2047/verbatim?issue=ACCEPTED_NAME_MISSING

@thomasstjerne I wonder if we should add an issues filter to the verbatim data viewer, that could be really useful for data managers

**Comment by mdoering** [comment]
It is kinda right actually. The source format is ColDP so names have their own id and verbatim record. The ones in question have been added properly but do not have an issue.

The synonym record is very limited, its just a nameID, taxonID and a status:
```
    {
      "key": 9338011,
      "datasetKey": 2047,
      "line": 279,
      "file": "Synonym.tsv",
      "type": "col:Synonym",
      "terms": {
        "col:nameID": "426",
        "col:status": "synonym",
        "col:taxonID": "74"
      },
      "issues": [
        "accepted id invalid",
        "accepted name missing"
      ]
    }
```

When the taxonID is not existing we cannot create a synonym record and the verbatim record of the _synonym_, not the name, gets flagged with Issue.ACCEPTED_NAME_MISSING.

The name usage search index does not know about that issue as the name record does not have it.
Solutions to consider:
 - Always provide an additional link to verbatim data viewer from the issues list
 - include all synonyms & taxon issues that lead to dropping the entire interpreted record with the verbatim record of the name. That feels semantically wrong, but allows to expose bare names with issues from synonyms and taxa that did not make it.

**Comment by mdoering** [comment]
Example of a bare name from the search that was linked to a bad synonym: http://api.col.plus/dataset/2047/name/search?nameID=426

**Comment by mdoering** [comment]
Suggest to rely on the verbatim data viewer in such cases as the pooling issues on the name record feels wrong to me. If you think otherwise feel free to reopen this ticket
