### ISSUE TITLE
Apply editorial decisions during sector sync

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#290]
- [x] block taxon and all its descendants
- [x] block chresonym, but include descendants
- [x] update name, (partially) update the name of the record
- [x] update lifezone for just this taxon, also see #289
- [x] apply fossil/recent for just this taxon, also see #289
- [x] update taxonomic status of the record

**Comment by mdoering** [comment]
@yroskov can an editorial decision convert a synonym to an accepted name and vice versa?
Or is the status change always just between accepted/provisionally_accepted and synonym/doubtful_synonym/misapplied ?

**Comment by yroskov** [comment]
General practice: accepted <-> provisionally accepted; synonym <-> ambigous synonym or misapplied name. In vary rare case, GSD custodian may request to make a shortcut change in CoL: accepted <-> synonym.

**Comment by mdoering** [comment]
All of the main name fields mentioned here are applied:
https://github.com/Sp2000/colplus-frontend/issues/206

No others at this stage
