### ISSUE TITLE
name usage search by nameIndexID not working

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#298]
you can see names here:
http://api-dev.col.plus/name/search?datasetKey=2045

but not filter by their nameIndexID:
http://api-dev.col.plus/name/search?datasetKey=2045&nameIndexID=9kpmj7

**Comment by ayco-at-naturalis** [comment]
I think it works in the API:
http://api-dev.col.plus/name/search?nameIndexID=_NULL ---> all
http://api-dev.col.plus/name/search?nameIndexID=_NOT_NULL ---> none

Did also make a few unit tests specifically for nameIndexId & they succeed

So it must have fallen by the wayside somewhere during the import ... will have a look

**Comment by mdoering** [comment]
ok, so that means the nameIndexID values never made it to the index

**Comment by ayco-at-naturalis** [comment]
It's probably not even the mapper, but somewhere in the PG import. Importing itis_global resulted in all namePublishedIn == null (in the database)

**Comment by ayco-at-naturalis** [comment]
Just did two dwca imports (itis_global and worms_mollusca) and in both case name_index_id is always null ... i.e. in the table ... so it's not even in the mapper but even more upstream.

**Comment by mdoering** [comment]
It requires a real implementation of the name matching service and either a dataset with contributesTo!= null (which either is set by having a mapped sector or flagged with namesIndexContributor=true). The tests all use a PassThru dummy matching service that always returns null, so that might be expected. 

How about a test inserting a single taxon with a name that has a non null nameIndexId and making sure it gets to the index?

**Comment by ayco-at-naturalis** [comment]
That's done: https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/test/java/org/col/es/NameSearchTestAllParamsTest.java

**Comment by ayco-at-naturalis** [comment]
Actually a full round-trip (NameUsageWrapper -> EsNameUsage -> insert -> query -> EsNameUsage -> NameUsageWrapper)

**Comment by mdoering** [comment]
looks like it is working fine:
http://api-dev.col.plus/name/search?datasetKey=1010
http://api-dev.col.plus/name/search?nameIndexID=6r_vqz
