### ISSUE TITLE
Implement Nomenclatural Acts MyBatis layer

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#3]
https://sp2000.github.io/colplus/api/staging.html#model-NomenclaturalAct

**Comment by mdoering** [comment]
@ayco-at-naturalis is this done?

**Comment by ayco-at-naturalis** [comment]
@mdoering I am almost done but struggling a bit with the SQL somehow.

**Comment by ayco-at-naturalis** [comment]
30bf7a00c4df12aba891723e18f93124d180951c

**Comment by ayco-at-naturalis** [comment]
30bf7a00c4df12aba891723e18f93124d180951c
