### ISSUE TITLE
persist verbatim record to postgres

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#30]
PgImport contains dummy method for this to be filled with life:
https://github.com/Sp2000/colplus-backend/blob/master/colplus-task/src/main/java/org/col/task/importer/PgImport.java#L241

**Comment by ayco-at-naturalis** [comment]
This already happens in PgImport.insertTaxaAndNames

**Comment by mdoering** [comment]
great! then just remove the redundant, empty method
