### ISSUE TITLE
Align tree API responses

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#302]
Assembly tree has [sectorKeys](https://api-dev.col.plus/dataset/3/tree/41641824/children?limit=100&offset=0), whereas source trees has the entire [sector object](https://api-dev.col.plus/dataset/1006/tree/xwYWd/children?limit=100&offset=0).
As https://github.com/Sp2000/colplus-frontend/issues/152 is closed, I think sectorKeys is sufficient.

This was the reason sectors didn´t show correct on source trees. 

It will be easier to document and use the API later on if responses are aligned.

(I have adapted the frontend, so it is not blocking in any way )

**Comment by mdoering** [comment]
so replace sector object with just the sectorKey, correct?

**Comment by thomasstjerne** [comment]
Yes
