### ISSUE TITLE
import endpoint count attributtes uppercased and underscored

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#304]
https://api-dev.col.plus/dataset/1015/import?limit=3&state=finished
They used to be lower case with spaces like in the vocab https://api-dev.col.plus/vocab/issue

This affects both import metric pages and issues

**Comment by mdoering** [comment]
Must have been existing for while. Fixed in https://github.com/Sp2000/colplus-backend/commit/9e04c759784b871165e6f716632a50dbdab0b8a5
