### ISSUE TITLE
CSL date-parts in nested array

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#310]
The date-parts in the response is an array of date parts sitting within another array.
This makes the frontend lib duplicate years in references

**Comment by mdoering** [comment]
what is the correct structure? Is it the literal value that is confusing or the nested dates?
The nested array is the CSL way of doing this I believe. Checkout CrossRef:
https://api.crossref.org/works?query.bibliographic=Telopea%2012(1):%20130-132

**Comment by mdoering** [comment]
See https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#date-fields

**Comment by mdoering** [comment]
seems to be a debated CSL issue, but 
> I'm assuming that "literal" names, as well as "literal" and "raw" dates, are all mutually exclusive with the other fields 
https://github.com/citation-style-language/schema/issues/160
https://github.com/citation-style-language/schema/pull/155

**Comment by mdoering** [comment]
Apparently also a year only in the date array is allowed - sth we very often have
