### ISSUE TITLE
Manage CoL info pages in Github

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#336]
[Info pages](http://www.catalogueoflife.org/col/info/about) of the monthly release of the CoL needs to be managed somewhere, ideally in github.

See also https://github.com/Sp2000/colplus-backend/issues/242

**Comment by ruud-altenburg** [comment]
I deliberately removed these from the repo, as these were maintained in the workbench. The idea was that Yuri was able to implement changes in these. If he can work with a git repo, then moving them to a separate repo (and symlinking that) sound like a good idea.

**Comment by mdoering** [comment]
This is only temporary, but with the assistence of @gdower this will be the best and simplest solution. Can the two of you please set this up and let me know if we need to add anything to the export?

**Comment by ruud-altenburg** [comment]
I will set up a new repo for the info files.

**Comment by ruud-altenburg** [comment]
https://github.com/Sp2000/col-info-pages-settings

This repo  currently covers our sections that need to be modified "from the outside": translation files, images, info pages and config (credits). I have copied the data from the workbench testcol, assuming these are the latest versions.

**Comment by ruud-altenburg** [comment]
our = four. I realize that the repo name doesn't really covers its contents anymore, but hopefully it's clear enough. Feel free to add more files if needed.

My proposal is to create a couple of webservice calls that will update these respective settings in production.

**Comment by mdoering** [comment]
@ruud-altenburg are 2 copies (gif&png) for a database image needed?
We had planned to provide the images from CoL+, but did not do this so far. 

If we want to are both copies needed and how is the GSD related to the image file? I would have assumed the database_id in the filename

**Comment by ruud-altenburg** [comment]
I haven't bothered to check which images are used and which aren't. We can easily switch to a different file naming protocol if this is more convenient.

**Comment by ruud-altenburg** [comment]
I have added a script to the conversion tool that can pull an updated version of this repo to the CoL server. This way anybody with access to the secret key can update these sections in the CoL remotely.

**Comment by mdoering** [comment]
I agreed wirh Geoff yesterday that we just use the logo images from the new repo directly. No need to export them from the clearinghouse, convert to both formats and changes names. When we add a new gsd logo images will simoly be added here as well

**Comment by mdoering** [comment]
closing this in favor of https://github.com/Sp2000/AC_Interface/issues/3 and https://github.com/Sp2000/colplus-backend/issues/549
