### ISSUE TITLE
Test SQL performance and create missing Postgres indices

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#34]
There are hardly any postgres indices currently.
Good for write performance, but we need to make sure reads are real quick.

Document any missing index and the SQL to be improved in this issue before adding

**Comment by ayco-at-naturalis** [comment]
**NameMapper**

count, list:
index on column **dataset_key**

lookupKey
unique index on columns **id, dataset_key**

search:
index on column **rank**
index on column **nomstatus**
index on column **type**
index on column **issue**
index on column **scientific_name** (sorting)

basionymGroup:
index on column **basionym_key**

==============================================================================

**TaxonMapper**

count, list:
index on column **dataset_key**
index on column **parent_key**
index on column **name_key**

lookupKey:
unique index on columns **id, dataset_key**

getAcceptedNames:
unique key on **synonym.taxon_key, synonym.name_key**

==============================================================================

**DatasetMapper**

count, list:
index on column **deleted**

listNeverImported:
(???) index on column **dataset_import.dataset_key, dataset_import.finished**

getByGBIF:
index on column **gbif_key**


==============================================================================

**NameActMapper**

count, list:
index on column **deleted**

listNeverImported:
(???) index on column **dataset_import.dataset_key, dataset_import.finished**

getByGBIF:
index on column **gbif_key**

**Comment by mdoering** [comment]
Quite a lot, but looks like we need them.
It would be good to test at least some that they actually get used by running EXPLAIN queries in postgres, but that requires quite some data. I wonder if we need the reference_key column indices for the various ReferenceMapper list methods. The where clause is on the taxonKey always which is very specific already and should never return very large resultsets. I would expect that single index to be sufficient.

Another thing to consider is the kind of index. Default b-tree indices are usually best, but Im not sure what kind of index is best suited for our array columns we use for issues and a few more.

**Comment by ayco-at-naturalis** [comment]
01a06e1eaf181a9477bac3fad784fc0aa096f657
