### ISSUE TITLE
PUT on decisions gives 400 bad request (missing modified_by)

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#348]
https://api-dev.col.plus/decision/9

↵### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: null value in column "modified_by" violates not-null constraint↵  Detail: Failing row contains (9, 1204, 10574, Acrotona pseudopygmaea, (Scheerpeltz, 1963), species, 2, 3, null, null, null, {}, null, 2019-05-03 09:16:58.291272, 102, 2019-05-06 10:28:23.180593, null).↵### The error may involve org.col.db.mapper.DecisionMapper.update-Inline↵### The error occurred while setting parameters↵### SQL: UPDATE decision     SET (      dataset_key,     subject_id,     subject_name,     subject_authorship,     subject_rank,     note,     modified,     modified_by,     mode,     name,     status,     fossil,     recent,     lifezones    ) = (      ?,     ?,     ?,     ?,     ?::rank,     ?,     now(),     ?,     ?,     ?::jsonb,     ?,     ?,     ?,     ?    )     WHERE key = ?↵### Cause: org.postgresql.util.PSQLException: ERROR: null value in column "modified_by" violates not-null constraint↵  Detail: Failing row contains (9, 1204, 10574, Acrotona pseudopygmaea, (Scheerpeltz, 1963), species, 2, 3, null, null, null, {}, null, 2019-05-03 09:16:58.291272, 102, 2019-05-06 10:28:23.180593, null).

**Comment by mdoering** [comment]
should be fixed in https://github.com/Sp2000/colplus-backend/commit/028dc8dc373343f3bc632509a12c98fddf9393f0 and deployed to dev
