### ISSUE TITLE
Refactor Decision and Sector, extending SimpleName

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#349]
status and parentId are needed to track down a concrete usage for an editorial decision. Extend SimpleName with those and refactor EditorialDecision and Sector to use it

**Comment by mdoering** [comment]
is parentID stable enough or should it rather be parentName?

**Comment by mdoering** [comment]
I am planning to allow authorship, status & parent (the name) to be optional and NULL values to match any. e.g. if the decision has authorship=NULL it will match a name regardless which authorship it has. But it needs to match a single name usage.

That means when POSTing to the API the object should be fully populated. I could fetch it just by its ID, but then I dont know if authorship, status & parent are also meant to be included. Well, I could just fetch all in case only the id is given and leave the object as it was POSTed if at least a rank & name was given.

**Comment by thomasstjerne** [comment]
So the UI should post parent and authorship also? That is probably not a big change.
But I reckon that authorship=NULL will mean no authorship param given right?

**Comment by mdoering** [comment]
yes exactly. But I don't know if we always really want to also give authorship and a parent name.
For resolving duplicates this is important (the status or parent could make the only difference) so I guess there definitely. For sectors authorship and parent is probably irrelevant and could even lead to unmatched/broken sectors if the source decides to change the classification.

**Comment by gdower** [comment]
Some GSDs don't provide stable identifiers, so I think it should be the parent name or a uuid generated from scientific names including the author string (because the editorial decision usually depends on the author string).

**Comment by mdoering** [comment]
The implemented change now adds `status`, `code` and `parent` which should be the parent scientificName without authorship
