### ISSUE TITLE
Genera with no species epithet should be handled as uninomials 

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#352]
The Scarabs dataset has a lot of genera provided as uninomials with no species epithet. We also have some really useful GSDs like IRMNG that provide a classification down to genus in gaps where we would otherwise have no data.

The names parser is adding "[spec.](https://www.col.plus/dataset/1027/names?facet=rank&facet=issue&facet=status&issue=indetermined&limit=100)" to these genus uninomials, which is undesirable because spec. wasn't included in the original dataset and in some cases there may not be an unnamed specimen but we might just be missing the species epithets.

**Comment by mdoering** [comment]
Do you have an example for this? This should only happen when the rank was actually given as `species`. For genus only names it would be a genus otherwise.

As we discussed in our last call this used to happen in all ACEF interpretation as it was designed to always be a species record. I have since then changed this to also allow for genus only records in the AcceptedSpecies file. It might not have been deployed fully on prod yet

**Comment by gdower** [comment]
That may indeed be the case, or maybe I just need to re-import the Scarabs dataset. Here's the [example](https://www.col.plus/dataset/1027/names?facet=rank&facet=issue&facet=status&issue=indetermined&limit=100).

**Comment by mdoering** [comment]
After redeploy and forced reindexing things look much better:
https://www.col.plus/dataset/1027/names?facet=rank&facet=issue&facet=status&issue=indetermined&limit=50&offset=0

Still a few, but no spec. names.
Any idea what these are about? Subgenus records?

**Comment by gdower** [comment]
@mdoering, I've looked carefully at the [raw data](https://raw.githubusercontent.com/Sp2000/data-scarabs/master/acef/AcceptedSpecies.tsv) and the [_Diploa proles_](https://www.col.plus/dataset/1027/taxon/19-.02-.03-.00-.008-.000-.003-.-) record seems correct. Does CoL+ interpret the additional data column? It is listed as being used for the genus type.

Some of these are synonyms with the infraspecies_marker var. and infraspecies var., which we hadn't previously been testing, and we probably should block from being included in CoL+.

**Comment by mdoering** [comment]
As proles is used in legacy names as a rank I suppose the name parser interprets `proles` as the rank and misses an epithet, hence the issue. But as ACEF supplies it as the species epithet we still use it as such so finally I think all is good - just some issues flagged that we can safely ignore in this case
