### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#367]

**Comment by mdoering** [comment]
ouch, I need to wipe dev to fix this

**Comment by mdoering** [comment]
@thomasstjerne can you try again please?

**Comment by thomasstjerne** [comment]
The first import worked now, but after changing origin to uploaded and retrying I get:


### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "name_2_pkey" Detail: Key (id)=(NIlwWl) already exists. ### The error may involve org.col.db.mapper.NameMapper.create-Inline ### The error occurred while setting parameters ### SQL: INSERT INTO name_2 ( id, dataset_key, sector_key, verbatim_key, name_index_id, homotypic_name_id, scientific_name, scientific_name_normalized, authorship, authorship_normalized, rank, uninomial, genus, infrageneric_epithet, specific_epithet, infraspecific_epithet, cultivar_epithet, appended_phrase, candidatus, notho, basionym_authors, basionym_ex_authors, basionym_year, combination_authors, combination_ex_authors, combination_year, sanctioning_author, published_in_id, published_in_page, code, nom_status, origin, type, webpage, fossil, remarks, created_by, modified_by , created, modified) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::rank, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? , now(), now()) ### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "name_2_pkey" Detail: Key (id)=(NIlwWl) already exists.

**Comment by mdoering** [comment]
ah, still related to NamesIndex.
@thomasstjerne to continue your work please turn off namesIndexContributor in dataset metadata before scheduling an import until I fix this for good.

**Comment by thomasstjerne** [comment]
But it is actually turned of. Maybe it is not recognised by the backend?
