### ISSUE TITLE
Not possible to upload a new archive for dataset after a sector sync

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#372]
The dataset has been used in a sector sync, but even after the sync is finished, the response is:
````
Request failed with status code 400
Dataset used in running sync of sector 20208

HTTP method: POST

https://api-dev.col.plus/importer/2048
````

**Comment by mdoering** [comment]
It is expected that you cannot sync a dataset which is being imported and vice versa.
After the sync is finished this should be possible though

**Comment by thomasstjerne** [comment]
Sure. The problem is that the sync is not running, it is finished.

**Comment by mdoering** [comment]
indeed a bug, found it
