### ISSUE TITLE
Add sector nom code configuration

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#376]
Allow a sector to contain manual configurations to override the nomenclatural code for all names from the sector copied into the CoL. This takes preference over the dataset configuration which can be vague in case of multiregnal datasets like ITIS

**Comment by thomasstjerne** [comment]
Does the sector need a full PUT to update the code?

**Comment by mdoering** [comment]
yes

**Comment by thomasstjerne** [comment]
Should it be the name or acronym of the code?

**Comment by mdoering** [comment]
the name please!
