### ISSUE TITLE
Name search sortBy TAXONOMIC gives unexpected results

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#378]
I would expect to see the the order "Crocodylia" in the top of these results:

https://api-dev.col.plus/dataset/1008/name/search?&reverse=true&sortBy=taxonomic&status=accepted&limit=25&offset=0&q=Croco

https://api-dev.col.plus/dataset/1008/name/search?&reverse=true&sortBy=TAXONOMIC&status=accepted&limit=25&offset=0&q=Croco

**Comment by mdoering** [comment]
why reverse=true?

**Comment by thomasstjerne** [comment]
Ahh. My bad. Closing

**Comment by mdoering** [comment]
reverse should be low ranks first
