### ISSUE TITLE
taxonomic_coverage not populated in `databases` table 

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#379]
The taxonomic_coverage column is not populated in the `databases` table of the CoL+ to Assembly_Global exporter, which causes the CoL web interface to not show GSDs' coverage in the classification section of species pages:

![CoL+ vs CoL comparison](https://i.gyazo.com/05a0584baccc879394c202943910a215.png)

**Comment by gdower** [comment]
Also, @mdoering, the delimiter for the taxonomic_coverage column has to be ' - ' not '-', otherwise it won't work.

**Comment by mdoering** [comment]
what about the source database rating, is it missing?

**Comment by gdower** [comment]
Yes, I think both the confidence and completeness columns weren't populated.

**Comment by mdoering** [comment]
Format of taxonomic_coverage:

List of "terminal" sector names delimited by a comma and prefixed with a shared classification delimited by a hyphen. E.g.:
```
Fungi - Ascomycota - Eurotiomycetes - Pyrenulales, Verrucariales, Mycocaliciales;
Fungi - Ascomycota - Dothideomycetes - Arthopyrenia, Eopyrenula, Lichenothelia, Mycoporum, Leptorhaphis, Naetrocymbe, Tomasellia, Peridiothelia, Pseudopyrenula, Cyrtidula, Cystocoleus, Kirschsteiniothelia, Mycoglaena, Racodium;
Fungi - Ascomycota - Leotiomycetes - Thelocarpaceae, Vezdaeaceae;
Fungi - Ascomycota - Eurotiomycetes - Sarcopyrenia;
```

http://www.catalogueoflife.org/col/details/database/id/79
