### ISSUE TITLE
How to post references to the API

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#397]
The regular reference object the API accepts is heavily based on [CSL-JSON](
https://github.com/citation-style-language/schema#csl-json-schema) which is a rather complex and extensible format. [CSL-JSON schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json)

The available/sensible fields depend on the reference (item) type:
https://aurimasv.github.io/z2csl/typeMap.xml

It might make sense to allow posting of simpler formats such as the [7 ColDP reference fields](https://github.com/Sp2000/coldp#reference). Offering different media types might be the way to go with plain JSON being the main CSL format, but `application/vnd.coldp+json` expecting a simple ColDP reference object in JSON:
```
{
"citation": "Full bibliographic citation as one single string as an alternative to the rest of the more structured fields. If individual fields are given the full citation can be ignored.",
"author": "S.M. Smith",
"title": "The title of the work. In case of journal articles the article title, not the journal itself."
"year": "The year of the publication.",
"source": "The title of the journal or book the work was published in. The source should exclude volume, edition, pages and other specifics."
"details": "volume, edition, pages and other specifics.",
"doi": "10.1126/science.169.3946.635"
"link": "https://syndication.highwire.org/content/doi/10.1126/science.169.3946.635"
}
```

**Comment by mdoering** [comment]
... and [BiBTex](https://format.gbv.de/bibtex) `application/x-bibtex```
Maybe thats worth supporting too as we do that already in the ColDP importer and its a common format with standing

**Comment by mdoering** [comment]
@thomasstjerne is it simple to post different content types from the UI?

**Comment by thomasstjerne** [comment]
Yes, it should not be a problem. 

I definitely think we should support some simple way of giving a reference, like the COLDP. 
Also, if you know the DOI it would be smart if you could just give that and let the system handle the rest.

**Comment by mdoering** [comment]
How about a parsing service that takes a single string and returns a proper ref object but not yet inserted so it can be reviewed and POSTed to be created. If its a DOI it tries to look up the metadata, if its a citation it tries to parse it. 

Would mean the UI still has to render CSL for review and fixes...

**Comment by thomasstjerne** [comment]
Sounds very good

**Comment by mdoering** [comment]
ok, posting coldp like this seems to work fine locally, gonna commit that:

```
curl -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJjNzFiZjU0ZS1hNDNiLTQxYjAtOGZkNC1jYWY5MTA1YjRjYmQiLCJpc3MiOiJjb2wucGx1cyIsImlhdCI6MTU2MDUwMjY3NSwic3ViIjoibWFya3VzIiwiZXhwIjoxNTYxMTA3NDc1fQ.7pA4lO6JR8MQF7tRWfOdm6oDTGVUh8fFUpdMn_04uaA'  -H 'Content-Type: application/vnd.coldp+json' -X POST -d '{}' http://localhost:8080/dataset/3/reference
```

**Comment by thomasstjerne** [comment]
I am trying to create references in CSL, but contentType "application/vnd.citationstyles.csl+json" gives 415. When posting this as plain JSON a reference is created, but it is empty: https://api-dev.col.plus/dataset/3/reference/713bc472-7111-4510-8c50-4799d38cdb78

```
{
"type":"incollection",
"title":"Cortinarius",
"author":[{"family":"Niskanen","given":"Tuula"},{"family":"Jeppesen","given":"Thomas S."}],
"container-title":"Funga Nordica",
"editor":[{"family":"Knudsen","given":"Henning"},{"family":"Vesterholt","given":"Jan"}],
"edition":"3",
"volume":"1",
"publisher":"Nordsvamp",
"publisher-place":"Copenhagen",
"URL":"",
"ISBN":"978-87-983961-3-0",
"issued":"","accessed":"",
"pages":"643-743"
}

```

**Comment by mdoering** [comment]
The CSL media type is not (yet) registered. The regular JSON reference contains the CSL inside the csl property: http://api.col.plus/dataset/3/reference

If you want to post a pure CSL item we can easily add that media type.
