### ISSUE TITLE
Generate ID for CSL reference

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#399]
When a new reference is posted through the UI, the backend should assign an ID for it.

Request failed with status code 400

### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: null value in column "id" violates not-null constraint Detail: Failing row contains (null, 3, null, null, null, null, null, , 2019-06-20 10:18:36.556514, 101, 2019-06-20 10:18:36.556514, 101). ### The error may involve org.col.db.mapper.ReferenceMapper.create-Inline ### The error occurred while setting parameters ### SQL: INSERT INTO reference_3 ( id, dataset_key, sector_key, verbatim_key, csl, citation, year, created_by, modified_by , created, modified) VALUES ( ?, ?, ?, ?, ?::jsonb, ?, ?, ?, ? , now(), now()) ### Cause: org.postgresql.util.PSQLException: ERROR: null value in column "id" violates not-null constraint Detail: Failing row contains (null, 3, null, null, null, null, null, , 2019-06-20 10:18:36.556514, 101, 2019-06-20 10:18:36.556514, 101).

HTTP method: POST

https://api-dev.col.plus/dataset/3/reference

Body:
{"type":"incollection","title":"Cortinarius","author":[{"family":"Niskanen","given":"Tuula"},{"family":"Jeppesen","given":"Thomas S."},{"family":"Brandrud","given":"Tor Erik"},{"family":"Frøslev","given":"Tobias"}],"container-title":"Funga Nordica","editor":[{"family":"Knudsen","given":"Henning"},{"family":"Vesterholt","given":"Jan"}],"edition":"3","volume":"2","publisher":"Nordsvamp","publisher-place":"Copenhagen","URL":"","ISBN":"978-87-983961-3-0","issued":{"date-parts":["2016","05","01"]},"accessed":"","pages":"697-789"}

**Comment by mdoering** [comment]
yes indeed
