### ISSUE TITLE
Synonym references are getting moved to accepted name references

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#406]
All synonym references are getting moved to the accepted name references:

![Taxon page with missing synonym references](https://i.gyazo.com/82c5dca89f1e6744ea6186e84c94844e.png)

![Accepted name references](https://i.gyazo.com/868c4659996928b81ce72d01cc2e6782.png)

It looks like this might be intentionally done:

![Synonym data moved](https://i.gyazo.com/f705a2e4cf5c3d55a71f8cce9d232d88.png)

Moving bibliographic references from synonyms to the accepted name is not desirable because if people are looking for reference information for a specific name they will then have to look through potentially a lot of extra references to find the information they need. Some accepted names have large numbers of synonyms with lots of synonym references. Both nomenclatural and taxonomic references attached to synonyms should remain associated with the synonym.

**Comment by mdoering** [comment]
Yes that *was* intentional. The nomenclatural reference stays with the name of course, but a taxonomic reference really should describe the taxon concept, thus the synonymy. A reference for each synonym is a little awkward. But I see the point to link to specific references for some synonyms and luckily we changed the data model a while ago to support this. But it hasnt been implemented in the importer yet  - which I am working on right now.

**Comment by mdoering** [comment]
Propose to extend the Synonym class to hold a list of reference ids.
A list of Synonyms is then added to the TaxonInfo class so its exposed at taxon/{ID}/info together with a map of ref ids to actual reference objects.

**Comment by mdoering** [comment]
@thomasstjerne please adjust the frontend to:
 - consider to use the synonym list now bundled with taxon/{id}/info
 - show synonym. and taxon.referenceIds instead of Info.taxonReferences

**Comment by thomasstjerne** [comment]
Does the new api distinguish between homotypic, heterotypic and misapplied names, or they just all the same?

**Comment by mdoering** [comment]
Its the same as before, BUT the info response only contains a simple list which you'd need to sort manually. Each name in there has the usual homotypicNameID with homotypic names sharing the same id. See here: https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/main/java/org/col/dao/TaxonDao.java#L64

You can still get the old style synonyms from the /synonymy method
