### ISSUE TITLE
decisionKey=_NOT_NULL gives zero results even though decisions exists

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#407]

**Comment by mdoering** [comment]
@thomasstjerne example at hand?

**Comment by thomasstjerne** [comment]
https://api-dev.col.plus/dataset/1008/name/search?decisionKey=_NOT_NULL&facet=rank&facet=issue&facet=status

https://api-dev.col.plus/decision?id=S-5013

https://api-dev.col.plus/dataset/1008/name/search?facet=rank&facet=issue&facet=status&issue=unusual%20name%20characters&limit=50&offset=0

**Comment by ayco-at-naturalis** [comment]
It seems like the decision key in the index is simply always absent, so it must be in the indexing. Vaguely seem to remember that we've been here before. See:
https://api-dev.col.plus/dataset/1008/name/search?decisionKey=_NULL&limit=0
https://api-dev.col.plus/dataset/1008/name/search?limit=0

**Comment by mdoering** [comment]
I have wiped dev (see gitter), so right now it should be empty

**Comment by mdoering** [comment]
I have added decision in the workbench, still none in the search:

https://dev.col.plus/dataset/1008/workbench?facet=rank&facet=issue&facet=status&limit=50&offset=0

https://api-dev.col.plus/dataset/1008/name/search?decisionKey=_NOT_NULL&limit=0

**Comment by mdoering** [comment]
... and interestingly the decision is not in the search result:
https://api-dev.col.plus/dataset/1008/name/search?limit=10

@thomasstjerne how does it get into the workbench then?

**Comment by thomasstjerne** [comment]
Currently the workbench looks up if a decision exists for each name in the table. Think I maybe did this as an interim solution waiting for decisions in the name search

**Comment by mdoering** [comment]
ah, that explains it. If a decision is created the index should be updated. But I found there was a transaction problem that prevented the newly created decision to be visible to the indexer.
Shoould be fixed now!

**Comment by mdoering** [comment]
@ayco-at-naturalis can you please look into this and maybe debug locally? Its blocking @thomasstjerne work

**Comment by ayco-at-naturalis** [comment]
ok - will look into now

**Comment by ayco-at-naturalis** [comment]
There are actually quite a few unit tests going through a full (and non-mocking) index cycle and then testing IS_NOT_NULL and IS_NULL queries for decision_key. They are run as part of the build (not one of those @Ignore test classes) and, self-evidently, they succeed. So I still wonder whether the decision keys really are handed over by postgres. Alternatively, it could be at the very other side, in the REST classes (converting the URL perhaps). Will have a look there

**Comment by mdoering** [comment]
can you run the app locally and create a decision and debug where things go wrong?

**Comment by ayco-at-naturalis** [comment]
I'll try that

**Comment by ayco-at-naturalis** [comment]
@thomasstjerne & @mdoering I've made integration tests spanning both pg and es a lot easier for myself. It's now rather easy to create a test that indexes a mini dataset using the index service, then adds a decision using the decision dao, and then use the search service to make sure the decision key has ended up in the index.

That DID indeed throw up an error in the decision dao, which I fixed. But haven't had time to ascertain that that was indeed the error Thomas was having trouble with.

**Comment by ayco-at-naturalis** [comment]
I have now made the entire trip from REST API all the way down and up and again, I the decision created via the REST API make it to ES, and back via the search API. As mentioned, I have modified the GlobalEntityDao to make it commit before the post-insert/update hooks. integration tests for both create and update of decisions working

**Comment by thomasstjerne** [comment]
This has reappeared. Also it would be nice to have the decisionsKey in the response so I dont have to issue a call to /decisions for each row in the result

**Comment by mdoering** [comment]
@thomasstjerne, please reopen if it is still true. I am closing as I strongly suspect this is because of ES entered read-only mode, see https://github.com/Sp2000/colplus-backend/issues/498

**Comment by thomasstjerne** [comment]
No data: https://api-dev.col.plus/dataset/1015/name/search?decisionKey=_NOT_NULL&facet=rank&facet=issue&facet=status&limit=50&offset=0

Another observation: the row with decisions end up in the very end of the result (last page). 
This means that if the exact same search is performed after a a decision is applied, the row with that decision is no longer on the current result page.

Decisions on the very last page example: http://localhost:3000/dataset/1015/workbench?facet=rank&facet=issue&facet=status&limit=50&offset=44350&reverse=false

**Comment by thomasstjerne** [comment]
The decisionKey never gets inserted into Elastic:
I created this [decision](https://api.dev.catalogue.life/decision?id=1&datasetKey=1700) :

````
{
  "created": "2019-11-25T13:20:22.913539",
  "createdBy": 100,
  "modified": "2019-11-25T13:20:22.913539",
  "modifiedBy": 100,
  "key": 3,
  "datasetKey": 3,
  "subject": {
    "id": "1",
    "name": "Plantae",
    "rank": "kingdom",
    "code": "botanical",
    "status": "accepted"
  },
  "subjectDatasetKey": 1700,
  "mode": "update",
  "status": "provisionally accepted"
}
```` 

But this is the entity in the [index](http://api.dev.catalogue.life/es/_search?q=datasetKey:1700&size=50) for id:1
````
{
  "_index": "dev-nu",
  "_type": "_doc",
  "_id": "l0i4om4BVHweO5LfYXfO",
  "_score": 9.306202,
  "_source": {
    "usageId": "1",
    "datasetKey": 1700,
    "scientificName": "Plantae",
    "nameStrings": {
      "genusOrMonomialWN": "plantae"
    },
    "nameId": "1",
    "nameIndexId": "QLP",
    "rank": 4,
    "type": 0,
    "nomCode": 1,
    "nameFields": [
      0
    ],
    "status": 0,
    "payload": "eJydkE1OwzAQhe8yawvsNM2fqgohNghRseiu6mJInDAisSvHQZQq1+ICXIxJIFXLAiF29vO852\/eAaiADBQI6FqsNGQHuPL7HR9gzWLuNHrNI5tAqlQoJYJAJCKIRBiJOJmFci6l3B4Hr\/eQKSmgsQWV9BfjNDk5C\/TYan+nh3ssWXnR7hE9NaMUCzDYjJy\/ss2TOI3UP9hOjT\/ZzkhSAU+2sVwW5StGup2KdGieIQu5UUPGNoQ1PzzUaDzqoVI0BfGWXQtZiXWrWbIFb6QEWEcVGcj4rx26dmD0ruOJ0roGPS+xGpeHBS2\/ExeXtIReQOu\/IuVZCua5dQWZam3ZdX9x8\/Hu+MYY+tWTyf2RoaZSv1mjOWIz2\/b9J6XtoK4="
  }
}
````


The only change is that this entity is now in the end of resultset

**Comment by mdoering** [comment]
I think I finally got it, it's in the mybatis layer. The join with decisions was through the decisions catalogue key, not the subjectDatasetKey. The tests did not pick this up because we use the same datasetKey for both in them ;)
