### ISSUE TITLE
Visayan language family has no iso code

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#411]
It is a family of languages, each with their own code:
https://en.wikipedia.org/wiki/Visayan_languages

How should we treat a common name with language=Visayan ?
Make it `Cebuano`, the largest language of that family?
https://en.wikipedia.org/wiki/Cebuano_language

**Comment by mdoering** [comment]
@gdower @yroskov would you agree with the Cebuano proposal?

**Comment by yroskov** [comment]
Yes, I agree. It looks like written Cebuano use basic Latin script.
