### ISSUE TITLE
/importer gives 500

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#413]
code: 500
message: "There was an error processing your request. It has been logged (ID 4b5e102cedcd4592)."

https://api-dev.col.plus/importer?limit=25&offset=0&state=waiting&state=downloading&state=processing&state=inserting&state=indexing&state=building%20metrics

**Comment by thomasstjerne** [comment]
Seems to happen directly after an import is triggered

**Comment by mdoering** [comment]
The duplication issue is still unresolved. @thomasstjerne can I leave this open and fix after holidays or is this blocking?

**Comment by thomasstjerne** [comment]
> The duplication issue is still unresolved. @thomasstjerne can I leave this open and fix after holidays or is this blocking?

Sure. Have a nice summer!
