### ISSUE TITLE
Imports: 400 already queued error when not actually queued

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#414]
When importing an uploaded dataset from the [meta data page](https://www.col.plus/dataset/2074/meta), the frontend posts a 400 already queued for import error, even when the queue is empty prior to clicking the import button and also the [import actually completes successfully despite the error message](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:'2019-07-02T21:10:47.459Z',mode:absolute,to:'2019-07-02T21:25:28.290Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:dataset,negate:!f,type:phrase,value:'2074'),query:(match:(dataset:(query:'2074',type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))):

![image](https://user-images.githubusercontent.com/8573609/60547499-7ec82300-9ce5-11e9-80dc-008e0ccf231a.png)

The same 400 error is correctly displayed for externally registered datasets and only when the user clicks the import button while it's still in the import queue.

Here's the api requests after clicking the import button:

```
https://api.col.plus/importer
Host: api.col.plus
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:3000/
Authorization: Bearer [redacted]
Content-Type: application/json;charset=utf-8
Content-Length: 48
Origin: http://localhost:3000
DNT: 1
Connection: keep-alive
{"datasetKey":2074,"priority":true,"force":true}
POST: HTTP/1.1 201 Created
Date: Tue, 02 Jul 2019 21:17:22 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Language, X-Requested-With
Content-Length: 136
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
https://api.col.plus/importer

Host: api.col.plus
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: authorization,content-type
Referer: http://localhost:3000/
Origin: http://localhost:3000
DNT: 1
Connection: keep-alive
OPTIONS: HTTP/1.1 200 OK
Date: Tue, 02 Jul 2019 21:17:22 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Content-Type: text/plain; charset=UTF-8
Allow: HEAD,POST,GET,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Language, X-Requested-With
Content-Length: 24
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
```

**Comment by mdoering** [comment]
not reproducible anymore
