### ISSUE TITLE
User not authorized on sector rematch

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#416]
When clicking the rematch button on [any dataset sector page](https://www.col.plus/dataset/1141/sectors), I get a 403 user not authorized error even when logged in.

Here's the API call:

```
https://api.col.plus/admin/rematch
Host: api.col.plus
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://www.col.plus/
Authorization: Bearer [redacted]
Content-Type: application/json;charset=utf-8
Content-Length: 19
Origin: https://www.col.plus
DNT: 1
Connection: keep-alive
{"sectorKey":20264}
POST: HTTP/1.1 403 Forbidden
Date: Wed, 03 Jul 2019 20:23:43 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Language, X-Requested-With
Content-Length: 45
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive

https://api.col.plus/admin/rematch
Host: api.col.plus
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: authorization,content-type
Referer: https://www.col.plus/
Origin: https://www.col.plus
DNT: 1
Connection: keep-alive
OPTIONS: HTTP/1.1 200 OK
Date: Wed, 03 Jul 2019 20:23:43 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Content-Type: text/plain; charset=UTF-8
Allow: POST,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Language, X-Requested-With
Content-Length: 13
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
```

**Comment by gdower** [comment]
I can't find much info on it in the [logs](https://logs.gbif.org/app/kibana#/context/AWGthDPVf8lu3pmEwvFE/logs/AWu5kaJWrbHgAYk4zpfP?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-15m,mode:quick,to:now))). Maybe it's actually a frontend problem.

**Comment by mdoering** [comment]
It might be that its an rights issue. All /admin resources require the admin role, not the editor one.
@gdower Do you have that role? Hm, not easy to find out. You need to use the API which is not simple as you need to first get a token. I would suggest we add some user info to the frontend.

The GBIF registry tells me you only have editorial rights. I will make you an admin now, please try again then!

**Comment by gdower** [comment]
Fixed
