### ISSUE TITLE
Excluding datasets from names index?

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#417]
Probably we don't want the fake unit test data included in the names index, which is where "Ani&nbsp;malia" originated. Is there a way to exclude testing datasets from the names index? Alternatively, I could only use real data for the unit testing datasets but would it be desirable to include those known data errors in the names index?

![image](https://user-images.githubusercontent.com/8573609/60824900-1effcb00-a170-11e9-9bb6-7a6ae8f2c283.png)

**Comment by mdoering** [comment]
The names index exists primarily to inform about where to find the same name, i.e. to group names from all datasets. It is not intended to provide nomenclatural data or to list only real names. Having bad names in there is unavoidable as they will appear all over the place. 

Having said that adding dirty bad names into it on purpose is probably not a good idea and we should provide a way to exclude entire datasets. Initially we provided a flag that needed to be actively set to include a dataset. Doing it the other way around, including any dataset by default and allowing it to be excluded manually later on sounds like a good option to me.

**Comment by mdoering** [comment]
After rethinking I think we can safely leave the dirty data in.
When a test dataset is the only source for a bad non name and it is removed, [all the names will also be logically removed](https://github.com/Sp2000/colplus-backend/issues/212) from the Names Index (i.e. they remain in the db but will be marked as deleted so we can revive their stable id if needed later). Hence when we go live and remove all testing datasets we wont notive their dirty data

Also see https://github.com/Sp2000/colplus-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+namesindexcontributor for frontend
