### ISSUE TITLE
No taxa imported into pg?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#42]
but where are they? How do we get from name to taxon? And there are no taxa???
http://api.col.plus/taxon
There should be 16000 for this dataset alone: http://api.col.plus/dataset/11/import

**Comment by ayco-at-naturalis** [comment]
Caused by datasetKey param not present in URL. datasetKey param now optional

**Comment by mdoering** [comment]
failed tests https://builds.gbif.org/job/colplus-backend/lastBuild/testReport/
