### ISSUE TITLE
Does merge sectors avoid plain duplicates?

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#422]
I have a question about merge sectors.
In the attached screenshot a source has 2 families not in the assembly, but also 4 that are already there from other sectors. Will a merge sector detect and skip the 4 plain (identical name) duplicates?

<img width="996" alt="mergesector" src="https://user-images.githubusercontent.com/1666484/61106877-ba4db480-a47e-11e9-9f39-862345f06a07.png">

**Comment by thomasstjerne** [comment]
Preferably, it should act like an amendment rather than a simple merge.

**Comment by mdoering** [comment]
as it is setup right now it simply copies all childs over and it is up to the editor to deal with duplicates. 

In this case the 4 duplicate families should either be blocked manually or there should be sectors defined on the family level.

We *could* provide a real merge/amend action that only copies over non existing taxa and and option to do so recursively down to infraspecies
