### ISSUE TITLE
Sync still blocks species after decision is removed

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#423]
To reproduce:

1. Create a new sector at family level under an order
2. Block one genus in the family
3. Sync the sector (this correctly omits the genus that is blocked)
4. Delete the block-decision
5. Sync sector again
6. Now the genus appears, but species in that genus are missing

Logs:
https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:sector,negate:!f,type:phrase,value:'20208'),query:(match:(sector:(query:20208,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:attempt,negate:!f,type:phrase,value:'2'),query:(match:(attempt:(query:2,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:environment,negate:!f,type:phrase,value:col-dev),query:(match:(environment:(query:col-dev,type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))

**Comment by mdoering** [comment]
I cannot reproduce this any longer
