### ISSUE TITLE
Log failed sector syncs

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#425]
Related to #424, failed sector syncs do not seem to be returned by the API and it may be useful to log failed sector syncs, especially so that we are able to troubleshoot failed sector syncs when syncing all CoL+ sectors:

https://api.col.plus/assembly/3/sync?limit=25&offset=0
https://api.col.plus/assembly/3/sync?limit=25&offset=0&state=failed

**Comment by mdoering** [comment]
The sync list allows in theory to filter just failed syncs:
https://www.col.plus/sector/sync?limit=25&offset=0&type=failed&type=canceled

The [filter is currently broken though](https://github.com/Sp2000/colplus-frontend/issues/319).

**Comment by mdoering** [comment]
API is working: https://api.col.plus/assembly/3/sync?limit=25&offset=0&state=failed
