### ISSUE TITLE
Duplicates and decisions bugs

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#426]
@ayco-at-naturalis @thomasstjerne @mdoering, I'm developing [frontend tests](https://github.com/Sp2000/colplus-frontend-tests/blob/master/tests/test_tasks_dashboard.py) to check the CRUD functionality of the tasks dashboard. It might be a backend bug, but when applying ambiguous decisions to "ACC-SYN infraspecies (different parent, same authors)" the decision is remembered but [not displayed by the frontend](https://github.com/Sp2000/colplus-frontend/issues/274). The dashboard still shows 2 duplicates after applying the decision and fails the assertion that duplicates should be 0 after applying the ambiguous synonyms decision.

Steps to reproduce:

1) Go to any "[Dashboard tasks testing](https://www.col.plus/dataset?limit=50&offset=0&q=dashboard%20tasks%20testing)" dataset
2) Click on tasks in the dataset menu
3) Click on "ACC-SYN infraspecies (diff parent, same authors)"
4) Click on "All synonyms" button
5) Apply ambiguous synonyms decision (you might get a 400 error if someone else applied the decision, see below)
6) Go back to the tasks pane and you'll see that "ACC-SYN infraspecies (diff parent, same authors)" is still showing 2 duplicates, when it should be 0
7) Click on "ACC-SYN infraspecies (diff parent, same authors)" again and you'll see the decisions aren't remembered
8) If you try to apply the same decision again, you'll get a 400 error which makes me think it might also be a frontend bug with the frontend not displaying past decisions

The API returns [no results withDecision=True](https://api.col.plus/dataset/2116/duplicate?authorshipDifferent=false&category=trinomial&limit=51&minSize=2&mode=STRICT&offset=0&parentDifferent=true&status=accepted&status=synonym&withDecision=true).

**Comment by gdower** [comment]
There are no calls to the /decision API from the [duplicates page](https://www.col.plus/dataset/2116/duplicates?authorshipDifferent=false&category=trinomial&limit=50&minSize=2&mode=STRICT&offset=0&parentDifferent=true&status=accepted&status=synonym&withDecision=false), so at least 1 of these bugs is a [frontend bug](https://github.com/Sp2000/colplus-frontend/issues/274). The [decisions are remembered by the backend](https://api.col.plus/decision?datasetKey=2116).

I think the other bug is with duplicates search, because the synonyms with decisions shouldn't be getting returned when the parameter [withDecision=false](https://www.col.plus/dataset/2116/duplicates?authorshipDifferent=false&category=trinomial&limit=50&minSize=2&mode=STRICT&offset=0&parentDifferent=true&status=accepted&status=synonym&withDecision=false).

**Comment by gdower** [comment]
The 3rd bug is the backend not allowing decisions to be updated (error code 400 above), so I opened a separate issue ticket [here](https://github.com/Sp2000/colplus-backend/issues/427) and will strike that above. This issue is for the duplicate search bug.

**Comment by gdower** [comment]
The same bug is present for blocked synonyms, where the [block decision has been applied](http://api.col.plus/decision?datasetKey=2132&id=B9-3) but the [tasks dashboard still shows "SYN-SYN species (same parent, same authors)" as still having 1 duplicate](http://www.col.plus/dataset/2132/tasks) when it should be 0.

After [provisionally accepted decisions are applied](http://api.col.plus/decision?datasetKey=2133), the task dashboard works correctly and [displays 0 matches for the ACC-ACC species (same authors)](http://www.col.plus/dataset/2133/tasks).

**Comment by mdoering** [comment]
Decision get created correctly - @thomasstjerne with the exception that the status of the subject is not posted which is crucial for duplicates as thats the only way to differ between them in some cases e.g. the ACC-SYN one. But indeed the duplicate response does ignore it, this seems like a true backend bug, Ill investigate.

**Comment by mdoering** [comment]
Should there not also be a way to see all decisions for a dataset? Maybe integrated as a filter in the names section?

**Comment by mdoering** [comment]
Ahhh, I think I've got it. @thomasstjerne the frontend seems to post the Name ids, not the usage ids:
```
 117 |        2113 | B4-5       | Solanum bahamense var. luxurians     | D'Arcy             | variety      |              |                |                |   
 118 |        2113 | B5-5       | Artemisia eriopoda var. rotundifolia | (Debeaux) Y.R.Ling | variety      |              |                |                |   
````

Please post usage ids !!!

**Comment by mdoering** [comment]
to be solved in the frontend issue https://github.com/Sp2000/colplus-frontend/issues/278

**Comment by thomasstjerne** [comment]
@mdoering I think the frontend now posts usage ids correctly after this was fixed: https://github.com/Sp2000/colplus-frontend#278

However, @gdower has tested this, and decisions are here:
https://api-dev.col.plus/decision?datasetKey=2070

But still not here:
https://api-dev.col.plus/dataset/2070/duplicate?authorshipDifferent=false&category=trinomial&limit=51&minSize=2&mode=STRICT&offset=0&parentDifferent=true&status=accepted&status=synonym&withDecision=true

**Comment by thomasstjerne** [comment]
The when using withDecision=true you get correct results, however the usages should be decorated with their decisions (or at least a decisionKey) for the fronted to be able to show them.

**Comment by mdoering** [comment]
Hm, there should really be a decision property. We have [working unit tests](https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/test/java/org/col/db/mapper/DuplicateMapperTest.java#L78) that check for that

**Comment by mdoering** [comment]
got it, related to dataset_key and subject_dataset_key change
