### ISSUE TITLE
authorsAndEditors not being read from metadata.yaml

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#428]
For 2 different repos the authors and editors aren't being read out of metadata.yaml:

 - [Cycads](https://www.col.plus/dataset/1163/meta) ([yaml](https://github.com/gdower/data-cycads/blob/master/metadata.yaml))
 - [World Ferns](https://www.col.plus/dataset/1140/meta) ([yaml](https://github.com/Sp2000/data-world-ferns/blob/master/metadata.yaml))

There's no yaml related errors in the [logs](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:dataset,negate:!f,type:phrase,value:'1163'),query:(match:(dataset:(query:'1163',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:attempt,negate:!f,type:phrase,value:'4'),query:(match:(attempt:(query:'4',type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))).

**Comment by mdoering** [comment]
@gdower while making sure all metadata gets through, do we want version names like `ver. (02/2019)` ? I would have thought simply `02/2019` is a better version name.

**Comment by mdoering** [comment]
I also wonder if in case of known ORCIDs we should just pass the orcid alone without a name. It can easily be retrieved from [their API](https://pub.sandbox.orcid.org/v2.0/#!/Public_API_v2.1/viewPersonalDetailsV21).

**Comment by mdoering** [comment]
as you can see thru the API the authors exist, just the frontend isnt showing them:
https://api.col.plus/dataset/1163/

How to deal with ORCIDs to be resolved in issue #309

**Comment by gdower** [comment]
> @gdower while making sure all metadata gets through, do we want version names like `ver. (02/2019)` ? I would have thought simply `02/2019` is a better version name.

I'm aiming to standardize all dates to the format of YYYY-MM-DD, YYYY-MM, or YYYY, including database versions in the metadata where a date was used as the version.

**Comment by gdower** [comment]
> I also wonder if in case of known ORCIDs we should just pass the orcid alone without a name. It can easily be retrieved from [their API](https://pub.sandbox.orcid.org/v2.0/#!/Public_API_v2.1/viewPersonalDetailsV21).

@mdoering, if you mean removing the author name from the metadata.yaml and just using an ORCID, I'd recommend still keeping the author name so that the metadata is human readable, too. 

BTW, we actually should not include email addresses in the metadata.yaml, because there's some data providers that do not like getting directly contacted by CoL users.

**Comment by mdoering** [comment]
well, shouldn't the contact of the metadata at least have an email address? Thats the purpose to get contacted. At GBIF we require at least one contact address for every dataset

**Comment by gdower** [comment]
I think we should have a separate private repo where we store private contact info. Publishers don't do a good enough job of protecting authors' emails, which results in a lot of [unsolicited spam emails from predatory publishers](http://blogs.nature.com/naturejobs/2018/04/11/clean-your-email-inbox-with-a-low-spam-diet/). Also, it's against the law to publish email addresses in some countries.

CoL gets a large number of general inquiry emails from the public that would be a burden for the data providers to handle, and the contact info is really intended for the editorial office so that we can contact a data provider when there actually is a good reason to contact them.

Even if a user, data provider, or editor specifies that they are willing to receive emails the public, it really ought to be through an email form with their email address concealed. That way they can choose whether to expose their email address to a sender by responding to an email.

**Comment by mdoering** [comment]
Some very valid points we should discuss in the group. We also need to clarify what the email address ought to be used for. Is it just for personal mailing between the editor(s) and the dataset provider? At some point we surely want system notifications to go to dataset provider/publishers (GBIF uses the term publisher for what CoL traditionally calls providers) and we need an email address for that. It might be better handled through a real CoL user account instead of some unauthenticated contact address though. That way providers can opt out if they like.

On the other hand GBIF exposes for more than a decade all dataset contacts so far without any problem being reported to us: https://www.gbif.org/dataset/af66d4cf-0fd2-434b-9334-9806a5efa6f7#contacts

@timrobertson100 @MortenHofft @thomasstjerne do you have recommendations on best practices for contact emails these days?
