### ISSUE TITLE
Wrong uninomial rank detected by name parser

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#429]
In World Ferns, CoL+ seems to be automatically filling in ranks for uninomial synonyms, because I left them blank but here are a [list of uninomial synonyms that have been assigned the rank tribe](https://www.col.plus/dataset/1140/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&rank=form&limit=100). There's nothing in the [raw data](https://github.com/Sp2000/data-world-ferns/tree/master/raw), [CoLDP files](https://github.com/Sp2000/data-world-ferns/tree/master/coldp), or verbatim data assigning tribe to those names.

Synonym ranks often aren't provided except for ranks below species. I could fill in the ranks for species, but specifying ranks for uninomials could be more problematic. Should I specify them as "[unranked](http://api.col.plus/vocab/rank)?"

**Comment by gdower** [comment]
Maybe this is being done using the uninomial suffixes? But isn't **-oideae** for subfamilies and **-eae** for tribe in the botanical code? If so, some of them seem to be incorrect:

Woodsi**oideae** Shmakov
Antrophy**oideae** Link
Protowoodsi**oideae** Shmakov

**Comment by mdoering** [comment]
Yes, the name parser recognises distinct suffices and I guess thats how some ranks get established: https://github.com/gbif/name-parser/blob/master/name-parser-api/src/main/java/org/gbif/nameparser/util/RankUtils.java#L162

Please tell me incorrect results so we can improve things.
One thing we could definitely do is separate them by their code which we usually know to yield better results.

**Comment by mdoering** [comment]
see https://en.wikipedia.org/wiki/Taxonomic_rank#Terminations_of_names

**Comment by mdoering** [comment]
`-eae` for Tribe is maybe a too low confidence - even together with a known botanical code?
