### ISSUE TITLE
Allow NULL relatedNameIDs in NameRel?

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#432]
I have one data source where names are specified as `nomen superfluous` without unambiguously specifying which name it is [superfluous](http://api.col.plus/vocab/nomreltype) with. I think this could potentially be a common problem if data curators are not explicitly recording these name relationships yet. I propose making `relatedNameID` optional so that we can still indicate the `nomen superfluous` status and other name relationships without specifying the name relationship. The name relationship could be flagged as incomplete with an issue and added at a later date when the data becomes available. 

Currently trying to import the CoLDP `NameRel` table with `NULL` as `relatedNameID` seems to [crash the importer](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWBa0XR-f8lu3pmE7ete,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:dataset,negate:!f,type:phrase,value:'1140'),query:(match:(dataset:(query:'1140',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWGthDPVf8lu3pmEwvFE,key:attempt,negate:!f,type:phrase,value:'1'),query:(match:(attempt:(query:'30',type:phrase))))),index:AWGthDPVf8lu3pmEwvFE,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))). Setting the ID to the non-existent ID 'unknown' results in `nomen superfluous` relationship not being set. If I set the nameID and relatedNameID equal, the name is designated as `nomen superfluous` but that might not be the best approach for handling incomplete data.

**Comment by mdoering** [comment]
Relations is intended to strictly be just relations between 2 names. To indicate just the status of a name the nomStatus and remarks field should be used instead:

https://github.com/Sp2000/colplus/blob/master/docs/NAMES.md#name-status

keep the import bug as new issue #433

**Comment by gdower** [comment]
@mdoering, names with the status nomen superfluous are still superfluous with another name even if the name relationship has not been parsed out of the literature yet, so I think they should still be stored in the name relations table with `NULL` or `''` as the `relatedNameID` and flagged with an `INCOMPLETE_NAME_REL` issue.

I wouldn't be surprised if a large number of name relationships aren't completely recorded yet, so it potentially might be useful to have a data storage structure that accommodates incomplete data instead of just dumping these incomplete name relationships into remarks where the data will be harder to use, and less likely to be completed.
