### ISSUE TITLE
Missing sectors and nested sectors

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#434]
For some reason a lot of sector attachment points are missing:

![image](https://user-images.githubusercontent.com/8573609/62308770-b690ca80-b44b-11e9-9b98-4365a495a7a7.png)

In AC2019 we have these sectors:

![image](https://user-images.githubusercontent.com/8573609/62308961-18513480-b44c-11e9-8fe9-1dc5a222f50d.png)

Maybe those are the broken sectors?

Additionally, it might also simplify things if we change Geraniaceae to CoL Management Classification so that we don't ever have any sectors nested within sectors. I could try to modify the sector generation script to only create sector attachment points at ranks where all sub-taxa are managed by a single GSD. Sometimes the sector attachment points would then be at the genus level like for the family [Fabaceae](http://www.catalogueoflife.org/annual-checklist/2019/browse/tree/id/aaa8d7d014c8f28d3d9505f29c127815). If we could still perform a sync all sectors below any rank, it could still be manageable.

**Comment by mdoering** [comment]
I think this should be restricted to WorldPlants, StaphBase and Cycads as we manually manage these sectors and do not export them from AC. See https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/main/resources/org/col/db/sectors.sql#L9

Those sectors are lacking a sourceId and need to be matched after a first import has happened.
That *should* happen automatically once an import has succeeded and actually contains such a name. Does this happen elsewhere or after successful imports?

**Comment by mdoering** [comment]
I would not remove the option of nested sectors. Without them it gets really complex I think and the code should already by prepared for it anyways

**Comment by mdoering** [comment]
I am closing this now. @gdower can you please reopen the issue when you find other cases then the ones I listed above?
