### ISSUE TITLE
Add ac-export service to dev?

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#439]
Adding the ac-export service to dev would be useful for testing since sometimes dev is working while prod is broken. I'm assuming this might be relatively quick and easy to do, but if not I can make do without it.

**Comment by mdoering** [comment]
yes, the code runs on dev too but its probably badly configured.
Is it good enough if dev would export to another file at http://api.col.plus/download/ ?

**Comment by gdower** [comment]
Sure, but this isn't essential so don't worry about it if you're busy with GBIF stuff.

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-deploy/commit/18bc8407c7ec3aa79f1c12b8bcf0b3023e5ffa7c

**Comment by mdoering** [comment]
http://api-dev.col.plus/download/
