### ISSUE TITLE
Sync status gives 500 after sector deletion

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#442]
After deleting a sector, calling https://api-dev.col.plus/assembly/3 gives 500:
There was an error processing your request. It has been logged (ID 3795dffa9dd58054)

**Comment by mdoering** [comment]
> java.lang.IllegalStateException: Non running or waiting sync with state FAILED found in queue for sector 4
> 	at org.col.assembly.AssemblyState.<init>(AssemblyState.java:31)
> 	at org.col.assembly.AssemblyCoordinator.getState(AssemblyCoordinator.java:92)
> 	at org.col.resources.AssemblyResource.state(AssemblyResource.java:46)
