### ISSUE TITLE
Importer: state param ignored when running param given

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#444]
Trying to switch from state params to running param as suggested in https://github.com/Sp2000/colplus-frontend/issues/280

But this currently breaks filtering on states:
https://api-dev.col.plus/importer?limit=25&offset=0&running=false&state=canceled

**Comment by mdoering** [comment]
yes, running is just a shortcut for the entire set of (not=false) running states which gets unified with the states given individually. If you need to filter states you need to avoid the running parameter
