### ISSUE TITLE
Add date to version number

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#445]
Can you please add the commit date to the [version number](http://api.col.plus/version) with the commit hash (e.g., something like this: 2019-08-14 c05acb4)? That way it will be human-readable, too, so that Yuri will know the last deployment date. I'm also opening a frontend issue to display the frontend and backend version numbers in the frontend so that we can include it in bug reports.

**Comment by mdoering** [comment]
will be sth like `a1c7f7b - 2019-08-14T12:40:02+0200` with next deploy
