### ISSUE TITLE
Different taxon ids in search index and in tree api

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#446]
The assembly pages uses the search index to search for a taxon in the assembly, and if it is found, it uses the tree api to expand down to that taxon.

There seems to be cases where a taxon has different ids in the two apis: 

Cycadopsida in the search index: 8deceba7-a552-44d2-b37a-a2029c2b70b4
Cycadopsida in the tree api: d6458ee7-17ca-4835-b4f7-f190fd58e97a

Backend version: e206678 running on dev

**Comment by mdoering** [comment]
Yes, expected after syncs as we do not update elastic properly during syncs, see #437
