### ISSUE TITLE
ACEF ambiguous and misapplied synonyms not being imported correctly

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#449]
The backend [is flagging ACEF ambiguous and misapplied synonyms that are shared by more than 1 parent as having duplicate IDs](https://www.col.plus/dataset/1015/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=id%20not%20unique&limit=100). While technically they are duplicate IDs, the data is represented correctly in the ACEF schema and it is not an issue that needs editorial attention unless the backend is not associating each synonym with their accepted parents. However, the backend does not seem to be correctly attaching ambiguous synonyms to their accepted names, because *[Senna septemtrionalis](https://www.col.plus/dataset/1015/taxon/629)* is missing its ambiguous synonym *Cassia laevigata* Willd, while *[Senna floribunda](https://www.col.plus/dataset/1015/taxon/17547)* does have the ambiguous synonym *Cassia laevigata* Willd.

For the misapplied name, *Albizia julibrissin* sensu auct., non Durazz., the accepted parent *[Albizia lebbekoides](https://www.col.plus/dataset/1015/taxon/22434)* has 2 blank misapplied names, and the other accepted parent *[Albizia philippinensis](https://www.col.plus/dataset/1015/taxon/24571)* also has a blank misapplied name.

The ambiguous synonym, *Azukia angularis* (Willd.)Ohwi, shows up in the synonyms section for the accepted parent *[Vigna angularis](https://www.col.plus/dataset/1015/taxon/2196)*, but not [*Vigna angularis* var. *angularis*](https://www.col.plus/dataset/1015/taxon/19801).

As for the issue rules for ACEF imports, we would be interested in cases where both the ID and AcceptedTaxonID are identical in 2 or more records, because those would likely be duplicates or mistakes.

ID | AcceptedTaxonID | Genus | SubGenusName | SpeciesEpithet | AuthorString | InfraSpeciesEpithet | InfraSpeciesMarker | InfraSpeciesAuthorString | GSDNameStatus | Sp2000NameStatus | GSDNameGUID
|--|--|--|--|--|--|--|--|--|--|--|--|
S-1025 | 17547 | Cassia |  | laevigata | Willd. |  |  |  |  | ambiguous synonym | 
S-1025 | 629 | Cassia |  | laevigata | Willd. |  |  |  |  | ambiguous synonym | 
S-52555 | 22434 | Albizia |  | julibrissin | sensu auct.,  non Durazz. |  |  |  |  | misapplied name | 
S-52555 | 24571 | Albizia |  | julibrissin | sensu auct.,  non Durazz. |  |  |  |  | misapplied name | 
S-3444 | 2196 | Azukia |  | angularis | (Willd.)Ohwi |  |  |  |  | ambiguous synonym | 
S-3444 | 19801 | Azukia |  | angularis | (Willd.)Ohwi |  |  |  |  | ambiguous synonym | 
S-52726 | 24606 | Pithecellobium |  | bigeminum | sensu auct.,  non (L.)Mart. |  |  |  |  | misapplied name | 
S-52726 | 22445 | Pithecellobium |  | bigeminum | sensu auct.,  non (L.)Mart. |  |  |  |  | misapplied name | 
S-55090 | 26061 | Hedysarum |  | grandiflorum |  | sericeum | subsp. | B.Fedtsch., p.p. |  | ambiguous synonym | 
S-55090 | 26116 | Hedysarum |  | grandiflorum |  | sericeum | subsp. | B.Fedtsch., p.p. |  | ambiguous synonym | 
S-55211 | 26124 | Hedysarum |  | microphyllum | sensu Turcz., p.p. |  |  |  |  | misapplied name | 
S-55211 | 26125 | Hedysarum |  | microphyllum | sensu Turcz., p.p. |  |  |  |  | misapplied name | 
S-55077 | 26099 | Hedysarum |  | pamiralaicum | Korotkova, p.p. |  |  |  |  | ambiguous synonym | 
S-55077 | 18556 | Hedysarum |  | pamiralaicum | Korotkova, p.p. |  |  |  |  | ambiguous synonym | 
S-54852 | 25934 | Oxytropis |  | oligantha | sensu auct. |  |  |  |  | misapplied name | 
S-54852 | 25987 | Oxytropis |  | oligantha | sensu auct. |  |  |  |  | misapplied name | 
S-3443 | 2196 | Phaseolus |  | angularis | (Willd.)W.Wight |  |  |  |  | ambiguous synonym | 
S-3443 | 19801 | Phaseolus |  | angularis | (Willd.)W.Wight |  |  |  |  | ambiguous synonym | 
S-12420 | 468 | Alvesia |  | tomentosa | (L.)Britton & Rose |  |  |  |  | ambiguous synonym | 
S-12420 | 493 | Alvesia |  | tomentosa | (L.)Britton & Rose |  |  |  |  | ambiguous synonym | 
S-55149 | 26101 | Hedysarum |  | plumosum | sensu auct. |  |  |  |  | misapplied name | 
S-55149 | 26095 | Hedysarum |  | plumosum | sensu auct. |  |  |  |  | misapplied name | 
S-2776 | 1776 | Dolichos |  | lablab | L. |  |  |  |  | ambiguous synonym | 
S-2776 | 1777 | Dolichos |  | lablab | L. |  |  |  |  | ambiguous synonym | 
S-55093 | 26062 | Hedysarum |  | pumilum | sensu auct., p.p. |  |  |  |  | misapplied name | 
S-55093 | 26090 | Hedysarum |  | pumilum | sensu auct., p.p. |  |  |  |  | misapplied name | 
S-54703 | 11918 | Oxytropis |  | tschuktschorum | Jurtzev, p.p. |  |  |  |  | ambiguous synonym | 
S-54703 | 25819 | Oxytropis |  | tschuktschorum | Jurtzev, p.p. |  |  |  |  | ambiguous synonym | 
S-3567 | 17513 | Phaseolus |  | trinervius | Wight & Arn. |  |  |  |  | ambiguous synonym | 
S-3567 | 2258 | Phaseolus |  | trinervius | Wight & Arn. |  |  |  |  | ambiguous synonym |

**Comment by gdower** [comment]
@mdoering & @thomasstjerne, actually I think there's a frontend bug on the misapplied names, too, which may be part of the problem because misapplied names are showing in the API for [*Albizia lebbekoides*](https://www.col.plus/dataset/1015/taxon/22434): https://api.col.plus/dataset/1015/taxon/22434/synonyms

I'll open a frontend issue ticket on that.

**Comment by yroskov** [comment]
Hedysarum grandiflorum sensu auct. 
Why authorstring for it was stripped off? As the author of ILDIS I asks to present our data as they have been collected and presented in the source.

**Comment by mdoering** [comment]
That is likey a shortcoming of the ACEF importer to not merge the multiple records with the same ID for ambiguous and misapplied synonyms. Good catch!
