### ISSUE TITLE
enum list - it includes the namespace

### ISSUE THREAD

**Issue by MortenHofft** [Sp2000/colplus-backend#45]
Having the enums available in the API is great

http://api.col.plus/vocab

Any reason to have the full namespace. E.g. `org.col.api.vocab.ImportState`? It isn't part of the url http://api.col.plus/vocab/ImportState So the last part have to differ anyhow i guess. And I haven't seen fields called `"org.gbif.nameparser.api.Rank" : "GENUS"` - they simple say `rank`

Just wondering

**Comment by mdoering** [comment]
very right, simple oversight

**Comment by mdoering** [comment]
fixed: http://api.col.plus/vocab
