### ISSUE TITLE
TAXON_ID_INVALID issue not showing search results

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#450]
For the TAXON_ID_INVALID issue, in two GSDs there are [37164](https://www.col.plus/dataset/1115/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=taxon%20id%20invalid&limit=100) and [2274](https://www.col.plus/dataset/1204/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=taxon%20id%20invalid&limit=100) issues flagged but search isn't showing any results.

**Comment by mdoering** [comment]
@thomasstjerne this issue needs to be directed to the verbatim search. Without a taxon id there is no interpreted name usage to search for.
