### ISSUE TITLE
Include subgenus in name matching and DUPLICATE_NAME issue

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#451]
The general DUPLICATE_NAME issue is flagging a lot of non-duplicate scientific names as duplicates because it does not take subgenus into account. Species are frequently moved between two subgenera with the previous name becoming a synonym. For example, these are not duplicates because in zoology the subgenus is a part of the name:

![image](https://user-images.githubusercontent.com/8573609/63624637-b4d9a300-c5c2-11e9-8a72-39515423b753.png)

Yet CoL+ flags them as duplicates:

![image](https://user-images.githubusercontent.com/8573609/63624684-ddfa3380-c5c2-11e9-82aa-a404d7eb7c4b.png)

Fixing this is less urgent because the CoL+ duplicates tool is good at accurately detecting duplicates, but it is going to clutter the GSD issues summary with duplicates that aren't actually duplicates, which will make it harder to find GSDs where there are actual duplicate problems that need to be resolved.

**Comment by mdoering** [comment]
This is intended behavior based on name matching and the names index which we can discuss. It has been open for comments since the very beginning of the project, see:

 - https://github.com/Sp2000/colplus/blob/master/docs/NAMES.md#names-index-and-name-equality
 - https://github.com/Sp2000/colplus/issues/35
 - https://github.com/Sp2000/colplus/issues/47

**Comment by mdoering** [comment]
I can see the point of including subgenus in the name matching, thus treating the same binomial with different subgenera as distinct name entities in the names index. Rich has actually pointed that out in the name [original identity issue](https://github.com/Sp2000/colplus/issues/35#issuecomment-338826174).

To me this raises the following linked questions:

 - can we safely apply this also to the botanical code? I would say yes
 - can we still safely ignore the subspecies in 4 parted names such as `Foo bar Lin. subsp. dar Mill. var. lion Smith 1850`?

**Comment by gdower** [comment]
My other thought might be to include nomenclatural duplicates and taxonomic duplicates as separate issues, because the goals of the two are probably different. @yroskov, what do you think?

The other possibility might be extending my gsd-issues report generator to get the specific duplicates counts used on the [tasks](https://www.col.plus/dataset/1141/tasks) page and include those statistics in the gsd-issues report.

**Comment by yroskov** [comment]
Separate tax & nom duplicates in general: it will add too much complexity. Both are overlapping. It is OK to manage both separately in GSD, but not in secondary resource such as CoL. 
Regarding subgenus issues: subgenus is a part of binomial in ZOOLOGY (ICZN Art 6.1). It should be included in a check for duplicated names. If binomials differs by different subgenus name, these species names are different, and should not be included in a report.

**Comment by mdoering** [comment]
[6.1. Names of subgenera](https://code.iczn.org/chapter-2-the-number-of-words-in-the-scientific-names-of-animals/article-6-interpolated-names/?frame=1)
> The scientific name of a subgenus, when used with a binomen or trinomen, must be interpolated in parentheses between the generic name and the specific name; it is not counted as one of the words in the binomen or trinomen. It must begin with an upper-case letter.

This is not entirely clear to me. It says it is not part of the binomen but used with the binomen

**Comment by mdoering** [comment]
Only applies to Zoology, remove infragenerics in botany
