### ISSUE TITLE
allow to DELETE a sector with non existing target

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#453]
I think it would be useful to allow deletion of a broken sector.
Sector 2715 does have a non existing target id

It would be the easy to simple delete and then recreate a sector that has lost its target

**Comment by mdoering** [comment]
sounds about right. But still delete its data if present, correct?
Usages will still have a sectorKey

**Comment by thomasstjerne** [comment]
> But still delete its data if present, correct?
Yes, definitely.
