### ISSUE TITLE
14 GSDs missing all scientific_names in ac-export

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#454]
There's potentially [2 different bugs with ac-exporter]():

- [ ] 14 GSDs are missing all ac-export.scientific_names
- [ ] 48, 49, 96, 162, 166, 172, 199 are missing in ac-export.families which might be a sector bug

All are present in `databases` which is good because ConversionTool will drop any records that don't have a record_id/database_id included in `databases`.

The sectors & data are included in CoL+:

GSD|Full name|Short name|CoL+ Sectors
-- | -- | --| --
14 | ICTV/MSL: International Committee on Taxonomy of Viruses / Master Species List | ICTV_MSL | [Viruses](https://www.col.plus/assembly?assemblyTaxonKey=d4a58396-a3b7-4399-9cc9-db1a8c2b4904)
31 | Global Taxonomic Database of Tineidae (Lepidoptera) | Tineidae NHM | [Tineidae](https://www.col.plus/assembly?assemblyTaxonKey=a6e6d2d6-1d59-4c23-9a96-1f9a3a743bb7)
37 | ZOBODAT: Zoological-Botanical Database (Vespoidea) | ZOBODAT Vespoidea | [Allorhyncium](https://www.col.plus/assembly?assemblyTaxonKey=d4a58396-a3b7-4399-9cc9-db1a8c2b4904), [Cochlischnogaster](https://www.col.plus/assembly?assemblyTaxonKey=66008ed2-ee3c-48e0-b355-cbeb8c52a3a4), [Emeryrhynchium](https://www.col.plus/assembly?assemblyTaxonKey=d7a4e948-b0f7-4021-b3bf-daf418d49ce0), [Eumenidae](https://www.col.plus/assembly?assemblyTaxonKey=10a3dde8-4e16-4955-b893-86b161ad7f36), [Masaridae](https://www.col.plus/assembly?assemblyTaxonKey=5a3d8149-61ea-4bcf-b008-8bdbafe8ae80), [Aethiopicodynerus](https://www.col.plus/assembly?assemblyTaxonKey=3f06ed1a-f61a-4b9a-bb20-47e180faa409), [Extreuodynerus](https://www.col.plus/assembly?assemblyTaxonKey=5f682f04-61fb-4737-b3f1-3e16a5f6c680), [Indodynerus](https://www.col.plus/assembly?assemblyTaxonKey=2823510a-7be9-47ca-9c3e-8a643bb4c8f3), [Simplepipona](https://www.col.plus/assembly?assemblyTaxonKey=c4aef433-9a0d-4501-bc96-f06d60f6f97f), [Vespidae](https://www.col.plus/assembly?assemblyTaxonKey=cd634942-0b89-4a13-affe-d9a98f691af3)
46 | Global Butterfly Information System | GloBIS (GART) | [Lycaenidae](https://www.col.plus/assembly?assemblyTaxonKey=1ec1734f-be62-4e93-8c17-c9a23c8d890e), [Pieridae](https://www.col.plus/assembly?assemblyTaxonKey=cd59137c-bca5-42f0-a1ca-6d14c6f6d0cc), [Papilionidae](https://www.col.plus/assembly?assemblyTaxonKey=1ec1734f-be62-4e93-8c17-c9a23c8d890e)
48 | Geranium Taxonomic Information System | RJB Geranium | [Geranium](https://www.col.plus/assembly?assemblyTaxonKey=fc11c169-ef6f-49ea-ad54-55ea669958a5)
49 | Global Taxonomic Database of Gracillariidae | Global Gracillariidae | [Gracillarioidea](https://www.col.plus/assembly?assemblyTaxonKey=2932777b-915e-4b1e-95c0-5f5f24284c1f)
69 | Mites GSDs: RhodacaridBase | RhodacaridBase | [Rhodacaridae](https://www.col.plus/assembly?assemblyTaxonKey=9ff40fc5-2a75-4da4-8a91-04f47cb090a8)
78 | Mites GSDs: TenuipalpidBase | TenuipalpidBase | [Tenuipalpidae](https://www.col.plus/assembly?assemblyTaxonKey=1f16a7c6-fcb7-4d42-b595-fcfb344c6cc3)
82 | Spider Mites Web | SpmWeb | [Tetranychidae](https://www.col.plus/assembly?assemblyTaxonKey=ed675d6b-fa45-4071-b6bb-d77c9e6258bd)
96 | Membracoidea of the World Database | MOWD | [Cestius](https://www.col.plus/assembly?assemblyTaxonKey=7c7ebe4f-3ca3-4bac-89ef-d5b4a09f4671), ..., Membracidae (missing)
162 | World Wide Wattle | WWW | [Parasenegalia](https://www.col.plus/assembly?assemblyTaxonKey=8a752faf-206e-4d69-948a-ad8a9516c237), [Mariosousa](https://www.col.plus/assembly?assemblyTaxonKey=4d9c0f7b-b3f1-4dbf-bf7c-f9c41076bb74), [Senegalia](https://www.col.plus/assembly?assemblyTaxonKey=6fc26b13-3bd9-4a5b-870f-cbfe43488af9), ...,  [Acacia](https://www.col.plus/assembly?assemblyTaxonKey=06742a9a-b428-446b-b7b9-1c5ae8972aca)
166 | 3i taxonomic databases Curculionidae subfamily Entiminae | 3i Curculio | [Corymacronus](https://www.col.plus/assembly?assemblyTaxonKey=1172bcf2-ae23-4f24-a396-2c0d4f7712d1), ..., [Catoptes](https://www.col.plus/assembly?assemblyTaxonKey=d954ad46-3e64-4f23-8a10-24efe7fcdcd7)
172 | Nepticulidae and Opostegidae of the World | Nepticuloidea | Nepticuloidea (missing)
199 | Catalogue of the Pterophoroidea of the World | Pterophoroidea | Pterophoroidea (missing)

Frontend version: eb54d25 August 27, 2019 7:02 AM
Backend version: cb2892d August 22, 2019 11:01 AM

**Comment by mdoering** [comment]
[Virus 14 was fixed yesterday](https://github.com/Sp2000/colplus-backend/issues/452)

**Comment by mdoering** [comment]
@gdower did you try to sync them individually? Then checking logs and looking for synced records. @thomasstjerne @gdower we should probably expose the sectorKey as a filter in the names search.

Sync all might not be reliable. It goes down sectors ordered by rank.

**Comment by mdoering** [comment]
I just synced Geranium manually and it worked just fine

**Comment by mdoering** [comment]
In production the sync all should not really be used and needed as we usually work dataset by dataset

**Comment by mdoering** [comment]
If you check the sync history of Geranium there is just one sync, it seems it never got executed during the sync all: https://www.col.plus/sector/sync?sectorKey=2818

**Comment by mdoering** [comment]
@thomasstjerne the rematch bug needs revisiting. I just clicked it 3 times and it always reported the silly ID error - but it did work when I reloaded

**Comment by mdoering** [comment]
I think we should remove the "replace" sector option. @thomasstjerne is this really needed? Can't we just delete and attach in 2 steps?

@gdower I think you gotta delete the sector first and then recreate it

**Comment by mdoering** [comment]
Caution:: The virus and ambiguous synonym fix was not deployed yet, so expect these issue to remain!
