### ISSUE TITLE
docs for /name

### ISSUE THREAD

**Issue by MortenHofft** [Sp2000/colplus-backend#46]
docs for https://sp2000.github.io/colplus/api/api.html#resource-14 says that limit defaults to one.

but
http://api.col.plus/name
isn't the same as http://api.col.plus/name?limit=1

same problem for /name/search and /taxon docs vs API

**Comment by mdoering** [comment]
bad docs that is. Comes from the beginning when I was considering to count in entire pages, not records

**Comment by mdoering** [comment]
fixed: https://github.com/Sp2000/colplus/commit/dc2754414d3950c7107488cf5728e0c58a138036
