### ISSUE TITLE
Put waiting imports in the end of the running imports rather than in the beginning

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#464]
As suggested here https://github.com/Sp2000/colplus-frontend/issues/336

**Comment by mdoering** [comment]
as we serve both running & finished pages through the same API I want to be clear about the sorting. Alternatively we could also offer 2 API methods for running & finished with a potentially different ordering.

Currently we order by priority then the date the request was created, regardless of the import state. That means running ones *should* always come before the queued ones as they were created earlier or have a higher priority. But I make sure this is always the case.

Apart from currently running ones I will keep the ordering by creation date

**Comment by thomasstjerne** [comment]
1. downloading
2. processing
3. inserting
4. indexing
5. building metrics
6. waiting
7. all finished states, ordered by creation date

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-backend/commit/50d40782637e9d78b682fbe1fd7dc92fc8d9c9c9

this does not sort the running ones by their state but by their started date
