### ISSUE TITLE
How to export unparsed non virus names

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#466]
There are likely other unparsed and/or unparsable names in the assembled CoL.
For these we only have a single string. They will likely contribute to the missing species problem for some GSD. How shall we deal with them during the AC export when we need separate genus/species/infraspecies/authorship fields?

I will inspect a real catalogue and report on real data, but in theory this would mostly apply to hybrid formulas such as `Cerasus incisa x jamasakura` - @gdower @yroskov which Im not sure the CoL even contains?

**Comment by gdower** [comment]
@mdoering, I don't think ConversionTool and/or AC_Interface can handle hybrid formulas. For World Plants we usually put the hybrid formula in the remarks/additional_details.

**Comment by yroskov** [comment]
We have tried to detect and exclude hybrid formulas from CoL. However, some of them and other incorrectly parsed names might be present in the database. 
As a shortcut solution, all incorrectly parsed names should be blocked in CoL, if we are not able to parse them correctly.

**Comment by gdower** [comment]
Here's an [example](http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/e3a7f7d475ef8000e1f1170ad1927507) and actually the old World Ferns/World Plants parser only put hybrid taxon in the remarks. The new World Ferns/World Plants parser written in July [gives hybrid formulas in the CoLDP scientificName field and adds more details in the remarks](https://raw.githubusercontent.com/Sp2000/data-world-ferns/master/coldp/Name.tsv?token=ACBNFKLXU5KYPVSHWFNGNT25P6WIU):

```tsv
5426f578-f475-546d-9a3c-0addac4e7816	Huperzia × bartleyi (Cusick) Holub	(Cusick) Holub	species	Huperzia	bartleyi		296	92	botanical			Hybrid taxon. selago agg., Huperzia lucidula x porophila
899a62d8-e532-5111-9c2d-4a2e185962ef	Lycopodium × bartleyi Cusick	Cusick		Lycopodium	bartleyi		555	100	botanical			Hybrid taxon.
9fa7a3a9-6348-51b7-9a9d-e2dabf84cd2f	Huperzia × buttersii (Abbe) Kartesz & Gandhi	(Abbe) Kartesz & Gandhi	species	Huperzia	buttersii		468	201	botanical			Hybrid taxon. selago agg., Huperzia lucidula x selago
6cfdd99c-71dd-5b83-8e1f-325c18aa41f4	Lycopodium × buttersii Abbe	Abbe		Lycopodium	buttersii		556	91	botanical			Hybrid taxon.
98fc3ec5-5b79-5e04-bc3a-99930d4ae2a0	Huperzia × carlquistii Beitel & W. H. Wagner	Beitel & W. H. Wagner	species	Huperzia	carlquistii		557	142	botanical			Hybrid taxon. Huperzia erubescens x Huperzia subintegra
7e8a563d-518a-512d-b6bd-67f0cf860d5c	Huperzia × gillettii Beitel & W. H. Wagner	Beitel & W. H. Wagner	species	Huperzia	gillettii		557	142	botanical			Hybrid taxon. Huperzia serrata x Huperzia subintegra
45a69df2-a3cc-5e78-bd20-2fdd40c68543	Huperzia × josephbeitelii A. Haines	A. Haines	species	Huperzia	josephbeitelii		558	100	botanical			Hybrid taxon. Huperzia selago x appressa
6e486715-2403-525f-bd52-2e88d5820bc1	Huperzia × beitelii A. Haines	A. Haines		Huperzia	beitelii		559		botanical			Hybrid taxon.
182c9f31-0a69-5df7-b533-76f4b39802f2	Huperzia × medeirosii Beitel & W. H. Wagner	Beitel & W. H. Wagner	species	Huperzia	medeirosii		557	142	botanical			Hybrid taxon. Huperzia haleakalae x Huperzia subintegra
8c147d4f-6134-5807-9566-405acc610ca6	Huperzia × protoporophila A. Haines	A. Haines	species	Huperzia	protoporophila		560		botanical			Hybrid taxon. Huperzia lucidula x appressa
1a91d30d-f309-5dfd-8304-273bac969374	Huperzia × sulcinervia (Spring) Trevis.	(Spring) Trevis.	species	Huperzia	sulcinervia		434	248	botanical			Hybrid taxon. Huperzia erubescens x Huperzia serrata
```

**Comment by mdoering** [comment]
@yroskov the data model in CoL+ allows to store a single entire string in case it is an unparsable name that does not fit an extended bi/trinomial structure. We do this for virus names and well known OTUs for example. That's where the Name.type attribute comes in importantly. It tells you what syntactical kind of name it is - ScientificName being a latin bi/trinomial one. 

Named hybrids with an x prefix are covered in our parsed names.
But hybrid formulas are not - they have their own NameType.HYBRID_FORMULA and are just stored as a single string. The way you did the ferns ColDP archive looks really good to me.

So we agree to remove all hybrid formulas from CoL if we can spot them?
I do this already in the assembly I believe, so thats good!

**Comment by yroskov** [comment]
Yes, pls remove all hybrid formulas

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-backend/commit/4c1824219d922e5c2a51e324d7890c7ecc80b587
