### ISSUE TITLE
Sectors often not mapping on first import

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#468]
The backend often is still requiring datasets to be imported twice in order for sectors to map successfully. In the Assembly sources pane the sectors do not show up for datasets that fail to map successfully (similar to [#424](https://github.com/Sp2000/colplus-backend/issues/424#issuecomment-512358393)): 

![image](https://user-images.githubusercontent.com/8573609/64626370-5d557880-d3b3-11e9-81a6-aabfa1f2fcce.png)

Steps to reproduce:

1) deploy and wipe
2) import world ferns
3) load world ferns in the assembly sources pane and check if sectors show
4) try to sync sectors in assembly (it will fail if missing in 3)
5) re-import world ferns
6) load world ferns in the assembly sources pane and sectors will probably show
7) sync the world ferns sectors

Here's a screenshot after importing a 2nd time in step 6:

![image](https://user-images.githubusercontent.com/8573609/64628040-554b0800-d3b6-11e9-8262-51359d32ee75.png)

If sync is run for these unmapped sectors, it results in the sectors being stuck in the preparing state, which cannot be canceled:

![image](https://user-images.githubusercontent.com/8573609/64625775-5bd78080-d3b2-11e9-8052-b79ac8225338.png)

The bug doesn't block other sectors from being imported, so it's not a huge problem. The frontend gives a blank message as well when trying to cancel these syncs. I'll open a separate frontend ticket on this issue on that:

![image](https://user-images.githubusercontent.com/8573609/64626084-de604000-d3b2-11e9-8dfa-1e9f0a36ae11.png)

Frontend version: 5e066ea September 10, 2019 8:46 AM
Backend version: 530045e September 9, 2019 11:45 AM

**Comment by gdower** [comment]
Here's probably a [relevant message on the sector for CarabCat being a duplicate](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AW0dMuj0HCKcR6PFQ4sP?_a=(columns:!(_source),filters:!(),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=()) after the first import:

```
Sector Sector{3124, datasetKey=1146, mode=ATTACH, code=null, subject=SUPERFAMILY Caraboidea} seems to be a duplicate of Sector{3124, datasetKey=1146, mode=ATTACH, code=null, subject=SUPERFAMILY Caraboidea [xabgo]} for Caraboidea in dataset 1146
```

**Comment by gdower** [comment]
This is still an issue although not a show stopper for the first monthly release:

![image](https://user-images.githubusercontent.com/8573609/68243447-1e6d2900-ffd8-11e9-99ea-e4b0c89fbb41.png)

Frontend version: 8c6e663 November 4, 2019 5:20 AM
Backend version: 1928a73 November 5, 2019 5:03 AM

The missing sectors show up in broken sectors:

```JSON
GET https://api-dev.col.plus/sector/broken?datasetKey=1140
[
  {
    "created": "2019-10-13T10:55:28.106141",
    "createdBy": 0,
    "modified": "2019-11-05T20:23:06.81244",
    "modifiedBy": 0,
    "key": 2728,
    "datasetKey": 3,
    "target": {
      "id": "bfb709db-491c-48b6-80f5-32ef14f63e4f",
      "name": "Tracheophyta",
      "rank": "phylum"
    },
    "subjectDatasetKey": 1140,
    "subject": {
      "name": "Lycopodiopsida",
      "rank": "class"
    },
    "mode": "attach"
  },
  {
    "created": "2019-10-13T10:55:28.106141",
    "createdBy": 0,
    "modified": "2019-11-05T20:23:06.819247",
    "modifiedBy": 0,
    "key": 2729,
    "datasetKey": 3,
    "target": {
      "id": "bfb709db-491c-48b6-80f5-32ef14f63e4f",
      "name": "Tracheophyta",
      "rank": "phylum"
    },
    "subjectDatasetKey": 1140,
    "subject": {
      "name": "Polypodiopsida",
      "rank": "class"
    },
    "mode": "attach"
  }
]
```

Doing a rematch fixed the issue:

```JSON
POST http://api-dev.col.plus/assembly/3/rematch
{"sectorKey":2728}
```

```JSON
GET https://api-dev.col.plus/sector/broken?datasetKey=1140
[
  {
    "created": "2019-10-13T10:55:28.106141",
    "createdBy": 0,
    "modified": "2019-11-05T20:23:06.819247",
    "modifiedBy": 0,
    "key": 2729,
    "datasetKey": 3,
    "target": {
      "id": "bfb709db-491c-48b6-80f5-32ef14f63e4f",
      "name": "Tracheophyta",
      "rank": "phylum"
    },
    "subjectDatasetKey": 1140,
    "subject": {
      "name": "Polypodiopsida",
      "rank": "class"
    },
    "mode": "attach"
  }
]
```

![image](https://user-images.githubusercontent.com/8573609/68244118-bd465500-ffd9-11e9-8d89-39d46ff821ee.png)

The same approach worked for the Polypodiopsida broken sector. So maybe the backend just needs to do a rematch on any dataset sectors after importing?

**Comment by gdower** [comment]
@mdoering, we're hitting this bug again with Scarabs but it's a more extreme case because the sector doesn't show up even after importing it 2-3 times. It shows up as a [broken sector](https://data.catalogue.life/sector/broken), but rematch doesn't work.

**Comment by gdower** [comment]
The sector is showing as the state `preparing` which probably has something to do with it, although I don't think it is actually `preparing`.

![image](https://user-images.githubusercontent.com/8573609/69568424-2ee24500-0f81-11ea-95b2-1b1ead02ad63.png)

When I clicked stop sync, a blank pop-up appeared and nothing happened. [There is a frontend issue open on that already.](https://github.com/Sp2000/colplus-frontend/issues/342) The stop sync button sends `DELETE https://api.catalogue.life/assembly/3/sync/3113` and gets a 204 response.

**Comment by mdoering** [comment]
Ill investigate tomorrow. But when I imported all datasets I did not have a single problem. All sectors were fine. And also synced wirhout error. Sth else must be going on

**Comment by mdoering** [comment]
do you sync broken sectors?

**Comment by gdower** [comment]
Maybe @yroskov did sync while it was still importing, or maybe the sector was still broken because the dataset hadn't been imported twice.

For now, we'll delete the broken sector and re-register it so that we can produce an ac-export to test conversion.

**Comment by mdoering** [comment]
also rematching on purpose does not work if its an ambiguous match. We need to think what to do in such cases.

**Comment by gdower** [comment]
Here's the [stacktrace](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AW6jmU0rHCKcR6PFyE1w?_a=(columns:!(level),filters:!(),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))) from the failed sync:

```
java.lang.IllegalArgumentException: Sector 3113 does have a non existing subject SUPERFAMILY Scarabaeoidea for dataset 1027
	at org.col.api.util.ObjectUtils.checkNotNull(ObjectUtils.java:50)
	at org.col.assembly.SectorRunnable.loadSector(SectorRunnable.java:150)
	at org.col.assembly.SectorRunnable.init(SectorRunnable.java:114)
	at org.col.assembly.SectorRunnable.run(SectorRunnable.java:86)
	at org.col.assembly.SectorSync.run(SectorSync.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mdoering** [comment]
that failed sync is very much expected if its a broken sector.

**Comment by mdoering** [comment]
It *should* not be possible to sync a running import or vice versa.

**Comment by gdower** [comment]
I agree, although I am not 100% certain that he synced while it was importing. It might be worthwhile trying to reproduce it. Probably sync shouldn't be allowed for datasets that are importing, although of course we'll try to avoid doing it.

**Comment by mdoering** [comment]
As I said, you should not be able to schedule a sync for a dataset with a running import. Give it a try on dev

**Comment by mdoering** [comment]
after wiping and importing Scarabs for the first time the sector is matched fine.
Trying with world ferns now.

One thing to remember is that imports that fail in between, e.g. during indexing, will likely result in broken sectors & decisions as the re-matching step comes nearly last.

**Comment by mdoering** [comment]
Same for ferns.
I am trying to reimport both, maybe this only happens on subsequent imports...

**Comment by mdoering** [comment]
Aha, it happens on subsequent imports. Interesting.
