### ISSUE TITLE
taxon synonyms missing

### ISSUE THREAD

**Issue by MortenHofft** [Sp2000/colplus-backend#47]
the docs tell me that i should expect an array of synonyms
https://sp2000.github.io/colplus/api/api.html#resource-12

I haven't seen anything but

http://api.col.plus/taxon/1573459/synonyms
```
{
"empty": true
}
```

and

http://api.col.plus/taxon/1573461/synonyms
```
{
"empty": false
}
```

if there are examples where an array is returned it would be nice if the format was the same everytime. it makes it more enyouable to consume. so an epty array if there isn't any. or alternatively an object everytime

**Comment by MortenHofft** [comment]
Similarly I'd expect `http://api.col.plus/name/[key]/synonyms` to be an empty array if there isn't any (I couldn't find an example with no synonyms)

**Comment by mdoering** [comment]
very strange indeed. This is an example that should have synonyms:
http://api.col.plus/taxon/25/synonyms

from dataset5, with these names:
```
        25 |    16208 |           5
        25 |    16207 |           5
        25 |    16209 |           5
        25 |    16206 |           5
        25 |    16205 |           5
        25 |    15399 |           5
```
