### ISSUE TITLE
natural_keys discussion

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#470]
ConversionTool creates natural_keys for taxa by hashing the scientific names and author strings, which is used to create the URLs for the AC_Interface web portal:

http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/[ac_plus._natural_keys.hash]

For example:

http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/e0c1915041ce81c166f1521c0e6bcac2

CoL+ improves the formatting of the author_strings, which changes the natural_key hashes. It's okay if the natural_keys are different between editions if the name_code system is preserved. That way I'll be able to get the 2 natural_keys needed to run the col-diff-tool, along with other name_code join queries between editions.

Currently in ac-export.zip the name_codes have been changed to the colplus name usage IDs, which will have no affect on the natural_keys (without modifications to ConversionTool by @ruud-altenburg) but will break name_code joins between the ac_latest and ac_plus which will make it very difficult and time consuming to test the data between the 2019 annual edition and the new monthly CoL+ edition. name_code is not publicly exposed and is intended to be primarily used for data assembly and data testing, so I don't see much benefit to changing the name_codes and especially not while we're still testing data between editions.

My proposal is to keep the name_codes as they were originally in the 2019 annual edition and instead add the colplus name usage ID to ac-export.zip in the scientific_names table as an additional column. @ruud-altenburg could use the colplus name usage ID as the natural_key, which will also be beneficial because CoL+ will be able to directly link to the old web portal from the clearinghouse with the colplus name usage ID.

http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/[colplus.name_usage_3.id]

It's not a problem if the natural_keys don't match between editions, but we need to preserve the name_code IDs as they were.

**Comment by ruud-altenburg** [comment]
Actually this issue isn't discussing natural keys, it's discussing name codes. For the current CoL, the name codes (original id in database prefixed with a code of the GSD) are largely irrelevant. I don't think they are exposed anywhere other than in the DwCA export. @gdower if you need to use the "old" name codes, you can use them in the CoL+ export.

The current CoL uses natural keys. Previously, the CoL used the database ids in its urls. As these changed monthly, the urls to species were never fixed. The discussion about how to fix this and what should be used instead continued for years, without any results. The natural key is an md5 hash of a combination of name characters that I personally chose. It may not be perfect but it's better than what we had!

When the current CoL is finally laid to rest, there will be issues with urls to species. I figured that as an "in-between" option, the monthly edition based on the CoL+ could switch to the "colplus.name_usage_3.id". This way we could provide redirecting from the old CoL to CoL+. I guess this is still perfectly feasible for accepted names. Synonyms and common names, however, have their own natural keys. E.g.

http://www.catalogueoflife.org/col/details/species/id/253bb4ac5026b77a3adf9b78516913b9/common/d4f93ced0a1c49266ef6a4c808f19820

So my questions was if it would be worth switching keys if the effort we could only provide partial redirection.

**Comment by mdoering** [comment]
OK, there seems to be 2 issues intermixed here:

1) stable CoL+ IDs which should be exposed in the API and legacy portal so they get picked up by users. This is a requirement for example to engage with the EEA as soon as possible. For this to work the natural keys should be replaced by the CoL+ usage keys. @ruud-altenburg is this doable in the ConversionTool?

2) offer a way to relate and diff two names from the previous catalogue and the newly generated one via CoL+. For this @gdower wants to use the name_codes which do not exist in the CoL+ (draft) catalogue. The codes are also only unique in the context of a GSD.

Proposal:
 - use CoL+ usage ids in the export and reuse them in the portal switching off natural key hashing
 - add a new field for the old name_codes in the export purely for the purpose of accessing the new data with the old ids for diffing.

**Comment by ruud-altenburg** [comment]
We don't necessarily have to use both simultaneously, do we? We can switch back to the original name codes when testing differences. Once these have been fixed, we can use the usage keys as name codes.

This still doesn't address the problem that CoL+ synonyms and common names do not have unique usage ids.

**Comment by mdoering** [comment]
Synonyms and common names do have unique ids, but maybe not in the export? What would you expect?

**Comment by mdoering** [comment]
One other note. We already have 2 key systems in the export: `record_id` and `name_code` again referenced sometimes as `family_code` or `family_id` and similar fields. Are both really needed?

**Comment by ruud-altenburg** [comment]
If we have the unique ids, we can try to create a redirection service. The unique ids of synonyms are already in the export, apologies for overlooking those! If we would add an extra column to common_names, we could use the ids of those as well.

**Comment by ruud-altenburg** [comment]
> One other note. We already have 2 key systems in the export: `record_id` and `name_code` again referenced sometimes as `family_code` or `family_id` and similar fields. Are both really needed?

These are an artefact of the ACEF format. Be glad you can have a fresh start and remove all that redundant stuff :)

**Comment by mdoering** [comment]
common_names.record_id is just an integer sequence generator.
I don't care much about the common name ids as these are not exposed in the UI - or are they?

**Comment by ruud-altenburg** [comment]
They are in the example in my first reply.

**Comment by mdoering** [comment]
Ah I see. For linking common name searches. I don't think they matter, use whatever keys you got now. The species pages are the ones that need to be linked to persistently

**Comment by ruud-altenburg** [comment]
Right, will do. But first I assume you will revert back to the old name codes to allow @gdower to do his comparisons?

**Comment by mdoering** [comment]
that makes sense but its not trivial at all for me to do that. Don't expect anything to be ready before friday, maybe monday only

**Comment by ruud-altenburg** [comment]
Whenever you have the time Markus. I will add an option so you can chose which keys to use: natural keys or the CoL+ ids.

**Comment by gdower** [comment]
@mdoering and @ruud-altenburg, as you suggested, I wrote some SQL queries to get the URLs without needing the name_codes. I'm going to close this because I think this is resolved.

That provides URLs between the 2 editions for 2014165 species and infraspecies. There's only 1349 CoL+ names that I can't resolve the natural_keys between which is a relatively small amount, and possibly those are names that are still affected by some of the remaining assembly bugs that we're working on fixing.

```SQL

CREATE DATABASE ac_diff DEFAULT CHARSET utf8 COLLATE utf8_general_ci;


DROP TABLE IF EXISTS ac_diff.colplus;
CREATE TABLE ac_diff.colplus
(
    KEY (diff_key)
)
SELECT MD5(CONCAT_WS('_', p8.name, p7.name, p6.name, p5.name, p4.name, p3.name, p2.name, p1.name, tt.name)) diff_key,
       CONCAT_WS('_', p8.name, p7.name, p6.name, p5.name, p4.name, p3.name, p2.name, p1.name, tt.name)      hierarchy,
       p8.name                                                                                              p8,
       p7.name                                                                                              p7,
       p6.name                                                                                              p6,
       p5.name                                                                                              p5,
       p4.name                                                                                              p4,
       p3.name                                                                                              p3,
       p2.name                                                                                              p2,
       p1.name                                                                                              p1,
       tt.name,
       hash,
       concat('http://workbench.catalogueoflife.org/col_plus/details/species/id/', hash)                    url
FROM ac_plus.`_natural_keys` nk
         INNER JOIN ac_plus.`_taxon_tree` tt ON nk.id = tt.taxon_id
         LEFT JOIN ac_plus.`_taxon_tree` p1 ON tt.parent_id = p1.taxon_id
         LEFT JOIN ac_plus.`_taxon_tree` p2 ON p1.parent_id = p2.taxon_id
         LEFT JOIN ac_plus.`_taxon_tree` p3 ON p2.parent_id = p3.taxon_id
         LEFT JOIN ac_plus.`_taxon_tree` p4 ON p3.parent_id = p4.taxon_id
         LEFT JOIN ac_plus.`_taxon_tree` p5 ON p4.parent_id = p5.taxon_id
         LEFT JOIN ac_plus.`_taxon_tree` p6 ON p5.parent_id = p6.taxon_id
         LEFT JOIN ac_plus.`_taxon_tree` p7 ON p6.parent_id = p7.taxon_id
         LEFT JOIN ac_plus.`_taxon_tree` p8 ON p7.parent_id = p8.taxon_id
WHERE status IN (1, 4);


DROP TABLE IF EXISTS ac_diff.ac2019;
CREATE TABLE ac_diff.ac2019
(
    KEY (diff_key)
)
SELECT MD5(CONCAT_WS('_', p8.name, p7.name, p6.name, p5.name, p4.name, p3.name, p2.name, p1.name, tt.name)) diff_key,
       CONCAT_WS('_', p8.name, p7.name, p6.name, p5.name, p4.name, p3.name, p2.name, p1.name, tt.name)      hierarchy,
       p8.name                                                                                              p8,
       p7.name                                                                                              p7,
       p6.name                                                                                              p6,
       p5.name                                                                                              p5,
       p4.name                                                                                              p4,
       p3.name                                                                                              p3,
       p2.name                                                                                              p2,
       p1.name                                                                                              p1,
       tt.name,
       hash,
       concat('http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/', hash)             url
FROM ac_latest.`_natural_keys` nk
         INNER JOIN ac_latest.`_taxon_tree` tt ON nk.id = tt.taxon_id
         LEFT JOIN ac_latest.`_taxon_tree` p1 ON tt.parent_id = p1.taxon_id
         LEFT JOIN ac_latest.`_taxon_tree` p2 ON p1.parent_id = p2.taxon_id
         LEFT JOIN ac_latest.`_taxon_tree` p3 ON p2.parent_id = p3.taxon_id
         LEFT JOIN ac_latest.`_taxon_tree` p4 ON p3.parent_id = p4.taxon_id
         LEFT JOIN ac_latest.`_taxon_tree` p5 ON p4.parent_id = p5.taxon_id
         LEFT JOIN ac_latest.`_taxon_tree` p6 ON p5.parent_id = p6.taxon_id
         LEFT JOIN ac_latest.`_taxon_tree` p7 ON p6.parent_id = p7.taxon_id
         LEFT JOIN ac_latest.`_taxon_tree` p8 ON p7.parent_id = p8.taxon_id
WHERE status IN (1, 4);


DROP TABLE IF EXISTS ac_diff.urls;
CREATE TABLE ac_diff.urls
SELECT minus.diff_key  diff_key,
       minus.hierarchy minus_hierarchy,
       plus.hierarchy  plus_hierarchy,
       minus.url       minus_url,
       plus.url        plus_url,
       minus.hash      minus_hash,
       plus.hash       plus_hash,
       minus.name      minus_name,
       plus.name       plus_name
FROM ac_diff.ac2019 minus
         INNER JOIN ac_diff.colplus plus ON minus.diff_key = plus.diff_key;

# 1349 hits
SELECT * FROM ac_diff.colplus plus LEFT JOIN ac_diff.ac2019 minus ON plus.diff_key = minus.diff_key WHERE minus.url IS NULL;

# 0 hits
SELECT * FROM ac_diff.ac2019 minus LEFT JOIN ac_diff.colplus plus ON plus.diff_key = minus.diff_key WHERE minus.url IS NULL;
```

**Comment by mdoering** [comment]
Good! If you could dump those non matching 1349 names in a list with links to them it might be worthwhile looking at them manually

**Comment by gdower** [comment]
Yeah, @yroskov and I are reviewing those now. I added to the [issues spreadsheet](https://docs.google.com/spreadsheets/d/1BC0O5-zCJ7Ndl1SNUcZS2lPy1yT-jVAi-XzozzV-nzg/edit?usp=sharing) as col_diff_misses. A lot of the names are present in AC2019, so probably I need to do some adjustments to the queries to eliminate some subtle differences between the hierarchy codes.

**Comment by yroskov** [comment]
So far, the only really missing set of infraspecific taxa from Geoff's list is from World Ferns, such as  
Asplenium helii subsp. alberti-nieschalkii
Asplenium helii subsp. helii
Asplenium helii subsp. lainzii
Asplenium javorkae subsp. afghanicum
Asplenium javorkae subsp. javorkae
Asplenium javorkae subsp. eglii

I do not think, it is a priority for now.

**Comment by mdoering** [comment]
The Asplenium names are imported into the Clearinghouse, e.g. [Asplenium helii alberti-nieschalkii Bennert, Pic.Serm., Rasbach, K.Rasbach & Reichst.](https://dev.col.plus/dataset/1140/taxon/7043)
