### ISSUE TITLE
Setup production hosting

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#472]
Update the prod CoL+ installation to be ready for going public with data being properly maintained.

- [x] setup prod db on ector
    - [x] replication backup
    - [x] migrate data from db.col.plus/colplus
- [x] setup prod col-ws app
    - [x] backup metrics & images folder (220MB right now, up to 3 GB over the next year)
    - [x] logstash
- [x] setup ES server

**Comment by MattBlissett** [comment]
The two current VMs, coldb-vh.col.plus and colapps-vh.col.plus, are temporary before a proper infrastructure is setup.

### Databases — PostgreSQL.

Please create new users and databases on pg1.gbif.org and pg1.gbif-dev.org.  I'd like them to be prefixed, e.g. `prod_col` or `prod_colplus` etc.  It's best if the user owning the database isn't the usual user for database access by the web service etc.  Please don't reuse the same password on both environments.

The pg1.gbif.org database will then be streaming-replicated onto pg2.gbif.org, and the write-ahead logs streamed to a different server. Weekly full physical dumps are archived to a KU system.  We can do point-in-time recovery to any point. (Dev isn't replicated.)

This does tie CoL+ into the same PostgreSQL version as for other GBIF services.

### Elasticsearch

I don't want us to tie this to the GBIF occurrence index. Version changes are much more disruptive than for PostgreSQL, and we don't really know how the new ES cluster will behave. It may disrupt a CoL hosted together with it, or _vice versa_.

I will set up new VMs for Elastic Search instances, one per environment. Unlike the test VM, they will have a separate partition for the ES index, so it's easier to grow that as required. The current use at /var/lib/elasticsearch is 25GB, what would be reasonable for new servers?

### Production filesystem

Does this refer to `/home/col` and `/var/www/html` on colapps-vh? Or to the NFS storage, `/mnt/auto/misc`?

The server looks to be running two Java webservices, one for dev and one for prod.  I should make two VMs, one for each environment, to run the webservices and Apache.

Data can be stored on either NFS or the VM, but VMs images aren't backed up by default — if necessary, we'd just restore them from Ansible scripts etc. Parts of the filesystem can be backed up if necessary.

**Comment by mdoering** [comment]
with filesystem I did not refer to the entire image but just the data we store there, i.e images, archives (which we may want to ignore) and especially metrics and change diffs which we cannot regenerate otherwise. I need to lookup the exact paths. they should be under /home/col

**Comment by mdoering** [comment]
using pg1 for the db should je ok. But I am slightly scared about the replication being a bottleneck. Remember clb brought down the server before? On the other hand clb will be gone in the future at some point so its not a huge load increase. we should try this out soon, I will setup the db as you mentioned

**Comment by MattBlissett** [comment]
The new servers have 2×10Gb/s connections to each other and to the destination for WALs, and a RAID5 of NVMe storage, so I'm much less concerned about the load.

**Comment by mdoering** [comment]
The data on the filesystem that needs backup is currently under `/home/col/bin/prod`:

```
colapps-vh ~/bin/prod $ du -sh *
4.0K	config-cli.yml
4.0K	config-ws.yml
0	images
12M	logs
2.8G	metrics
764M	namesindex
0	scratch
175M	ws-server.jar
```

From those  `images` and `metrics` are unreplaceable. The namesindex can be rebuilt from postgres data. All of these should be rather quick to access.

Data archives downloaded for indexing are kept on NFS at `/mnt/auto/misc/col/prod/archive` and do not need backups.

It is hard to prognose the rise of especially the metrics folder as its archiving stats about each dataset import and sector sync so we can diff them retrospectively. Images are nearly only logos, so thats not gonna grow large. Most of the metrics data is stored in plain text and could be compressed considerably if metrics size becomes a problem. But it is served straight through the API, so it needs to be readily available.

**Comment by mdoering** [comment]
ELASTIC

Current ES prod node contains 15G, excluding any GBIF checklists & Plazi. 
I would expect that we can grow that to 30-50G over the next year with the above added. We could try that out on the current setup, but I assume we'll reach the storage limits

**Comment by mdoering** [comment]
Postgres takes up 45g and I would expect we will grow to 60-100 over the next year for a single database.

Elastic is down to 10G and would mount to 25G in this scenario.

We do see strange spikes in disk use though which I cannot explain yet:

![graph](https://user-images.githubusercontent.com/327505/65750109-dcfb7b00-e107-11e9-8dcf-3475684d1a0e.png)

**Comment by mdoering** [comment]
blocked by #498

**Comment by mdoering** [comment]
Decision today is to use Ector as a new PG12 (just released) db server and isolate it from the existing GBIF infrastructure.

**Comment by mdoering** [comment]
as for the `metrics` folder that needs backed up I added gzip compression to it so it should be considerably smaller now.

**Comment by MattBlissett** [comment]
I'm working through and will continue tomorrow:

* ector as PostgreSQL and ElasticSearch (unless you think otherwise) host, with LVM 
on the disk so we can allocate the remaining space as we need it.
* I'll make a VM for a development PG12 database
* I'll back them up using the streaming replication we use (via barman) for GBIF's production DBs
* I'll make new VMs for the apps servers (dev + prod) and back up selected directories; I can see the configuration allows a good choice of where things will be.  I don't think we need any NFS access on these.

**Comment by mdoering** [comment]
Can we use barman for log shipping from a PG12 server?
> log shipping between servers running different major PostgreSQL release levels is not possible

**Comment by mdoering** [comment]
We'd also use the latest ES, 7.4.2 in that setup please

**Comment by mdoering** [comment]
see https://github.com/Sp2000/colplus/issues/65 for a more public prod domain discussion.
If www is taken by the main portal still to be developed I wonder where we best expose the Clearinghouse/Assembly tools. We could share the main domain with the portal and use a base root like `https://www.catalogue.life/ch` but I would prefer to have a dedicated subdomain.

I suggest we use these domains at this stage:
**PROD**
 - https://www.catalogue.life -> reserved for the new portal
 - https://ch.catalogue.life -> Clearinghouse, currently www.col.plus
 - https://api.catalogue.life -> API
 - https://pg1.catalogue.life -> Postgres and ES server (not public)

**DEV**
Uses `dev.catalogue.life` as the base with otherwise the same mapping as above:
 - https://www.dev.catalogue.life -> reserved for the new portal
 - https://ch.dev.catalogue.life -> Clearinghouse, currently www.col.plus
 - https://api.dev.catalogue.life -> API
 - https://pg1.dev.catalogue.life -> Postgres and ES server (not public)

Or should we stick with col.plus for dev?

**Comment by yroskov** [comment]
_Agree:_    https://www.catalogue.life -> reserved for the new portal
_Two letters "ch" for "clearinghouse" is not a good idea; it is more associated in user's mind with "China" in URLs (regardless of its position in the tail, head or body of the URL_:  https://ch.catalogue.life -> Clearinghouse, currently www.col.plus
_Agree:_    https://api.catalogue.life -> API
_Neutral:_    https://pg1.catalogue.life -> Postgres and ES server (not public)

I prefer **col.plus** for all code developments.

**Comment by mdoering** [comment]
I agree with `ch` being not great. Any other idea? 
We could continue to use col.plus for developments, but its the name of the project that is running out now, so Im not sure it's fine to continue with that. @olafbanki your cents on continuing the col.plus domain? Generally it is a great short name.

**Comment by yroskov** [comment]
Any kind of development is "plus". If CoL+ as a project name will be forgotten, col.plus domain might be still positively used for further developments.

**Comment by MattBlissett** [comment]
coldevapps-vh.catalogue.life (apps.dev.catalogue.life)
colprodapps-vh.catalogue.life (apps.catalogue.life)

These now exist. I haven't added NFS, so temporary things can go in /home/col/... and things to be backed up can go in /srv (which is the expected place for that kind of thing). Only the production /srv will be backed up.

Have a look at the disk sizes, RAM, CPU etc.  I've tried to guess based on current usage, ganglia etc. It's easiest to change the disk before the VM is in use (can just destroy and regenerate), RAM and CPU require a reboot to change.

We can register an additional name if you'd prefer not to use *.dev.catalogue.life and also want to move away from col.plus, although catalogue-dev.life (in the same pattern as gbif-dev.org) doesn't exactly roll off the tongue.

**Comment by mdoering** [comment]
@MattBlissett can we also map api.catalogue.life and api.dev.catalogue.life to the apps VMs to expose them to the public on port 80 and 443/ssl ? We currently use Apache, maybe Varnish at some stage. Or do you prefer a dedicated VM for that?

**Comment by MattBlissett** [comment]
I think these are both ready already, but there is nothing listening on the server.

Apache is probably used at the moment because you're also serving files (/download) which is not possible in Varnish.  Either way, I will set it up (including TLS) with Ansible.

**Comment by olafbanki** [comment]
"@olafbanki your cents on continuing the col.plus domain? Generally it is a great short name."
I like catalogue.life in general a better url than catalogueoflife.org although we should for historical reason keep the latter url as well. Have you considered col.life as an even shorter one? I have no objections keeping col.plus for development if that is useful. We will certainly have a second phase of the project. Col.tec if available would also work for me.

**Comment by mdoering** [comment]
Most 3 letter domains are [taken](https://www.namemesh.com/domain-name-search/col?show=1) including col.org. For `col` the only ones that are free and make some sense are:
 - col.science
 - col.sc
 - col.site

**Comment by dhobern** [comment]
I think catalogue.life really nicely and succinctly says what we are as well as being simple. col.life is less clear and redundant (life.life).

**Comment by yroskov** [comment]
Don't see any reasons to change domain name. catalogue.life - easier to remember then catalogueoflife.org? shorter? better address a subject area? what?
catalogueoflife.org is cited in thousands of publications and website. Thousands of users know it a home for the Catalogue of Life.

**Comment by yroskov** [comment]
Decision to change domain name for well known product should not be "in-house" decision by shadow cabinet. It must be consulted with data providers and users.

**Comment by MattBlissett** [comment]
The `/srv` directory on colprodapps-vh.catalogue.life is now backed up.

(I used catalogue.life as it's a domain registered by GBIF, and I need to have full control over the domain used internally for servers.  This needn't affect anything visible to the public.)

**Comment by mdoering** [comment]
Decided to go with the following until the global team decides differently:

**PROD**
 - https://www.catalogue.life -> reserved for the new portal
 - https://data.catalogue.life -> Clearinghouse, currently www.col.plus
 - https://api.catalogue.life -> API

**DEV**
 - https://www.dev.catalogue.life -> reserved for the new portal
 - https://data.dev.catalogue.life -> Clearinghouse, currently dev.col.plus
 - https://api.dev.catalogue.life -> API
