### ISSUE TITLE
inc. sed. species sometimes not placed correctly in ac-export.zip

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#477]
In [investigating the mismatch in URL natural_keys between CoL editions](https://github.com/Sp2000/colplus-repo/issues/60), it appears that  inc. sed. species might be getting placed incorrectly in the taxonomic classification in [CoL+](https://www.col.plus/dataset/1200/taxon/942802) and ac-export.zip:

diff_key | hierarchy | p8 | p7 | p6 | p5 | p4 | p3 | p2 | p1 | name | hash | url
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
e22ccb1be7cfa9842320c78e2a524153 | Animalia_Arthropoda_Diplopoda_Polydesmida_Trichopolydesmoidea_Not assigned_Moojenodesmus_Moojenodesmus irmgardae |   | Animalia | Arthropoda | Diplopoda | Polydesmida | Trichopolydesmoidea | Not assigned | Moojenodesmus | Moojenodesmus irmgardae | 2abae75bb571644054fadbfd78b731fa | http://workbench.catalogueoflife.org/col_plus/details/species/id/2abae75bb571644054fadbfd78b731fa
5699c23906721e3b6ae2d7ea577b115d | Animalia_Arthropoda_Diplopoda_Polydesmida_Not assigned_Moojenodesmus_Moojenodesmus irmgardae |   |   | Animalia | Arthropoda | Diplopoda | Polydesmida | Not assigned | Moojenodesmus | Moojenodesmus irmgardae | 2abae75bb571644054fadbfd78b731fa | http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/2abae75bb571644054fadbfd78b731fa

Here's the verbatim data from [ACEF](https://github.com/Sp2000/colplus-repo/blob/master/ACEF/200.tar.gz?raw=true) file, which matches the classification for the 2019 annual edition:
```
"993171"	"Animalia"	"Arthropoda"	"Diplopoda"	"Polydesmida"	""	"Not assigned"	"Asphalidesmus"	""	"golovatchi"	"Mesibov, 2009"	""	"accepted name"	"0"	"0"	"1"	"terrestrial"	""	"Mesibov, Robert"	"2017-05-27"	"http://www.millibase.org/aphia.php?p=taxdetails&id=993171"	""	"urn:lsid:marinespecies.org:taxname:993171"
```

Here's the scientific_names entry from ac-export.zip with family code **inc.sed-325**:

```
716893,286ed035-8e6e-4f1f-8d60-72bc8111137c,http://www.millibase.org/aphia.php?p=taxdetails&id=993171,Asphalidesmus,\N,golovatchi,\N,\N,\N,"Mesibov, 2009",286ed035-8e6e-4f1f-8d60-72bc8111137c,\N,2017-05-27,1,200,1390,3896670,\N,inc.sed-325,1,\N,\N,\N,0,1
```

And the incorrect taxonomic placement in families.csv:

```
3896670,\N,Animalia,Arthropoda,Diplopoda,Polydesmida,Not assigned,Trichopolydesmoidea,200,inc.sed-325,1
```

**Comment by mdoering** [comment]
@gdower can you please always clearly state which ID & name is effected where (clearinghouse, draft col, ac-export)? I find it hard to understand the issue.

**Comment by mdoering** [comment]
Is the issue that `Asphalidesmus golovatchi Mesibov, 2009` has an additional superfamily _Trichopolydesmoidea_ which isnt present in the original ACEF?

**Comment by mdoering** [comment]
superfamily is indeed wrongly copied from some other name with also an "Not assigned" family.

**Comment by mdoering** [comment]
For data to be fixed this needs a reimport into the ClearingHouse with code from today

**Comment by gdower** [comment]
> @gdower can you please always clearly state **which** ID & name is effected **where** (clearinghouse, draft col, ac-export) with **what** kind of a problem? I find it hard to understand the issue.

@mdoering, I checked and I provided you with IDs, names affected, the locations in the data flow of the problems, and that it was a problem with inc. sed. name placement. Clarity might have suffered a bit because I found this issue at the end of my workday and I was racing to get this ticket opened so that you could possibly fix it during your workday. I'll try to be clearer, but frankly these issues are often complex and it might still take some time to digest and understand the issue even when it is well described.

**Comment by mdoering** [comment]
Yes, all infos were there. Just took me a while to figure out that superfamily in the Clearinghouse was the problem. Or was there sth else?

**Comment by gdower** [comment]
If there's more than 1 inc. sed. family in a sector, I think the normalizer might place the names in the wrong inc. sed. family because it might not be checking the full classification hierarchy and just assigns the name to the first "Not assigned" group it finds. Alternatively, the normalizer might consolidate all names in "Not assigned" groups into one "Not assigned" group with a lot being placed in the wrong location in the classification hierarchy. Does that make sense?

**Comment by mdoering** [comment]
Yes, it just compares the classification for higher ranks with real names, not placeholders. That leads to the superfamily being ignored in this case. Fixed now with [real test data](https://github.com/Sp2000/colplus-backend/blob/master/colplus-ws/src/test/resources/acef/21/AcceptedSpecies.tsv).

**Comment by gdower** [comment]
Awesome, thanks!
