### ISSUE TITLE
Bacteria, Chromista and Plantae trinomials are getting assigned an infrasp. marker

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#478]
Bacteria, Chromista and Plantae trinomials are being assigned the infraspecies marker, "infrasp.," which shouldn't be used as a marker because infraspecies is a generic term. This might be a code-specific bug because it doesn't affect zoological trinomials.

diff_key | hierarchy | p8 | p7 | p6 | p5 | p4 | p3 | p2 | p1 | name | hash | url
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2dcfb8c6aaccaeafda8377dde0ed8d57 | Bacteria_Cyanobacteria_Cyanophyceae_Nostocales_Oscillatoriaceae_Spirulina_Spirulina subsalsa_Spirulina subsalsa infrasp. subsalsa |   | Bacteria | Cyanobacteria | Cyanophyceae | Nostocales | Oscillatoriaceae | Spirulina | Spirulina subsalsa | Spirulina subsalsa infrasp. subsalsa | a0a65ef2280ace909199aad702e82619 | http://workbench.catalogueoflife.org/col_plus/details/species/id/a0a65ef2280ace909199aad702e82619
1af233132eb786bff78398b3197a9144 | Bacteria_Cyanobacteria_Cyanophyceae_Nostocales_Oscillatoriaceae_Spirulina_Spirulina subsalsa_Spirulina subsalsa subsalsa |   | Bacteria | Cyanobacteria | Cyanophyceae | Nostocales | Oscillatoriaceae | Spirulina | Spirulina subsalsa | Spirulina subsalsa subsalsa | 2a0e960881689be471ff59ab3bc173fd | http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/2a0e960881689be471ff59ab3bc173fd

Bug found in: https://github.com/Sp2000/colplus-repo/issues/60

**Comment by mdoering** [comment]
where does this show up? I cannot find the marker in the clearinghouse nor draft catalogue, it looks fine to me: https://www.col.plus/dataset/3/taxon/586c3737-2e91-40da-aaf1-aa3a0a945a05

**Comment by gdower** [comment]
It's in scientific_names.csv of ac-export.zip:

23688,a754cd45-23e7-4ebf-9721-e9201b9fd243,http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=1057, Spirulina,\N,subsalsa,ff3c9027-d693-4d25-b867-afec408f6fa6,subsalsa,**infrasp.**,,a754cd45-23e7-4ebf-9721-e9201b9fd243,\N,2015-03-02,1,115,\N,1851,\N,42ff70c5-bd1f-492d-b9d1-a54997ea7103,1,\N,\N,0,0,0
23689,586c3737-2e91-40da-aaf1-aa3a0a945a05,http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=1056, Spirulina,\N,subsalsa,ff3c9027-d693-4d25-b867-afec408f6fa6,oceanica,**infrasp.**,,586c3737-2e91-40da-aaf1-aa3a0a945a05,\N,2015-03-02,1,115,\N,1851,\N,42ff70c5-bd1f-492d-b9d1-a54997ea7103,1,\N,\N,0,0,0

You can also see it in the AC_Interface search, but not on the taxa pages:

http://workbench.catalogueoflife.org/col_plus/search/all/key/Spirulina+subsalsa+subsalsa/fossil/1/match/1

(AC_Interface removes the infraspecies marker from taxon pages for zoological infraspecies, and it's probably a AC_Interface bug that it's showing infraspecies markers for zoological species in search.)

**Comment by mdoering** [comment]
was it exported from the current prod draft catalogue? The current draft does not seem to have the same problem

**Comment by gdower** [comment]
Yeah, I pulled those two lines above from the latest ac-export.zip with:

```
grep "Spirulina" scientific_names.csv | grep subsalsa | grep infrasp\.
```

**Comment by mdoering** [comment]
mind if I reexport the current prod draft to see if it still is the case?

**Comment by gdower** [comment]
Go ahead.

**Comment by mdoering** [comment]
Ah, now I got it. The rank marker is exported in the ranks field. I was thinking it is part of the full name which is isn't. The CoL interface assembles the rank into the name. 

I will exclude all ranks of that type in the export.
