### ISSUE TITLE
org.elasticsearch.client.ResponseException URI 403 forbidden

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#479]
We hit a new elasticsearch bug when trying to re-import a dataset with a broken sector. Here's the [Kibana logs](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AW07ucNfHCKcR6PFPGe5?_a=(columns:!(_source),filters:!(),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1h,mode:quick,to:now))).

```
org.elasticsearch.client.ResponseException: method [POST], host [http://db.col.plus:9200], URI [prod-nu/_doc/_delete_by_query], status line [HTTP/1.1 403 Forbidden] {"took":58,"timed_out":false,"total":30067,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[{"index":"prod-nu","type":"_doc","id":"FOoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"FeoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"FuoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"F-oWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"GOoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"GeoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"GuoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"G-oWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"HOoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"HeoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"HuoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"H-oWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"IOoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-nu","type":"_doc","id":"IeoWO20BlW4uXqVNCS9N","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403},{"index":"prod-
```

Versions:
Frontend version: 6cecadb September 12, 2019 4:43 AM
Backend version: eaf65f9 September 16, 2019 11:02 AM

**Comment by gdower** [comment]
I'm not sure if this will be reproducible, so I'm closing this and will re-open it if we hit it again.

**Comment by gdower** [comment]
This is reproducible and rebooting wouldn't fix it.

**Comment by gdower** [comment]
[Here's the process](https://github.com/Sp2000/colplus-repo/issues/65#issuecomment-531957528) @yroskov and I followed that resulted in the ES 403 error. Before we hit this bug, a few syncs failed on sector 4488. If the sector sync updates the ES index, my thought is that maybe it was left in a read only state when the sector sync failed, and now it's giving a forbidden error when trying to write to ES. Here's the logs from the failed syncs: [1](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:4488),query:(match:(sector:(query:4488,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:1),query:(match:(attempt:(query:1,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))), [2](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:4488),query:(match:(sector:(query:4488,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:2),query:(match:(attempt:(query:2,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))).

It looks like the restart.sh script might only restart the backend.

**Comment by gdower** [comment]
[This](https://techoverflow.net/2019/04/17/how-to-fix-elasticsearch-forbidden-12-index-read-only-allow-delete-api/) might fix it.

**Comment by mdoering** [comment]
we have about 50% left, that doesn't seem to be the source of the problem. But maybe it indeed has to do with syncs now properly writing to ES

**Comment by mdoering** [comment]
Elastic logs indeed indicate a "high disk watermark" above 90% which is then causing the above problem:

``` 
[2019-09-16T22:16:46,664][WARN ][o.e.c.r.a.DiskThresholdMonitor] [coldb-vh.col.plus] flood stage disk watermark [95%] exceeded on [Zv4gm3xXQhCAefB3FwZCNg][coldb-vh.col.plus][/var/lib/elasticsearch/nodes/0] free: 6.8gb[4.9%], all indices on this node will be marked 
```

**Comment by mdoering** [comment]
The issue right now is that ES entered readonly mode for its only node

**Comment by mdoering** [comment]
I enabled the readonly ES node again with:

`curl -X PUT "http://db.col.plus:9200/*/_settings" -H 'Content-Type: application/json' -d'{"index.blocks.read_only_allow_delete": null}'
`

see https://stackoverflow.com/questions/38735514/elasticsearch-entered-read-only-mode-node-cannot-be-altered

**Comment by mdoering** [comment]
still getting this error on dev. We need to find out what is using the space and increase disk space for elastic - hopefully we dont need SSD space there

**Comment by mdoering** [comment]
Or maybe better migrate the index to the GBIF ES cluster, need to check for versions and what we need to run the client against the cluster

**Comment by ayco-at-naturalis** [comment]
WIll look into it

**Comment by mdoering** [comment]
it is postgres: https://github.com/Sp2000/colplus-backend/issues/498
