### ISSUE TITLE
Online resources missing for some GSDs

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#480]
For some GSDs with online resources, the [links are missing](http://ower.org/col_diff/diff.php?id=4e03b1d2fd581378fda62daea5c0b684):

![image](https://user-images.githubusercontent.com/8573609/65079112-0c6df300-d964-11e9-853d-bdbd1e90453c.png)

The URL is [present in the verbatim data](https://www.col.plus/dataset/1028/taxon/174124) in the CoL+ clearinghouse, but it's missing in the clearinghouse [name source URL](https://www.col.plus/dataset/1028/name/174124), and the ac-export.zip:

web_site is the 3rd column which is a \N:
```
grep Puccinia scientific_names.csv | grep burmeisteri 
117374,d352a740-6ed4-47fa-932c-6ad2c2d27bf6,\N,Puccinia,\N,burmeisteri,\N,\N,\N,"Speg., 1898",d352a740-6ed4-47fa-932c-6ad2c2d27bf6,\N,2017-10-27,1,28,1372,71481,\N,6f94f6a0-c3b1-4e63-a729-34f860ac104c,1,\N,\N,0,0,0
```

Some GSDs still have their online resource links: 

http://ower.org/col_diff/diff.php?id=a5bdb0fc6b5f64f084b136deb24bb918

@mdoering, [maybe you are checking the URLs to see if they are valid](https://github.com/Sp2000/colplus-backend/issues/287)? I don't see a [broken link issue](https://www.col.plus/dataset/1028/issues) though.

Possibly it's caused by the space in the URL?

"http://www.speciesfungorum.org/Names/SynSpecies.asp?RecordID=Puccinia burmeisteri"

**Comment by mdoering** [comment]
The ACEF speciesURL should be on the taxon/synonym, not the name.
But the URL fails to parse into a URI object. 2 bugs at once:

1) URI parser fails to handle unescaped whitespace which is strictly an invalid URL but should obviously be gracefully handled

2) no issue is logged in the verbatim as the parser fails to throw UnparsableException
