### ISSUE TITLE
Clearinghouse is parsing author names with given and middle initials into 2 authors

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#486]
In the CoL+ Clearinghouse, [author strings with given and middle name initials are getting parsed into 2 authors.](https://github.com/Sp2000/colplus-repo/issues/66#issuecomment-532833233)

Here's one example for _Physomerinus septemfoveolatus_ where [Schaufuss, L. W. got switched by CoL+ to Schaufuss & L.W](http://www.ower.org/col_diff/diff.php?id=d8200fd32d93675ef8e65565fce3548b):

![image](https://user-images.githubusercontent.com/8573609/65182035-02acc400-da26-11e9-870d-2322a998e850.png)

Here's the [name in the Clearinghouse where the verbatim author string for the name is correct, the interpreted authorship is incorrect, but the basionym authorship is correct](https://www.col.plus/dataset/1204/name/Physomerinus_septemfoveolatus):

![image](https://user-images.githubusercontent.com/8573609/65182359-c168e400-da26-11e9-9e09-3e0fd69d8669.png)

**Comment by mdoering** [comment]
Yes, this is indeed a known problem with [name parsing](https://github.com/gbif/name-parser/issues). I thought it was solved, but there must be sth wrong, I reopened the ticket. The format "Lastname, Initials" is a rather unusual format

**Comment by mdoering** [comment]
NameParser patched. Note that the canonical authorship will place the initials in front of the surname, so it will be `Physomerinus septemfoveolatus L.W.Schaufuss`

**Comment by mdoering** [comment]
if a year follows this is stll not working:
`Euplectus cavicollis LeConte, J. L., 1878`

**Comment by mdoering** [comment]
it actually is
