### ISSUE TITLE
Proposal for release metadata and full stack versioning

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#489]
For debugging, it's important that we add the versions of the full software stack and data to the AC_Interface. My proposal would be to add a versions page [probably here](http://www.catalogueoflife.org/annual-checklist/2019/info/version) that would include something like this:

Backend version: [84098d9](https://github.com/Sp2000/colplus-backend/commit/84098d9) September 16, 2019 4:07 PM
Frontend version: [b237d7c](https://github.com/Sp2000/colplus-frontend/commit/b237d7c) September 19, 2019 2:27 AM
Data export version: 38dded4 September 16, 2019 9:13 AM†
ConversionTool: [8fa5ffa](https://github.com/Sp2000/ConversionTool/commit/8fa5ffa) September 12, 2019 2:35 AM (September 17, 2019 12:09 AM‡)
AC_Interface version: [2126ab0](https://github.com/Sp2000/AC_Interface/commit/2126ab0) 

† data export version would be the md5sum and creation time of ac-export.zip
‡ datetime conversion was run

This version info could be compacted for display in the AC_Interface footer as below, which would give us the exact versions of software and data used when a user reports a problem:

Version [84098d9-b237d7c-38dded4-8fa5ffa-2126ab0 September 17, 2019 12:09 AM‡](http://www.catalogueoflife.org/annual-checklist/2019/info/version)

Replacing the highlighted version in AC_Interface:

![image](https://user-images.githubusercontent.com/8573609/65261168-40185c80-dacd-11e9-85ca-c24f8b8bbc71.png)

The frontend and backend versions could be passed to AC_Interface via the credits.ini file which would be included inside ac-export.zip, although ConversionTool would have to be modified to add the md5sum hash and the file creation time of ac-export.zip. ConversionTool and AC_Interface can get their own versions with:

```
git rev-list --pretty=format:"%h %ad" --date=format:'%B, %e %-H:%M %p' --max-count=1 `git rev-parse HEAD`
```

Below is a current example of a credits.ini but we could add more lines for including the CoL+ software versions. The citation info could come from the [metadata from the draft release](http://www.col.plus/dataset/3/meta).

```INI
current_edition = "annual" ; monthly/annual/dvd

[monthly]
edition = "2019-09-16" ; date ac-export.zip was generated
citation = "Roskov Y., Ower G., Orrell T., Nicolson D., Bailly N., Kirk P.M., Bourgoin T., DeWalt R.E., Decock W., Nieukerken E. van, Zarucchi J., Penev L., eds. ([year]). Species 2000 & ITIS Catalogue of Life, [edition]. Digital resource at www.catalogueoflife.org/col. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-8858."
frontend_version = b237d7c September 19, 2019 2:27 AM
backend_version = 84098d9 September 16, 2019 4:07 PM

[annual]
edition = "2019" ; 2017
citation = "Roskov Y., Ower G., Orrell T., Nicolson D., Bailly N., Kirk P.M., Bourgoin T., DeWalt R.E., Decock W., Nieukerken E. van, Zarucchi J., Penev L., eds. ([edition]). Species 2000 & ITIS Catalogue of Life, 2019 Annual Checklist. Digital resource at www.catalogueoflife.org/annual-checklist/[edition]. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-884X."

[dvd]
edition = "2019" ; 2017
citation = "Roskov Y., Ower G., Orrell T., Nicolson D., Bailly N., Kirk P.M., Bourgoin T., DeWalt R.E., Decock W., Nieukerken E. van, Zarucchi J., Penev L., eds. ([edition]). Species 2000 & ITIS Catalogue of Life, 2019 Annual Checklist. DVD. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-917X."

```

**Comment by mdoering** [comment]
I like the idea of adding a credits.ini file to the ac-export.zip based on the draft catalogues dataset metadata. We could even take the citation from there.

Do we need to have all 3 categories in the ini file?
It seems we only ever talk about monthly editions now. DVDs are gone and annual releases *should* be done with a new portal.

Knowing the frontend version in the backend is a little complicated though. The only way I can imagine that to work is to pass the frontend version to the backend in the (POST) request by the frontend itself when it triggers the release. @thomasstjerne what do you think?

**Comment by gdower** [comment]
@yroskov and I don't think we need to have those other 2 DVD and annual editions in credits.ini for the current release. The current=1 version info in ac_plus._credits is most important and the other 2 citations as far as I know are just get placed on the [citation page](http://www.catalogueoflife.org/annual-checklist/2018/info/cite). That extra citation info for the annual edition could be added manually to the citation page when we release an annual edition.

### ac_plus._credits ###

id | type | current | edition | citation
-- | -- | -- | -- | --
1 | monthly | 0 | 25th March 2019 | Roskov Y., Ower G., Orrell T., Nicolson D., Bailly N., Kirk P.M., Bourgoin T., DeWalt R.E., Decock W., Nieukerken E. van, Zarucchi J., Penev L., eds. ([year]). Species 2000 & ITIS Catalogue of Life, [edition]. Digital resource at www.catalogueoflife.org/col. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-8858.
2 | annual | 1 | 2019 | Roskov Y., Ower G., Orrell T., Nicolson D., Bailly N., Kirk P.M., Bourgoin T., DeWalt R.E., Decock W., Nieukerken E. van, Zarucchi J., Penev L., eds. ([edition]). Species 2000 & ITIS Catalogue of Life, 2019 Annual Checklist. Digital resource at www.catalogueoflife.org/annual-checklist/[edition]. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-884X.
3 | dvd | 0 | 2019 | Roskov Y., Ower G., Orrell T., Nicolson D., Bailly N., Kirk P.M., Bourgoin T., DeWalt R.E., Decock W., Nieukerken E. van, Zarucchi J., Penev L., eds. ([edition]). Species 2000 & ITIS Catalogue of Life, 2019 Annual Checklist. DVD. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-917X.

**Comment by mdoering** [comment]
mostly superceeded by https://github.com/Sp2000/colplus-backend/issues/545
