### ISSUE TITLE
undocumented search filter on name/search

### ISSUE THREAD

**Issue by MortenHofft** [Sp2000/colplus-backend#49]
http://api.col.plus/name/search?key=1
that shouldn't make a difference according to docs
https://sp2000.github.io/colplus/api/api.html#resource-15

but in reality it only return the item with key=1

**Comment by mdoering** [comment]
I see our NameSearch bean has:
```
 	@QueryParam("key")
	private Integer key;
```

@ayco-at-naturalis do we make use of that key param somewhere? Then please add it to the RAML. Otherwise remove the property

**Comment by ayco-at-naturalis** [comment]
df5a25e2ec4be3d4545d3dd8609992adeab1a2fa

**Comment by ayco-at-naturalis** [comment]
5efe6dd

**Comment by mdoering** [comment]
@ayco-at-naturalis has any code been committed? Its still there

**Comment by ayco-at-naturalis** [comment]
The key parameter has been added to RAML, so it is now a documented feature. Maybe it's a bit odd that key is one of the allowed query parameters for search, that equalize search to get; however, you still get a NameSearchResult back, which is richer than a plain Name.
