### ISSUE TITLE
verbatim should return 404 instead of 204 

### ISSUE THREAD

**Issue by MortenHofft** [Sp2000/colplus-backend#50]
http://api.col.plus/taxon/1573349/verbatim
I don't see any data. Is this only for some taxa?

**Comment by mdoering** [comment]
similar to GBIF CLB verbatim requires "origin=source". This one has "denormed classification"
But it should be a 404, not 204

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-backend/commit/fd7e574778cf44b8894f9a4cf722cb193e247086

https://github.com/Sp2000/colplus-backend/commit/3e2606c9ef5aa5e389469d8414d4a7b79f1b07b5
