### ISSUE TITLE
name search without facets returns error

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#506]
This returns one record as of typing:

https://api-dev.col.plus/dataset/2009/name/search?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=Holophrya

But without the facets we get a 400 error `Collection is empty` which is wrong:
https://api-dev.col.plus/dataset/2009/name/search?limit=50&offset=0&q=Holophrya

**Comment by ayco-at-naturalis** [comment]
Same as #510

**Comment by gdower** [comment]
It's also returning this 400 error when searching CoL draft in assembly. The frontend sends the query:

```JSON
GET https://api.col.plus/dataset/3/name/search?&sortBy=TAXONOMIC&status=accepted&limit=25&offset=0&q=Merostomata
{
  "code": 400,
  "message": "Collection is empty"
}
```

Frontend version: d656d49 October 9, 2019 8:47 AM
Backend version: 31c251f October 13, 2019 5:20 AM

It's not working on dev either, although prod and dev are running the same version:

```JSON
GET https://api-dev.col.plus/dataset/3/name/search?&sortBy=TAXONOMIC&status=accepted&limit=25&offset=0&q=Merostomata
{
  "code": 400,
  "message": "Collection is empty"
}
```

Frontend version: 48492ee October 11, 2019 1:45 PM
Backend version: 31c251f October 13, 2019 5:20 AM

**Comment by mdoering** [comment]
I think @ayco-at-naturalis s fix hasnt been deployed yet. I just did a deploy to both dev and prod, @gdower please check if its still valid!

**Comment by gdower** [comment]
Works in:

Frontend version: 48492ee October 11, 2019 1:45 PM
Backend version: d1b29dd October 14, 2019 3:23 AM
