### ISSUE TITLE
500 when trying to post decision

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#507]
I have posted some with success, but this one failed:
code: 500
message: "There was an error processing your request. It has been logged (ID b80e4c4892dc63bf)."

**Comment by thomasstjerne** [comment]
Had another one.

This was the payLoad:

```
{
  "name": {
    "scientificName": "Skeletonema test"
  },
  "lifezones": [
    
  ],
  "fossil": false,
  "recent": false,
  "mode": "update",
  "subjectDatasetKey": "2009",
  "datasetKey": 3,
  "subject": {
    "id": "120334",
    "name": "Skeletonema sp.",
    "rank": "species"
  }
}

```

**Comment by thomasstjerne** [comment]
Could it be the quoted subjectDatasetKey ?

  "subjectDatasetKey": "2009",

**Comment by mdoering** [comment]
buah, its elastic being on read only again :)
```
org.col.es.EsException: org.elasticsearch.client.ResponseException: method [POST], host [http://db.col.plus:9200], URI [dev-nu/_delete_by_query], status line [HTTP/1.1 403 Forbidden]
{"took":11,"timed_out":false,"total":1,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[{"index":"dev-nu","type":"_doc","id":"wAeBqm0B8_YkYOd5hwcc","cause":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}]}
```
if you can remove the quotes from subjectDatasetKey. I turn on ES again and stop imports

**Comment by mdoering** [comment]
the admin UI button for ES gives me an error:

```
Network Error
HTTP method: PUT

Body:
{"index.blocks.read_only_allow_delete":null}

```

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-backend/issues/498

![graph](https://user-images.githubusercontent.com/327505/66381588-edd6a700-e9b9-11e9-8cd4-d65a937b1fce.png)

**Comment by thomasstjerne** [comment]
I still get the 500, but actually the decisions are there when updating the table. Seems to be only the service that fails

**Comment by mdoering** [comment]
its the ES part that fails, so they are in postgres but not in ES. We are really short on disk space right now, I might have to wipe...
