### ISSUE TITLE
Name search fails on offset param

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#510]
Request failed with status code 400
Cannot parse offset into a known NameSearchParameter

HTTP method: GET

https://api-dev.col.plus/dataset/2050/name/search?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic

**Comment by gdower** [comment]
@mdoering, should I wipe and deploy **dev** to get this bug fix? I could wipe and deploy prod, too.

**Comment by thomasstjerne** [comment]
@gdower please do so (wipe and deploy **dev**)

**Comment by gdower** [comment]
@ayco-at-naturalis, I'm re-opening because of [this](https://github.com/Sp2000/colplus-backend/issues/506#issuecomment-541889892), but perhaps the frontend isn't sending the right request in Assembly search?

**Comment by gdower** [comment]
Works in: 
Frontend version: 48492ee October 11, 2019 1:45 PM
Backend version: d1b29dd October 14, 2019 3:23 AM
