### ISSUE TITLE
Add yaml and plain text as mime-types for proxy dataset uploads

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#521]
Uploading yaml files fails probably because it expects a zip file or octet stream:

![image](https://user-images.githubusercontent.com/8573609/67157009-7a069980-f2eb-11e9-8aa8-926686feb5f4.png)

Here's the request in [Kibana](https://logs.gbif.org/app/kibana#/context/AWyLa2lBHCKcR6PFXu26/logs/AW3oUmgmHCKcR6PFzYOW?_a=(columns:!(_source),filters:!(),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))).

**Comment by mdoering** [comment]
ah yes. That also is the reason for failing plain text uploads, e.g. single plain DwC CSV files
