### ISSUE TITLE
Genera missing in the search

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#523]
Some genera seems to be missing from the search index:

Search for Curculionites gives no results, but goto [Curculionidae](https://www.col.plus/assembly?assemblyTaxonKey=99218ce0-d0de-44a6-ae45-b774036862c6
) and expand children, and the genus is there.

**Comment by gdower** [comment]
Here's the API calls for 2 missing genera:

https://api.col.plus/dataset/3/name/search?&sortBy=TAXONOMIC&status=accepted&limit=25&offset=0&q=Curculionites
https://api.col.plus/dataset/3/name/search?&sortBy=TAXONOMIC&status=accepted&limit=25&offset=0&q=Trifolium

**Comment by mdoering** [comment]
maybe related to #536 ?

**Comment by mdoering** [comment]
was the sector really synced?
