### ISSUE TITLE
Family gets inserted several times in name search

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#525]
After creating several genus sectors under a family in the assembly, that family appears multiple times in the name search for the assembly.

https://api-dev.col.plus/dataset/3/name/search?&sortBy=TAXONOMIC&status=accepted&limit=25&offset=0&q=Cortinariacea

**Comment by mdoering** [comment]
If I create a new family in the assembly tree it never shows up at all in the search :(

**Comment by mdoering** [comment]
@thomasstjerne is that still true? I cannot reproduce

**Comment by mdoering** [comment]
likely a duplicate of #496 ?

**Comment by thomasstjerne** [comment]
> is that still true? I cannot reproduce

Search for Cortinariaceae in the [dev assembly](https://dev.col.plus/assembly)

**Comment by ayco-at-naturalis** [comment]
So .... I'm not sure what to do with this one ... I'm not even sure I understand the issue

**Comment by mdoering** [comment]
ayco, Ill follow up on that

**Comment by mdoering** [comment]
Not only families, huge numbers of higher taxa - probably the sector roots - get duplicated in the search:

**Comment by mdoering** [comment]
they all lead to the same usage, so it is isolated to the index.
@ayco-at-naturalis would it not have been better to use the usage ids as doc ids? it would have been improssible to happen then and deletions/updates would also be way simpler as ES would not need to lookup the doc id by the usage id.
