### ISSUE TITLE
Increase max result size size (es & frontend)

### ISSUE THREAD

**Issue by ayco-at-naturalis** [Sp2000/colplus-backend#529]
"max_result_window" for es indexes is now at default (50000). Increase to 2million. Fronted should have this same setting

**Comment by mdoering** [comment]
until we get a better automised installation could you add the relevant ES configs here please?
https://github.com/Sp2000/colplus-deploy/blob/master/gbif-deploy.md#install-elasticsearch-641

**Comment by mdoering** [comment]
As there will be a hard limit in any case I would also suggest to catch these in the search DAO and make sure we never let ES fail, but instead return a 400 IllegalArgumentException

**Comment by ayco-at-naturalis** [comment]
yes will do
