### ISSUE TITLE
key missing for yroskov user

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#535]
The [key is missing in //user/me for yroskov again](https://github.com/Sp2000/colplus-frontend/issues/325), so he's getting access denied when trying to apply decisions.

**Comment by mdoering** [comment]
did @yroskov try to logout and back in again?

**Comment by mdoering** [comment]
@thomasstjerne do you remember what was the cause last time?

**Comment by yroskov** [comment]
Yes, I did try. Nothing happened.

What's worrying me, the login bug is inconsistent. Sometimes, system works, in other time, not.

**Comment by gdower** [comment]
Last time I think it was because of the jwt change. My account never is missing the key and I think we've got the same permissions.

**Comment by mdoering** [comment]
same here, I never had such a problem.
Yuris entry in the prod db shows last login from 2019-10-21:

```
 key |  username  |      firstname      | lastname |        email         |        orcid        | country |  roles  | settings |         last_login         |          created           | deleted 
-----+------------+---------------------+----------+----------------------+---------------------+---------+---------+----------+----------------------------+----------------------------+---------
 104 | yroskov    |                     |          | yroskov@illinois.edu |                     | US      | {0,1,2} |          | 2019-10-21 07:14:24.459    | 2019-10-21 07:14:24.474435 | 
```

**Comment by mdoering** [comment]
@gdower can you please check Yuris browser and the cookie he has for the col.plus domain?

**Comment by gdower** [comment]
What about on dev? We were working on dev yesterday. We did have to do
basic authentication to view //user/me

**Comment by mdoering** [comment]
same thing on dev:
´´´
 key |  username  |      firstname      | lastname |        email         |        orcid        | country |  roles  | settings |         last_login         |          created           | deleted 
-----+------------+---------------------+----------+----------------------+---------------------+---------+---------+----------+----------------------------+----------------------------+---------
 103 | yroskov    |                     |          | yroskov@illinois.edu |                     | US      | {0,1,2} |          | 2019-10-21 07:05:02.808    | 2019-10-21 07:05:02.820968 | 
´´´

It seems you did not login successfully

**Comment by thomasstjerne** [comment]
It is in the localStorage, not in the cookie (I think)

**Comment by mdoering** [comment]
@thomasstjerne this reminds me we should do Sp2000/colplus-frontend#276

**Comment by mdoering** [comment]
old issue is https://github.com/Sp2000/colplus-frontend/issues/325

**Comment by mdoering** [comment]
is that still an issue after logging out and back in again?

**Comment by gdower** [comment]
@yroskov is still getting the issue on dev even after logging in and out again. We also tried logging him in on a Firefox private window (which should completely reset the session).

**Comment by gdower** [comment]
I'm going to let him use my account for now.

**Comment by gdower** [comment]
Actually, it seems to be working now for some reason and his account has a key. We'll re-open this issue if it happens again.

**Comment by gdower** [comment]
@mdoering, I think we figured it out. If @yroskov logs in with his email address, he cannot apply decisions. If he logs in with just yroskov, he can apply decisions. Are there 2 accounts or is this a bug when logging in with an email address?

**Comment by mdoering** [comment]
it should be just his username `yroskov` but I had expected that logging in with the email address would fail.

**Comment by mdoering** [comment]
Ha, indeed that was the problem. GBIF accepted both the username and email address but our login expected the username. Ive patched the backend to accept both now, still to be deployed. Until then please use the username
