### ISSUE TITLE
Search does not include subgenera

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#536]
Search does not include subgenera:

[Rhizophagus (Anomophagus) wagae](https://dev.col.plus/dataset/2061/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Rhizophagus%20%28Anomophagus%29%20wagae&sortBy=taxonomic)

[Rhizophagus wagae](https://dev.col.plus/dataset/2061/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Rhizophagus%20wagae&sortBy=taxonomic)

**Comment by mdoering** [comment]
Indeed searching for "Rhizophagus (Anomophagus) wagae" or just "Anomophagus" does not yield any result.

**Comment by mdoering** [comment]
@ayco-at-naturalis is NameStrings.java used for such searches? In which case it misses infragenerics entirely.

**Comment by ayco-at-naturalis** [comment]
I currently use the scientificName only if there are more than 3 search terms

I use the NameStrings object for (what Geoff/Yuri calls) fuzzy matching.

I can add subgenus to the NameStrings object.

However I now realize that with just one search term I might as well match against the "weakly normalized" full scientific name

**Comment by mdoering** [comment]
I should revisit the search specs. Is the latest version still in that issue? It may be good to document the search behavior in a search readme. 

I would always try to match against the scientific name. Be aware that there is no guarantee for a parsed name! virus names for example do only exist as a scientific name. Unpardsble names and others like hybrid formulas too.

**Comment by mdoering** [comment]
What was the exact need that led to NameStrings based searches?

**Comment by mdoering** [comment]
I've created a separate issue  #541 for the unparsed searches

**Comment by mdoering** [comment]
search specs are at https://github.com/Sp2000/colplus-backend/issues/374
