### ISSUE TITLE
Search for unparsed names

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#541]
Make sure we can search for unparsed names of various kinds:
 - [ICTV](https://www.col.plus/dataset/1014/names?q=Acholeplasma%20phage): `Acholeplasma phage MV-L51 ICTV`
 - [ReptileDB](https://www.col.plus/dataset/1008/names?q=lichtensteinii): `H(eterodon) lichtensteinii Jan, 1859`
 - [VASCAN](https://www.col.plus/dataset/2011/names?q=saccharum): `Acer nigrum × Acer saccharum`
 - [VASCAN](https://www.col.plus/dataset/2011/names?q=incertae): `incertae sedis`
 - [UNITE](https://www.col.plus/dataset/7337/names?q=SH215351.07FU): `SH215351.07FU`

**Comment by ayco-at-naturalis** [comment]
The name search now always includes a (low scoring) OR search against the entire scientific name so that something always comes back if at least one word in the search phrase matches one word in the scientific name. Is that what you mean?

**Comment by mdoering** [comment]
that sounds good. Can you please test the above names in searches and link them here?

**Comment by mdoering** [comment]
@ayco-at-naturalis this still does not seem to work, see linked report above

**Comment by ayco-at-naturalis** [comment]
I'll make unit tests for each of the above names

**Comment by ayco-at-naturalis** [comment]
Now with unit tests for the above names (and quite a few improvements in other aspects)
