### ISSUE TITLE
Please include decisions in name search results 

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#548]
Currently the frontend does a subsequent lookup for each usage in the table. It would be better if the backend guaranteed consistency of the decisionKey=_NOT_NULL and data where `usage.decision` or at least `usage.decisionKey` is present

**Comment by mdoering** [comment]
the NameUsageWrapper object returned by the search should have a decisionKey present already.
If not its a bug. @thomasstjerne can you point to decisions not being returned by the search?

**Comment by mdoering** [comment]
related to #407

**Comment by ayco-at-naturalis** [comment]
@mdoering  @thomasstjerne Is this still actual? We now have a list of decisions in the name usage document. You could still ask ES for documents where decisionKey is not null, but the result is notoriously tricky - a document matches the query of it has at least one document where the decision key is not null.

**Comment by mdoering** [comment]
the need to find usages with/without decisions still exists, but the way to query for them is superceeded by the `decisionMode` parameter. 

`?decisionMode=_NOT_NULL` or `?decisionMode=_NULL` would be the way to go
