### ISSUE TITLE
name/1703359 returns 500

### ISSUE THREAD

**Issue by MortenHofft** [Sp2000/colplus-backend#55]
small thing
http://api.col.plus/name/1703359 returns 500
http://api.col.plus/name/1703359/synonyms returns an empty list.

shouldnt the non existing key be 404. not sure what the synonyms should be. 404 as well perhaps?

**Comment by MortenHofft** [comment]
same goes for missing taxons
http://api.col.plus/taxon/1703359 returns 500

**Comment by mdoering** [comment]
yes, these should all be 404s.
I have removed the underlying KeyNotFoundException that caused 500 - so should be fixed in next deploy. 

@ayco-at-naturalis , but the empty synonyms list needs some change to also be a 404!

**Comment by ayco-at-naturalis** [comment]
NB if key exists an empty list is still returned

**Comment by ayco-at-naturalis** [comment]
Added unit test

**Comment by mdoering** [comment]
redeployed latest version but still a 500: 
http://api.col.plus/name/91703359

**Comment by mdoering** [comment]
also http://api.col.plus/name/91703359/synonyms

**Comment by mdoering** [comment]
also for taxon: 
http://api.col.plus/taxon/-9
