### ISSUE TITLE
Is both dataset version & released needed?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#551]
version (string) and released (date) seems very much the same property of a dataset.
Should we better only keep the release date?

[WoRMS Mollusca](http://www.catalogueoflife.org/annual-checklist/2019/details/database/id/130)

> Version: 2019-03-06
> Release date: 2019-03-06

[World Auchenorrhyncha Database](http://www.catalogueoflife.org/annual-checklist/2019/details/database/id/189)

> Version: Nov 2017
> Release date: 2017-11-18

[Conifer Database](http://www.catalogueoflife.org/annual-checklist/2019/details/database/id/45)

> Version: Jan 2014
> Release date: 2014-06-18

[Fishbase](http://www.catalogueoflife.org/annual-checklist/2019/details/database/id/10)

> Version: Feb 2018
> Release date: 2018-02-15

**Comment by mdoering** [comment]
ping @gdower @yroskov

**Comment by yroskov** [comment]
We need BOTH: 
- version, as **applied by data provider inside its own project** (it might number only (ver. 1.34, or ver 5.), number and date (ver. 21 of Feb 2018), or date only (DD/MM/YYYY or MM/YYYY or YYYY), and **as data provider asks users to cite his data**;
- release date, a date when **export for the CoL was generated** (single format DD/MM/YYYY, better YYYY-MM-DD). We may receive different exports (with different dates) of the same version of database, and those exports might be different for various technical reasons. 
Date in the version and Release Date might be identical, close each other or very much different. For example, when we'll update ILDIS, version will remain as _ver. 12, May 2014_, but release date will be _2020-02-10_. 
If dataset version important for both users and CoL management, Release Date is more important for CoL management.

**Comment by mdoering** [comment]
thanks, that makes sense. Release date was not cear to me and sounds a bit misleading. maybe export date would be better?
