### ISSUE TITLE
Delete all data if a dataset gets deleted

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#552]
we only logically delete a dataset, but all data and the partition tables should be removed in that case.
Import metrics and file stored trees also need to be removed

**Comment by gdower** [comment]
The metadata including the title should also be nullified when a dataset is deleted. Otherwise some of the metadata is still accessible from the frontend after a dataset is "deleted."

**Comment by mdoering** [comment]
The metadata should stay as it was so we still know what the record is about.
We only logically delete dataset records, i.e. we set the deleted timestamp.

Deleted datasets will not show up in dataset searches anymore.
But you can still call them by their id if needed. 

Where does a deleted dataset show up wrongly?
The frontend needs to mark a deleted dataset somehow like we do in GBIF:
https://www.gbif.org/dataset/587b0989-6ade-4c6d-b366-ffdc70396159
