### ISSUE TITLE
Decision causing scarabs to only sync the apex taxon

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#557]
@mdoering, I isolated the decision in Scarabs that was causing only the apex taxon to sync:

![](https://files.gitter.im/gdower/AFHV/image.png)

```JSON
{
  "created": "2019-11-14T20:57:23.94755",
  "createdBy": 101,
  "modified": "2019-11-14T20:57:23.94755",
  "modifiedBy": 102,
  "key": 2840,
  "datasetKey": 3,
  "subject": {
    "name": "Gymnoloma",
    "authorship": "Dombrow, 2001",
    "rank": "genus"
  },
  "subjectDatasetKey": 1027,
  "mode": "block",
  "status": "synonym"
}
```

I'm not sure why, but when that decision is deleted, it syncs all of the taxa.

**Comment by gdower** [comment]
@mdoering, the current decision key is [2870](https://api-dev.col.plus/decision/2870), so if you run DELETE //decision/2870 it will sync the full sector.

**Comment by mdoering** [comment]
... and it does not even have a subject id, so its "broken". It should not even be considered...

**Comment by mdoering** [comment]
maybe the NULL id is the trouble, this patch avoids them

**Comment by gdower** [comment]
So the frontend isn't putting in the ID in from the interface that Yuri used to add the decision?

**Comment by gdower** [comment]
It looks like in order to restore sync, I had to delete out all of the decisions that had no name ID. I added this decision and it also blocked sync for all but the apex taxon (after I removed decision 2870 from above):

```JSON
  {
    "created": "2019-11-13T21:37:43.13447",
    "createdBy": 101,
    "modified": "2019-11-14T18:57:23.783755",
    "modifiedBy": 101,
    "key": 1397,
    "datasetKey": 3,
    "subject": {
      "name": "Aphodius",
      "authorship": "Schmidt, 1913",
      "rank": "genus"
    },
    "subjectDatasetKey": 1027,
    "mode": "block",
    "status": "synonym"
  }
```

**Comment by mdoering** [comment]
While debugging this I wonder how you deal with pro parte synonyms? Maybe the actual data here is a wrong case, but generally we should face this quite often:

[Gymnoloma Dombrow, 2001](https://dev.col.plus/dataset/1027/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Gymnoloma&rank=genus&sortBy=taxonomic) seems to be a p.p. synonym linked to 2 different accepted taxa:
[Stigmatoplia (Dombrow, 2001)](https://dev.col.plus/dataset/1027/taxon/22-.05-.01-.00-.079-.000-.000-.-) and [Scelidothrix (Dombrow, 2001)](https://dev.col.plus/dataset/1027/taxon/22-.05-.01-.00-.078-.000-.000-.-)

Ideally the source would just use one name record and 2 synonym records using that one name. That can only be done via ColDP though. The Clearinghouse normalizer does not try to normalize the 2 ACEF name duplicates into just one record - at this stage at least, maybe we should change that?

Does there need to be a decision type to merge the names and make them an "ambigous" pro parte synonym with 2 accepted taxa?

**Comment by mdoering** [comment]
see also https://github.com/Sp2000/colplus-frontend/issues/415

**Comment by mdoering** [comment]
by ignoring broken decisions this seems to be fixed now on both prod and dev
