### ISSUE TITLE
Possibility to query sectors by both catalogue and dataset scope

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#570]
Started work on the catalogue / dataset scope - looking at dataset [sectors listing](https://data.catalogue.life/dataset/1025/sectors) I see that I currently get them like this https://api.catalogue.life/sector?datasetKey=1025 where the datasetKey is actually the subjectDatasetKey. We should probably rename that param for consistency and make it possible to scope by both dataset and catalogue, like https://api.catalogue.life/sector?subjectDatasetKey=1025&datasetKey=3

**Comment by mdoering** [comment]
Yes, agree. I just changed the decision API to just expose a pageable list method that takes [various request params incl a boolean broken flag](https://github.com/Sp2000/colplus-backend/blob/master/colplus-api/src/main/java/life/catalogue/api/search/DecisionSearchRequest.java#L7).

I would propose to do the same for sectors.

**Comment by mdoering** [comment]
see https://sp2000.github.io/colplus/api/api.html#resource-47
