### ISSUE TITLE
Duplicates endpoint should also accept a decisionDatasetKey

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#571]
Needs adaption similar to the nameusage search #569

**Comment by mdoering** [comment]
should we call it `decisionDatasetKey` or rather `catalogueKey`? I seem to use both in different places and it would be better to unify

**Comment by thomasstjerne** [comment]
I would prefer catalogueKey, as the frontend uses this when sending props to components already

**Comment by mdoering** [comment]
kk, lets go with catalogueKey then. It will default to the draft btw as its required

**Comment by thomasstjerne** [comment]
And also for the nameusage/search right?

**Comment by mdoering** [comment]
yes, still to be done, but yes!
