### ISSUE TITLE
ac-export character encoding problem

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#577]
The ac-exporter is producing character encoding corruption for characters with diacritics and logographic characters:

For example here's `紫色叉鼻喉盘鱼`:
``` 
grep 'Zi se cha bi hou pan yu' common_names.csv 
8829261,f09ac7bb-1e05-4147-8e65-3ef22a164ef5,???????,Zi se cha bi hou pan yu,cmn,CN,\N,\N,10,\N,\N
```

which should be:

```
grep 'Zi se cha bi hou pan yu' common_names.csv 
8829261,f09ac7bb-1e05-4147-8e65-3ef22a164ef5,紫色叉鼻喉盘鱼,Zi se cha bi hou pan yu,cmn,CN,\N,\N,10,\N,\N
```

Here's `Harilik puuksäga`: 

```
8451658,194be6d5-23ec-4f98-b485-421e47521e7a,Harilik puuks?ga,Harilik puuksaega,est,EE,\N,\N,10,\N,\N
```

which should be:

```
8451658,194be6d5-23ec-4f98-b485-421e47521e7a,Harilik puuksäga,Harilik puuksaega,est,EE,\N,\N,10,\N,\N
```

The [character encoding is correct in the Clearinghouse](https://data.catalogue.life/dataset/1010/taxon/148961), so I think this is an ac-exporter bug.

Ref: https://github.com/Sp2000/colplus-repo/issues/89

**Comment by mdoering** [comment]
see https://stackoverflow.com/questions/30916853/postgresql-copy-encoding-how-to

**Comment by mdoering** [comment]
@gdower are you sure this is not a terminal artifact?

**Comment by gdower** [comment]
@mdoering, unfortunately, it's not a terminal artifact. Here's the [Harilik puuksäga species page](http://workbench.catalogueoflife.org/col_plus/details/species/id/194be6d5-23ec-4f98-b485-421e4752/common/aee906f7-810b-4e1d-92e1-2bffc428) for that common name:
![image](https://user-images.githubusercontent.com/8573609/70340351-44276100-1816-11ea-9445-15b9676a2380.png)

Most non-ascii characters seem to be replaced with `?` in all of the ac-export.zip csv files.

The encoding is correct in catalogue 3, so I think the encoding corruption is introduced by the ac-exporter: https://data.catalogue.life/dataset/3/taxon/194be6d5-23ec-4f98-b485-421e47521e7a

**Comment by mdoering** [comment]
that should have been the culprit: https://github.com/Sp2000/colplus-backend/commit/fb64ae5a3dab8129409ac9202c68ebbd41d9c5d2
