### ISSUE TITLE
Presentation of LTS Date

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-backend#579]
Problem with presentation of LTS Date, for example, in the original "Govaerts R., **Aug 2017**", in CoL+ "Govaerts R., **2017-08-01**".
**Aug 2017** should not be interpreted as **2017-08-01**.
**2017** should not be interpreted as **2017-01-01**.

**Comment by gdower** [comment]
If you look at the verbatim info, the scrutiny is the month, 2017-08, which CoL+ is converting to 2017-08-01:

https://data.catalogue.life/dataset/1024/taxon/189272

**Comment by mdoering** [comment]
Yes, that's expected as we keep dates.
I agree it would be better to also keep the dates precision (year, month, day).
Will look into options for this
