### ISSUE TITLE
tsv/csv standardization

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#582]
Data bugs are being introduced from inconsistent tsv/csv styles being used by the importers and exporters. I think we should switch to tsv as our internal standard with all fields quoted and any actual quotes in the data escaped as `\"`. That's how the AG+2019 GSD .tar.gz exports were produced and I don't really want to re-run that export again at this stage, because it will introduce all sorts of other issues again and delay the monthly release. **Alternatively, we just need to configure the importers/exporters correctly if that will take less time.**

For example, [here "Tigerwood" was quoted in the original source](https://data.catalogue.life/dataset/1141/verbatim?q=Tigerwood), which ultimately got turned into `"\"Tigerwood\""` by the AG+2019 exporter, which the [clearinghouse importer interpreted](https://data.catalogue.life/dataset/1141/taxon/79447) as `""Tigerwood""`, which then got exported as `"""""Tigerwood"""""` in ac-export. 

```
8585361,658ce92e-887d-4c35-a187-2c150f5c3ff3,"""""Tigerwood""""","""""Tigerwood""""",\N,\N,\N,\N,141,\N,\N
```
We will still have to deal with non-standardized csv/tsv exports from the data providers. Ideally, it would be really great if the Clearinghouse importer can accurately detect the right style of csv/tsv. Some future bugs might be introduced by data provider exporters not deliminating consistently. I can re-write the CoLDP specifications to include a preferred submission style.

**Comment by gdower** [comment]
The good news is that `""`'s don't appear to be too common in ac-export.zip:

```
grep '""' common_names.csv | wc -l 
21

grep '""' databases.csv | wc -l 
17

grep '""' distribution.csv | wc -l 
563

grep '""' families.csv | wc -l
0

grep '""' lifezone.csv | wc -l 
0

grep '""' references.csv | wc -l 
2393

grep '""' scientific_names.csv | wc -l
116

grep '""' scientific_name_references.csv | wc -l 
0

grep '""' specialists.csv | wc -l 
0
```

**Comment by mdoering** [comment]
the export as CSV is safe, no worries there. Unless you want to file a bug with Postgres.
As far as I remember the ConversionTool is built on CSVs. 
Changing to tabs is not much work for the exporter, so this question rather is a conversion tool one. @ruud-altenburg, any preference?

**Comment by gdower** [comment]
I'm talking about the flow of the data through the full chain of imports and exports, where each importer/exporter is handling the csv/tsv files differently (using `""` escapes vs `\"` escapes), resulting in some corruption of the final data.

The data that we work with shouldn't have tabs in it, whereas it has tons of commas, so it's better practice to use tsv which reduces chances of data corruption.

**Comment by mdoering** [comment]
Ah sorry. So your concern is about the import of ColDP, DwC-A etc and the used delimiters in those formats. DwC-A gives you any freedom you want, allowing any custom delimiter and linebreak. We do see people using pipes for example. The importer therefore has routines to guess the right format if its not specified properly.

For ColDP I felt I wanted to restrict the options to only support common formats which boils down to tabs and classic CSVs. These are both formats that a whole range of tools support. I definitely  think we should support both in ColDP. I would not mind recommending to use TSV in the ColDP specs if that is sth to improve the situation. CSVs [should be formatted](https://github.com/Sp2000/coldp#data-files) according to the official [RFC 4180 CSV specs](https://tools.ietf.org/html/rfc4180) which clearly say how to escape quotes:

>    7.  If double-quotes are used to enclose fields, then a double-quote
>        appearing inside a field must be escaped by preceding it with
>        another double quote.  For example:
> 
>        "aaa","b""bb","ccc"

If the current ACEF GSD exports do not follow the specs but use `\"` instead I see these options:
 - rerun the ACEF export to use `""`: sth you'd like to avoid, I agree 
 - support `\"` in the auto-detection of the CSV flavor: I would like to avoid that cause this is difficult to guess and will likely introduce errors in other places
 - provide a manual hint to the importer that the CSV quote escapes to be used are different. 

I think I'd prefer the last option. This could either be a secret file inside the archive, a setting in the dataset metadata (we have a flexible settings key/value map on a datasets metadata that we can use for this) or a hack inside the code that detects the ACEF export files from their URL.

I am leaning towards manual dataset settings which we could reuse to fix similar issues when we get data from providers.

**Comment by ruud-altenburg** [comment]
Strictly speaking, switching to tsv doesn't solve your quoting problem, does it? Tabs shouldn't be present in the input, but I bet they are. We have had all types of problems with the current CoL webservice because of hidden line breaks and other kinds of fancy characters that had snuck into the database.

**Comment by mdoering** [comment]
I have implemented a dataset setting map that can hold all kinds of custom settings.
The following 3 settings are implemented when reading text files during imports:

```
    /**
     * When importing data from text files this overrides  
     * the field delimiter character used
     */
    CSV_DELIMITER,

    /**
     * When importing data from text files this overrides  
     * the quote character used
     */
    CSV_QUOTE,

    /**
	 * When importing data from text files this overrides  
     * the single character used for escaping quotes inside an already quoted value. 
     * For example '"' for CSV
     */
    CSV_QUOTE_ESCAPE
```

**Comment by mdoering** [comment]
we then just need to update the prod db for the ACEF datasets with the new CSV_QUOTE_ESCAPE setting `\` (it takes the single escape char)

**Comment by mdoering** [comment]
I have updated all 166 ACEF GSD datasets on prod with the settings:
`CSV_QUOTE_ESCAPE = \`

**Comment by gdower** [comment]
Great, thanks!
