### ISSUE TITLE
Name search within datasets not working

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#587]
@ayco-at-naturalis, you probably know about it already, but name search within datasets isn't working on prod or dev:

https://api.catalogue.life/dataset/1015/nameusage/search?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Sesbania&sortBy=taxonomic

https://api.dev.catalogue.life/dataset/1015/nameusage/search?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Sesbania&sortBy=taxonomic

The Sesbania genus is present in the taxonomic classification:

https://data.catalogue.life/catalogue/3/dataset/1015/classification?sourceTaxonKey=xN

Search is not returning an error, so my guess is that the name index is just not populated.

**Comment by mdoering** [comment]
watch Gitter, we tried rebuilding the search index on prod but it didnt succeed yet so search there is broken. For dev this is unexpected. @ayco-at-naturalis can you please take a look?

**Comment by mdoering** [comment]
> Search is not returning an error, so my guess is that the name index is just not populated.

Yes, but remind you that this is the _search index_, the name index is one specific dataset within the Clearinghouse

**Comment by ayco-at-naturalis** [comment]
@gdower @mdoering I'm sorry just picking up on this one now. That sounds pretty serious, but as per markus's remarks, is this (still) an issue?

**Comment by mdoering** [comment]
The index is still not fully rebuild, lets wait for that

**Comment by mdoering** [comment]
reindexed prod and it is working
