### ISSUE TITLE
Remove orphaned names when deleting usages?

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#589]
e.g. when deleting a subtree in a catalogue. Should all names be removed too?
Otherwise they show up in search results as bare names...

**Comment by ayco-at-naturalis** [comment]
You mean you should have something like a sync for sectors and datasets?

**Comment by mdoering** [comment]
I was thinking of eithers db triggers that remove orphaned names when their usage (synonym or taxon) gets deleted.

Or keeping them around and providing a manual routine to delete orphaned names (and references eventually too)

**Comment by mdoering** [comment]
I will expose an API method to remove orphan names and references so we can clean those up on demand. With an optional lastModified date that we can use to only remove older objects in case orphans are due to recent still ongoing editing.

**Comment by mdoering** [comment]
new methods exposed for dataset scoped names and references

`GET /dataset/{KEY}/name|reference/orphans?before=2019-08-21` page through all orphan names|references with an optional before parameter

`DELETE /dataset/{KEY}/name|reference/orphans?before=2019-08-21` delete all orphan names|references with an optional before parameter
