### ISSUE TITLE
Issue "Unparsable Authrship" and the suffix "bis" in authorstrings

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-backend#591]
@mdoering 
Working with Species Fungorum sample from Paul Kirk, we have discovered that authorstrings with suffix **bis** dropped in the Issues report "Unparsable Authrship". For example, _Castellano, S.L. Mill., L. Singh bis & T.N. Lakh._  or _(Beurm., Gougerot & Vaucher bis) Sacc. & Traverso_
https://data.dev.catalogue.life/catalogue/3/dataset/30807/verbatim?issue=unparsable%20authorship.

Then I have a look IPNI database for botanical authors, and understood that suffix **bis** appears in standard form of some author names - for those who have homonymic colleagues:  https://www.ipni.org/?q=bis

Markus, could you please adjust the code, and include suffix **bis** in authorstrings as a legal case.

**Comment by mdoering** [comment]
thanks @yroskov an interesting one. I will update the parser accordingly !
