### ISSUE TITLE
Use usage labels in AC Exports - CoL+ spoils authorstrings

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-backend#595]
Please compare original authorstring presentation in FishBase taxa:
Aphyosemion calliurum ahli **(non Myers, 1933)** | misapplied name for Aphyosemion herzogi Radda, 1975 | FishBase
Aphyosemion calliurum ahli **(non Myers, 1933)** | misapplied name for Fundulopanchax gardneri (Boulenger, 1911) | FishBase
Aphyosemion calliurum ahli Myers, 1933  | synonym for Aphyosemion ahli Myers, 1933 | FishBase
http://www.catalogueoflife.org/annual-checklist/2019/search/all/key/Aphyosemion+calliurum+ahli/fossil/1/match/1

and presentation after CoL+ transformations:
Aphyosemion calliurum ahli | misapplied name for Aphyosemion herzogi Radda, 1975 | FishBase
Aphyosemion calliurum ahli | misapplied name for Fundulopanchax gardneri (Boulenger, 1911) | FishBase
Aphyosemion calliurum ahli Myers, 1933 | synonym for Aphyosemion ahli Myers, 1933 | FishBase
http://workbench.catalogueoflife.org/col_plus/search/all/key/Aphyosemion+calliurum+ahli/fossil/1/match/1

It would be better, if CoL+ do no take off any parts in authorstrings. 
**Expected behavior:** Identified issues in authorstrings should be reported to GSD authors and editors for their decisions.

Another example of CoL+ problems with authorstrings is automatic exclusion of names with "ined." and "comb. ined." portions in authorstrings. These issues should be reported, but not modified without editorial decision.

**Comment by mdoering** [comment]
These are not removed really, just parsed into different parts.
Taxon concept phrases like the one for misapplied names, e.g. "non XYZ" are found in the [API in accordingTo](https://api.catalogue.life/dataset/3/synonym/bb59ec7b-4743-485d-9d91-ebfc02c41901) and rendered in the [CoL+ UI](https://data.catalogue.life/catalogue/3/taxon/5ab7eb15-35ba-4884-bac8-0a4ea7961d7c
).

<img width="1345" alt="Bildschirmfoto 2019-12-18 um 20 51 51" src="https://user-images.githubusercontent.com/327505/71118374-44413c80-21d8-11ea-8b01-2b5fa085f41c.png">

I take this as a bug to fix the export!

**Comment by yroskov** [comment]
Authorstrings are empty in a product.

**Comment by yroskov** [comment]
It is wrong to remove _(non Myers, 1933)_ from the authorstring, because it says a lot to taxonomists.

**Comment by mdoering** [comment]
The manuscript name exclusion is done deliberately and you agreed with it:
https://github.com/Sp2000/colplus-backend/issues/350

@yroskov If you don't want that anymore we can easily remove the automatic filtering again. It's done on purpose to avoid excessive manual decisions. There is no point in manually removing all of them. Either they all stay in or all are out. Or what would be the reasoning for deciding on manuscript names case by case?

**Comment by yroskov** [comment]
All cases of manuscript names are different.
There are about 500 provisionally proposed names in WCSP, WPlants & WFerns. GSD authors intended to present consistent classification based on modern data. We must not simply delete all these species without asking authors first.

**Comment by mdoering** [comment]
please reopen the issue above and explain your expected behavior instead if you want that to be changed

**Comment by yroskov** [comment]
done: #269

**Comment by mdoering** [comment]
blocked by #598

**Comment by mdoering** [comment]
we are using verbatim authorships in the export now, so not blocking milestone anymore
