### ISSUE TITLE
Populate full TaxonInfo

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#6]
with all vernacular names, distributions & references for 1 taxon
https://sp2000.github.io/colplus/api/staging.html#model-TaxonInfo

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-backend/commit/7f928957934600b79b71e97d88408ef83f5521ae

**Comment by ayco-at-naturalis** [comment]
33df835b505f608356c65afde86020e6cc52289c
