### ISSUE TITLE
Delete decisions by datasetKey and subjectDatasetKey?

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#601]
Is there an API request to bulk delete all decisions by datasetKey and subjectDatasetKey? If not, it might be useful to add one, because currently we delete the decisions with 1 API request per decision which actually takes quite a while if there are thousands.

I tried this, but it didn't work:

```
DELETE http://api.dev.catalogue.life/decision?subjectDatsetKey=1027&dataset=3

{
  "code": 405,
  "message": "HTTP 405 Method Not Allowed"
}
```

It might be nice to even have a frontend button that will delete all decisions by datasetKey and subjectDatasetKey (with probably a big confirmation warning). If someone makes a huge mistake that they can't reverse, resetting the decisions and starting over again is sometimes going to be faster than trying to figure out how to correct the mistake.

**Comment by mdoering** [comment]
Added new delete method: 

`DELETE http://api.dev.catalogue.life/decision?datasetKey=1027&catalogueKey=3`

parameter names are the same as the delete sectors by dataset methd, but to be finally discussed in issue #603
