### ISSUE TITLE
Trying to POST a root taxon in a new managed dataset gives 404

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#604]
The frontend now shows a button for creating a root taxon in a new managed dataset, as suggested here:
https://github.com/Sp2000/colplus-frontend/issues/472

But when POSTing the new root, a 404 is returned:

Request failed with status code 404
Dataset 2052 does not exist

HTTP method: POST

https://api.dev.catalogue.life/dataset/2052/taxon

Body:
```
{
"status":"accepted",
"name":{
  "uninomial":"Bacteria",
  "rank":"domain"
 }
}
```

**Comment by mdoering** [comment]
This is a persistence exception mapped to 404 because the dataset partition was not yet setup.
This needs to happen when a managed dataset is created
