### ISSUE TITLE
Update credits.ini citation date

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#608]
In the [catalogue 3 metadata citation string](https://data.catalogue.life/catalogue/3/meta) we have YYYY-MM-DD:

```
Roskov Y.; Ower G.; Orrell T.; Nicolson D.; Bailly N.; Kirk P.M.; Bourgoin T.; DeWalt R.E.; Decock W.; Nieukerken E. van; Penev L.; eds. (2019). Species 2000 & ITIS Catalogue of Life, [YYYY-MM-DD] Beta. Digital resource at www.catalogueoflife.org/col. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-8858. 
```

Can you replace the YYYY-MM-DD automatically to match the edition date in credits.ini (e.g., replace YYYY-MM-DD with 2020-01-08 below)? I think it makes more sense to do it at the ac-exporter stage than in conversion since other people might download that export archive.

```
current_edition = "monthly"

[monthly]
edition = "2020-01-08"
citation = "Roskov Y.; Ower G.; Orrell T.; Nicolson D.; Bailly N.; Kirk P.M.; Bourgoin T.; DeWalt R.E.; Decock W.; Nieukerken E. van; Penev L.; eds. (2019). Species 2000 & ITIS Catalogue of Life, [YYYY-MM-DD] Beta. Digital resource at www.catalogueoflife.org/col. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-8858."

[annual]
edition = 2019
citation = "Roskov Y., Ower G., Orrell T., Nicolson D., Bailly N., Kirk P.M., Bourgoin T., DeWalt R.E., Decock W., Nieukerken E. van, Zarucchi J., Penev L., eds. (2019). Species 2000 & ITIS Catalogue of Life, 2019 Annual Checklist. Digital resource at www.catalogueoflife.org/annual-checklist/2019. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-884X."
```

**Comment by mdoering** [comment]
We could do that. But that leaves the draft catalogue in the clearinghouse with a strange citation, don't you think? The exporter either uses a given citation or generates one on its ownbased on the individual metadata properties like `authorsAndEditors` or `title`. The `released` date is used to generate the date, see https://github.com/Sp2000/colplus-backend/blob/master/colplus-ws/src/main/resources/exporter/credits.ftl#L8

Maybe that's a simpler way to populate the credits.ini?
Alternatively we could also have a more private settings entry in the dataset that acts as a template. I would prefer that to place variables into the main citation.
