### ISSUE TITLE
Use Elastic Search for searches

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#61]
Use Elastic search for searching, removing the performance bottleneck #57 .
Consider how to best expose facets and counts. Should we expose ES directly or wrap it in our API?

The importer needs to update ES for each indexed dataset. But there should also be a backfill method that regenerates the entire index for desaster recovery and updating an out of sync index  e.g. because of network outages. A DW admin command that reindexes the entire database or just a single dataset is needed to manage ES data.

For testing an embedded ES should be used when testing populating and querying the index. When running other tests not directly using searches it should be doable to swap out the implementation for a mock that doesn't do anything. A new ElasticConfig would be good that allows to specify the ES location (if null use a mock) and any other needed settings.

**Comment by mdoering** [comment]
Could be useful https://github.com/dropwizard/dropwizard-elasticsearch

**Comment by mdoering** [comment]
Similar to [handle all names](https://github.com/Sp2000/colplus-backend/blob/master/colplus-dao/src/main/java/org/col/db/mapper/NameMapper.java#L25) in a dataset I'd suggest to use a resulthandler with mybatis to process an entire, large [resultset of NameUsages](NameUsageMapper) in one go with a single db cursor. This is **much** quicker than paging and much simpler and quicker than processing in batches.

**Comment by mdoering** [comment]
Reading NameUsages from neo4j will be too hard and impossible to rebuild an entire index from, so we should make use of postgres as the source

**Comment by mdoering** [comment]
Should ES use a separate index per dataset like the pg partitioning does?

**Comment by ayco-at-naturalis** [comment]
So if reading from neo4j is too hard, it will be a job separate from (and after) the pg import?

**Comment by ayco-at-naturalis** [comment]
My broad strokes in ImportJob now looks like this:

`
        new Normalizer(store, dwcaDir, index).call();

        updateState(ImportState.INSERTING);
        LOG.info("Writing {} to Postgres!", datasetKey);
        store = NeoDbFactory.open(datasetKey, cfg.normalizer);
        new PgImport(datasetKey, store, factory, cfg.importer).call();
        
        new EsImport(datasetKey, store, esClientFactory, cfg.importer).call();

        checkIfCancelled();
`
Since the store read-only (if I am correct), the PgImport and EsImport can be parallelized, but this was the basic idea.

**Comment by mdoering** [comment]
the neo4j store is not read-only, but I would go for postgres as the source:

1. mybatis mapper for NameUsage instances exists already and its not trivial to map these complex objects
2. surrogate keys dont exist in neo yet (can be changed though)
3. rebuilding the entire ES index would require the copies matching the current sql of neo4j to persist and opening/closing of a store per dataset. When we start a new import the old neo4j store gets removed
4. unclear how neo4j handles parallel, multithreaded reads and transactional locks
5. postgres is partitioned and we can read the specific partition tables directly not interferring with the aggregated table. The partition can even be attached to the main table after ES has been build so its not yet visible to the public, full queries

Building the ES index sequentially will obviously stretch the entire import process considerably, but we can parallize entire imports more to counter that. Removing the full text search index from the names table will also slightly speed up the sql import.

**Comment by mdoering** [comment]
Done the process dataset handler in the NameUsage mapper which was straight forward and can be used already to index into ES:
https://github.com/Sp2000/colplus-backend/commit/7a7ea062eb97ef8272be913091511f7d6b63122d
