### ISSUE TITLE
Decisions for note and website not getting applied

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#612]
Decisions for the fields `note` and `website` don't seem to get synced. Until we find a permanent solution, I was trying to use decisions as a temporary workaround to add BHL URLs, but it might be useful to be able to update those fields with editorial decisions. Here's what I tried and the decisions posted successfully and weren't listed as broken:

```JSON
POST http://api.dev.catalogue.life/decision
{
  "lifezones": [],
  "note": "data.dev.catalogue.life",
  "mode": "update",
  "subjectDatasetKey": 1206,
  "datasetKey": 3,
  "subject": {
    "id": "595",
    "name": "Decoriplus hamatus",
    "authorship": "Louw, 1979 Kamiński M.J.",
    "rank": "species",
    "status": "accepted",
    "parent": "Decoriplus",
    "code": "zoological"
  }
}

POST http://api.dev.catalogue.life/decision
{
  "lifezones": [],
  "website": "data.dev.catalogue.life",
  "mode": "update",
  "subjectDatasetKey": 1206,
  "datasetKey": 3,
  "subject": {
    "id": "595",
    "name": "Decoriplus hamatus",
    "authorship": "Louw, 1979 Kamiński M.J.",
    "rank": "species",
    "status": "accepted",
    "parent": "Decoriplus",
    "code": "zoological"
  }
}
```

**Comment by mdoering** [comment]
Yes, decisions do not have such properties but we could add them easily.
I dont think adding BHL URLs that way is a feasable thing though unless they are just a few. 

Should the BHL link not be on the Reference instance rather than on the name?

**Comment by gdower** [comment]
Using decisions was just a temporary idea for testing while you were away but then I figured out that I could successfully [build small assemblies for testing the BHL links](https://data.dev.catalogue.life/catalogue/2059/assembly) instead.

I think attaching links to references is preferable. We might eventually have links to more than 1 external library and also sometimes an external project might want to link to a taxon or name page instead of a reference.
