### ISSUE TITLE
Setup robots.txt

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#613]
Google and probably other search engines are indexing the Clearinghouse, and we got a complaint because Google indexed a dataset that was under development. At least for now, we should deny all web crawlers with robots.txt:

```
User-agent: *
Disallow: /
```

We probably should not allow web crawlers to index the Clearinghouse even in the future because it's primarily intended as a publishing tool, not a data viewer for the public. It would be preferable to have catalogueoflife.org indexed, not the Clearinghouse, and I think other projects would likely also want their production websites indexed instead of the Clearinghouse. Otherwise the production websites are going to be competing with the Clearinghouse for page rank.

**Comment by gdower** [comment]
Fixed by @thomasstjerne

**Comment by mdoering** [comment]
Hm, the Clearinghouse in its original perception is intended to be public and for open data. We dont want to _compete_ with original sites, but being searchable by google seems not entirely wrong to me.

But is the indexing by google really going straight to the backend? Sounds rather like a frontend problem
