### ISSUE TITLE
Changing dataset type to managed doesn´t include it in /dataset/catalogues response

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#618]
https://api.dev.catalogue.life/dataset/catalogues

**Comment by mdoering** [comment]
I would propose to `https://github.com/Sp2000/colplus-backend/issues/634`.

**Comment by mdoering** [comment]
Also the call is listing managed datasets which have sectors, not all managed datasets.
The later is a simple dataset search: http://api.catalogue.life/dataset?origin=MANAGED

**Comment by mdoering** [comment]
What did we need the method for anyways? Cant this just be the dataset search?
I guess released catalogues are what we would like to avoid?

**Comment by thomasstjerne** [comment]
It is probably only used for the catalogue picker
Ill just used  http://api.catalogue.life/dataset?origin=MANAGED
instead

**Comment by mdoering** [comment]
Can I remove the method then? And should we have a new origin `release` to search for active managed datasets only?

**Comment by mdoering** [comment]
removed
