### ISSUE TITLE
Add taxon_reference.topic field

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#62]
references linked to a taxon should optionally be classified according to some enum.
ACEF has this in the reference links table.

**proposal**:
 - create ReferenceTopic enum
 - add array field topic to table taxon_reference
 - create TaxonReference class which takes a referenceKey and list of ReferenceTopic
 - change TaxonInfo.references to be a list of TaxonReference instances
 - add createTaxonReference method to ReferenceMapper that takes taxonKey and a TaxonReference 

**Alternatively** consider to avoid a new TaxonReference class, populate the table with createTaxonReference(taxKey, refKey, enum[] topics) and expose the data in TaxonInfo as Map<Integer, Topic[]>

**Comment by aycoholleman** [comment]
As discussed, the ACEF ReferenceType field really is just there to differentiate between types of references that we already distinguish within our data model: references about a taxon, references about a vernacular name, etc. We should generate that field from the assembly db and the import procedure should pick it up to decide which JOIN table to populate.

**Comment by ayco-at-naturalis** [comment]
Covered by #62
