### ISSUE TITLE
Syncstate includes sectors from other catalogues

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#620]
E.g. this endpoint 
https://api.dev.catalogue.life/assembly/3
returns sectors targeting catalogue 2064

**Comment by mdoering** [comment]
indeed not ideal. Right now we have only a single assembly thread shared across all catalogues and this endpoint returns that state. Quick solution is to change the resource to be at `/assembly` so it does not have a dataset scope.

**Comment by mdoering** [comment]
deployed to dev:

https://api.dev.catalogue.life/assembly
https://api.dev.catalogue.life/assembly/3
