### ISSUE TITLE
Missing credits to the classification providers

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-backend#623]
We need to bring back credits to classification contributors in tree branches with 0 species.

These contributors are: 
1.	**Animal biodiversity**: An Outline of Higher-level Classification and Survey of Taxonomic Richness (Addenda 2013) by Zhang Z.-Q. (ed). (2013). **GSDid 502**.
_Example:_ http://www.catalogueoflife.org/annual-checklist/2019/browse/tree/id/5fa582ff7728e25cf35bf173fd70687d 
2.	A Higher Level Classification of All Living Organisms by Ruggiero M.A., Gordon D.P., Orrell T.M., Bailly N., Bourgoin T., Brusca R.C., Cavalier-Smith T., Guiry M.D., Kirk P.M. (2015). **GSDid 500**.
3.	**IRMNG**: Interim Register of Marine and Nonmarine Genera by Rees T. (2018). **GSDid 501**.
_Example:_ http://www.catalogueoflife.org/annual-checklist/2019/browse/tree/id/11e650788bf11b519ac6727bf4e170ab 
4.	**ITIS** (in regional sectors). **GSDid 17**.

**Issue with genera from IRMING** needs further consideration and discussion on GT. At this moment, the lowest rank of taxa with 0 species in CoL Tree is family. This makes assembly and gap exposure much easier.

_Message from Tony Rees, 30 Jan 2020 at 04:30:_
_Subject: IRMNG content missing from CoL 2020-01-10 Beta?_

_I just checked the latest monthly release of CoL (Jan 2020) and noticed that the IRMNG genera that were previously being incorporated seem to have disappeared - e.g. search for "Fucus" or "Euglena" does not retrieve those genera any more. (IRMNG was supplying genus- level content for a range of algal/chromist/protozoan/plant algae groups where these were not being supplied from other sources)._

_Also the database description at https://www.catalogueoflife.org/col/details/database/id/501 is blank; previously it said:_
_Full name:	Interim Register of Marine and Nonmarine Genera
Short name:	IRMNG
Version:	Mar 2018
Release date:	2018-03-20
Authors/editors:	Rees T.
Taxonomic coverage:	Chromista - Acavomonidia, Bigyra (pro parte), Cercozoa (pro parte), Cryptista, Haptophyta, Heliozoa, Miozoa (pro parte), Ochrophyta (pro parte), Picozoa
Protozoa - Amoebozoa (pro parte), Calcitarcha, Choanozoa (pro parte), Euglenozoa, Loukozoa, Metamonada, Microsporidia (pro parte), Percolozoa (pro parte), Sulcozoa
Plantae - Charophyta, Chlorophyta, Glaucophyta, Rhodophyta
English name of the group:	All genera
Number of living species	0_

_I did note that IRMNG is cited in passing as a contributor to the "CoL Management Hierarchy", but first, it seems a backward step for the thousands of genera concerned to be omitted (leaving serious gaps in CoL coverage in the algal/protist area), and second, the record-level credit for individual IRMNG genera is valuable exposure for us bearing in mind that external recognition is the only reward IRMNG compilers get for their efforts (it is done as a "labour of love"), so the exposure that CoL (as the premier player in this space) can give is certainly appreciated._

_With best regards - Tony
Tony Rees, New South Wales, Australia
IRMNG main compiler, 2006- current
www.irmng.org_

Indeed, credits to CoL classification contributors are missing in CoL+ (these are tree branches with 0 species).

**Comment by mdoering** [comment]
@yroskov I finally managed to get IRMNG and Animal Biodiversity sectors out of AG+.
There are 4 animal biodiversity sectors and 125 from IRMNG: 
[sectors.xlsx](https://github.com/Sp2000/colplus-backend/files/4215772/sectors.xlsx)

If possible please verify them at least briefly

**Comment by yroskov** [comment]
For 1502 Animal Biodiversity, I was able to retrieve following sectors in AC19:

in order Coleoptera:
Superfamily Lepiceroidea • 0 of 1 est. living spp (0%) • Animal biodiversity
Family Aspidytidae • 0 of 2 est. living spp (0%) • Animal biodiversity
Family Meruidae • 0 of 1 est. living spp (0%) • Animal biodiversity
Family Rhysodidae • 0 of 350 est. living spp (0%) • Animal biodiversity

in order Hymenoptera:
Superfamily Megalyroidea • 0 living spp • Animal biodiversity
Superfamily Stephanoidea • 0 living spp • Animal biodiversity
Superfamily Trigonaloidea • 0 living spp • Animal biodiversity

**Comment by yroskov** [comment]
For 1501 IRMNG, I was able to check lines 6 - 40 for now (up to class Minisporea). 
Two credits are incorrect: 
order Vojnovskyales from PaleoBioDB 
order Amoebida from ITIS Regional

**Comment by yroskov** [comment]
lines 41-130 (up to the end)
5 credits are incorrect:
phylum	Heliozoa ITIS Regional	
family	Hemidiscaceae ITIS Regional	
family	Sellaphoraceae ITIS Regional	
family	Neidiaceae ITIS Regional	
order	Rhizosoleniales ITIS Regional

**Comment by yroskov** [comment]
I am not able to confirm that list of IRMNG sectors is complete. (Perhaps, it is not important how complete it is at this point. We are going to update IRMNG with 2020 version (request from Tony Rees).

**Comment by mdoering** [comment]
It is near to impossible to derive the same results from AG+ then the current portal displays. I can only offer to add this list or a slightly manually corrected one to prod so we have sth to show credits now. Whenever we update IRMNG we should then review and adjust sectors properly.

Does that make sense?

**Comment by mdoering** [comment]
ITIS Regional is gone in AG+, so I cannot see these at all.
A few ten or so families in AG+ are also duplicates and credited to different sources. That might play a role here as I randomly selected one of them

**Comment by yroskov** [comment]
ITIS Regional gone - as expected - these sectors can be regarded as CoL Management Classification.
IRMNG we'll "polish" with a new update. Now it's important to demonstrate that CoL+ can handle credits contributors to the classification.
We'll see how to bring 3 missing families from Animal Biodiversity. They are important for visualizing gaps in Coleoptera.

**Comment by mdoering** [comment]
I have applied the above sectors to the prod draft and linked 11 name usages to Animal Biodiversity and 4350 usages to IRMNG. @yroskov please update dataset metadata for both to fit your needs (note: IRMNG metadata is as given by Tony Rees in his dwc archive).

<img width="1610" alt="Screenshot 2020-02-19 at 17 16 12" src="https://user-images.githubusercontent.com/327505/74851453-8bb08a00-533b-11ea-86c1-c824e0671ed8.png">
