### ISSUE TITLE
Atomized name elements should be used when provided instead of the name parser

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#624]
The name parser is [incorrectly interpreting](http://api.catalogue.life/parser/name/?name=Sepidium+dispar+Desbrochers+des+Loges,+1881) the following binomial as a trinomial even when I'm giving it the correct atomized name components:

_Sepidium dispar_ Desbrochers des Loges, 1881

https://data.dev.catalogue.life/catalogue/3/dataset/2073/verbatim?issue=subspecies%20assigned

**Comment by mdoering** [comment]
Thanks. You can file pure name parser bugs here:
https://github.com/gbif/name-parser/issues

In this case it's both a name parser issue, but potentially also a ColDP importer one.
If entire name is given as atomized fields we should trust those more than the parser?

In your case the authorship is given separately, but it is already part of the scientificName. So it is not parsed again. Try removing it from the name, this might yield better results.

**Comment by gdower** [comment]
If atomized name components are provided, the atomized components should take precedence over the parser results. If I have atomized name components, I've been providing both the full scientific name and the atomized name components so that the mismatches between the name components and parser results can be used to improve the parser.

I opened a ticket for the GBIF name parser.
