### ISSUE TITLE
Consider adjusting "Synonym parent" issue

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#626]
I used the clearinghouse validate a dataset and got quite a bunch of synonym parent issues. However, all of the affected usages were actually synonyms themselves. I.e. species combined into new genus.

Maybe, consider adjusting to only affect accepted taxa with a synonym parent  ?

**Comment by mdoering** [comment]
I am not sure if I understand, can you give an exampe? "Chained" synonyms, i.e. synonyms that have another synonym as the parent, are not desired.

**Comment by mdoering** [comment]
@thomasstjerne ? I would close this otherwise as I dont understand the problem

**Comment by thomasstjerne** [comment]
Say the genus _Aus_ is being combined into the genus _Bus_.
Hence the species _Bus cus_ is also combined into _Aus_ as _Aus cus_.

So the usage _Bus cus_ is a synonym and its parent _Bus_ is also a synonym, but this seems legit?

**Comment by mdoering** [comment]
In what format does this example happen, DwC?
Synonyms no matter in which format should always point to an accepted.
And the classification given for synonyms is irrelevant and instead taken from the accepted.

_Bus cus_ is a synonym and _Aus cus_ is the accepted. It does not point to _Bus_ anymore, or how does it do that?
