### ISSUE TITLE
nameusage endpoint is serving csv?

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#630]
The nameusage endpoint is generating a CSV download when called directly:

https://api.dev.catalogue.life/dataset/31442/nameusage

Although csv downloads are nice, I'm assuming it's supposed to serve json by default, so I'm assuming this is a bug?

**Comment by gdower** [comment]
It looks like it's supposed to be like that:

https://github.com/Sp2000/colplus-backend/blame/ed5bc771a1f842830e250f740b7e7c6a19b7ec8c/colplus-ws/src/main/java/life/catalogue/resources/NameUsageDatasetSearchResource.java

**Comment by mdoering** [comment]
Yes, it is intended. But maybe the chosen URL is not the greatest and it should rather go under dataset/1234/export somewhere where we also do the AC exports and ColDP in the future.

This CSV is only usages though, thats why it was placed there
