### ISSUE TITLE
Unable to edit metadata in production Clearinghouse

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-backend#632]
I was not able to turn metadata page in editorial mode. After I slide "Edit" switcher, blank page appear. Page reload in a browser does not fix the issue. Browser Firefox 72.0.2. Clearinghouse: Frontend version: 89628ea February 7, 2020 7:59 AM
Backend version: 5409fd4 January 3, 2020 3:40 PM
View mode:
![image](https://user-images.githubusercontent.com/28574252/74278358-b452d700-4cde-11ea-8704-4445a4c88f0a.png)
Supposed to be edit mode:
![image](https://user-images.githubusercontent.com/28574252/74278425-d187a580-4cde-11ea-9b3c-486a5b28d685.png)

**Comment by mdoering** [comment]
ok, Im on that but it might take until tomorrow. We should try to avoid breaking prod.

**Comment by yroskov** [comment]
Shall we wait with Scarabs and Sepidiini in prod? We have completed our tests in dev, and now need to repeat & finalize both GSDs in prod.

**Comment by mdoering** [comment]
Yes. Please watch gitter to see the current status of deployment

**Comment by yroskov** [comment]
>>please do not alter prod data
OK
