### ISSUE TITLE
Switching ac-export from NULL to \N

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#635]
@mdoering, I think I figured out the [problem with conversion](https://github.com/Sp2000/ConversionTool/issues/23). The [MySQL 5 documentation](https://dev.mysql.com/doc/refman/5.7/en/load-data.html) seems to be wrong, or we're not interpreting it right because it's importing `NULL` as the string `"NULL"` with the config you had suggested:

```
LOAD DATA LOCAL INFILE '$file'
                INTO TABLE `$table`
                FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY ''
                LINES TERMINATED BY '\n'
                IGNORE 1 LINES;
```
MySQL also doesn't recommend using `ESCAPED BY ''`: "It is probably not a good idea to specify an empty escape character, particularly if field values in your data contain any of the characters in the list just given."

Option 1) The default MySQL config works:

```
                FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\'
                LINES TERMINATED BY '\n' STARTING BY ''
```

Under the above config, ac-export needs to modified to send `\N` instead of `NULL`. I wouldn't worry about [`\` frame shift bug](https://github.com/Sp2000/colplus-backend/issues/609) with tsv, because I think it's much less likely to occur than when we were using csv's.

Option 2) The alternative option that actually seems to work is replacing `NULL` with `​` (nothing) which imports as an empty string and conversion is pretty tolerant of empty strings instead of `NULL`'s. I'd go with option 1 though because it seems less risky to use an escape character  because it's not impossible that we'd have an errant tab and quotes in the same line, whereas it is pretty unlikely we'd have a field with tabs, quotes that is also terminated with `\`.

**Comment by mdoering** [comment]
Its trivial to change the NULL representation as we prefer it.
BUT using an escape character means not only potential frameshifts, we need to also escape the escape char. As you say the frameshifts are unlikely to happen with tabs. But an escape character before any other char still means we'd lose that char. And postgres uses the escape char very differently from mysql as far as I can tell. No matter what char is used:

> ESCAPE
> Specifies the character that should appear before a data character that matches the QUOTE value. The default is the same as the QUOTE value (so that the quoting character is doubled if it appears in the data). This must be a single one-byte character. This option is allowed only when using CSV format.

So it's only when facing the quote char that escape is used. Mysql on the other hand seems to use it all the time. Thats why I think we should try to avoid escapes alltogether. If you cannot turn it off in mysql lets use some strange control char thats not gonna exist.

I use this when exporting from Postgres now:
`
CSV HEADER NULL 'NULL' DELIMITER E'\\t' QUOTE E'\\f' ENCODING 'UTF8'
`

**Comment by mdoering** [comment]
@gdower it would be best to try out some settings manually on a small test file for a single table.

`
create table test (key serial, name text,author text, description text, link text);

 key |    name    |   author   |         description         |                 link                 
-----+------------+------------+-----------------------------+--------------------------------------
   1 | Abies alba | Mill.      | Nothing but pain            | http://gbif.org/not%20there?q=%23ber
   2 | Abies alba | Mill. 1988 | Nothing                    +| 
     |            |            | but                        +| 
     |            |            | pain                        | 
   3 | Abies alba |            |                             | 
   4 | Abies alba |            | /Nothing\but/slashes\       | 
   5 | Abies alba |            | Nothing but "quotes"        | 
   6 | Abies alba |            | "\"quoted"/slashes          | 
   7 | Abies alba |            | Nothing\but"quoted"/slashes | 
(7 rows)
`

Native Postgres TEXT export:
`\copy test to 'test.txt'`: 
[test.csv.zip](https://github.com/Sp2000/colplus-backend/files/4234485/test.csv.zip)

Native Postgres CSV export:
`\copy test to 'test.csv' WITH CSV HEADER`:
[test.tsv.zip](https://github.com/Sp2000/colplus-backend/files/4234486/test.tsv.zip)

Custom Postgres TSV export using a non occurring quote char:
` \copy test to 'test.tsv' WITH CSV HEADER NULL 'NULL' DELIMITER E'\t' QUOTE E'\f' ENCODING 'UTF8'`:
[test.txt.zip](https://github.com/Sp2000/colplus-backend/files/4234487/test.txt.zip)

**Comment by mdoering** [comment]
@gdower can you please test import this file into mysql?
The above listing shows the expected outcome.
The last TSV setting is what the export currently uses

**Comment by gdower** [comment]
```
CREATE DATABASE tsv_test DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
USE tsv_test;
DROP TABLE IF EXISTS test;
CREATE TABLE test(`key` TEXT, `name` TEXT, `author` TEXT, `description` TEXT, `link` TEXT);
LOAD DATA LOCAL INFILE '/var/lib/mysql/test.tsv'
                INTO TABLE `test`
                FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\'
                LINES TERMINATED BY '\n' STARTING BY ''; 
SELECT * FROM test;

mysql> SELECT * FROM test;
+------+------------+------------+-----------------------------+--------------------------------------+
| key  | name       | author     | description                 | link                                 |
+------+------------+------------+-----------------------------+--------------------------------------+
| 1    | Abies alba | Mill.      | Nothing but pain            | http://gbif.org/not%20there?q=%23ber |
| 2    | Abies alba | Mill. 1988 | Nothing 
but 
pain          | NULL                                 |
| 3    | Abies alba | NULL       | NULL                        | NULL                                 |
| 4    | Abies alba | NULL       | /Nothing\but/slashes\       | NULL                                 |
| 5    | Abies alba | NULL       | Nothing but "quotes"        | NULL                                 |
| 6    | Abies alba | NULL       | "\"quoted"/slashes          | NULL                                 |
| 7    | Abies alba | NULL       | Nothing\but"quoted"/slashes | NULL                                 |
+------+------------+------------+-----------------------------+--------------------------------------+
7 rows in set (0.01 sec)
```

**Comment by gdower** [comment]
@mdoering, I checked export-2079.zip and at present there are no backslashes in the data other than in `\n` line breaks in database.csv that are supposed to be there.
