### ISSUE TITLE
Missing genera with 0 species in Tenebrionidae family

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-backend#637]
Checking presentation of Sepidiini tribe data (GSD id 1206) at http://workbench.catalogueoflife.org/col_plus/browse/tree/id/ce5cfb8012398ce2a52cec94e6f97409, I have spot that all genera in the parent family Tenebrionidae outside Sepidiini GSD are missing. 
However, they are present in Clearinghouse in autoestablished tribe "Not assigned" https://data.catalogue.life/catalogue/3/assembly?assemblyTaxonKey=99bfc923-aed0-4028-9e42-4a51db5273b4--incertae-sedis--TRIBE
Why it is so?

**Comment by mdoering** [comment]
It looks to me like we generally do not export any empty genera!
The original format does not support this and we need to hack it - and it seems we've forgotten to do so. 

Sidenote: You have added tribe and subtribes to the CoL - was that on purpose? The exporter can't export those, but bear in mind the export is not the real thing. It is a simplified view on the CoL that will be removed once the new portal is matured.

**Comment by mdoering** [comment]
Sidenote: You have added tribe and subtribes to the CoL - was that on purpose? The exporter can't export those, but bear in mind the export is not the real thing. It is a simplified view on the CoL that will be removed once the new portal is matured.

**Comment by yroskov** [comment]
Tribes and subtribes in Sepidiini dataset were on purpose, to see how all work.
