### ISSUE TITLE
/nameusage/suggest doesn't appear to work

### ISSUE THREAD

**Issue by sckott** [Sp2000/colplus-backend#640]
e.g. http://api.catalogue.life/nameusage/suggest?q=Api is throwing 500 server errors - is it just me, or maybe the route is not operational yet?

**Comment by mdoering** [comment]
@ayco-at-naturalis NameUsageSuggestionServiceEs.java should not throw a generic EsException but instead something that we can convert into a bad request response.

**Comment by sckott** [comment]
thanks @mdoering !

**Comment by ayco-at-naturalis** [comment]
Sorry, yes I am regularly tricked into this myself, but I see Markus solved this already
