### ISSUE TITLE
Search ranking not showing full matches on top

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#641]
I would have expected that full word matches show on top of search results.
If you search for `Tragopogon` you get the exact match genus at the very top.
But all other species in that genus are way below other partial matches, often prefix matches of the epithet in some other genus.

@yroskov @gdower maybe this corresponds with your initial specs, but I find this rather unintuitive.

<img width="1293" alt="Screenshot 2020-02-27 at 15 07 29" src="https://user-images.githubusercontent.com/327505/75452599-e452d900-5972-11ea-8c5b-f73293f74394.png">

**Comment by mdoering** [comment]
It becomes really bad with short names like the bird genus `Ara`:

<img width="1293" alt="Screenshot 2020-02-27 at 15 12 15" src="https://user-images.githubusercontent.com/327505/75453309-06992680-5974-11ea-987a-542b8f27f65a.png">

In the previous portal there was a flag `Match whole words only` to avoid prefix matching.
We should add an option to turn it off and make that the default. I would propose to add a new parameter `partial` which is false by default.

**Comment by ayco-at-naturalis** [comment]
Hm ... yes, I can add this option along with fuzzy on/off

**Comment by mdoering** [comment]
It seems the old interface does the same thing:
http://www.catalogueoflife.org/col/search/all/key/Ara/fossil/1/match/0

Now that we have a match whole word only option this becomes largely irrelevant.
@thomasstjerne can you make sure whole word match is the default  for searches please?
