### ISSUE TITLE
name/KEY/publishedIn return wrapped reference

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#67]
http://api.col.plus/name/272232/publishedIn
wraps a references in an object with key=reference

it should be without like the docs say:
https://sp2000.github.io/colplus/api/api.html#resource-19

**Comment by mdoering** [comment]
there is also no key exposed

**Comment by mdoering** [comment]
it is because we return a ReferenceWithPage instance.
Thats not exactly nice for the consumer who is likely rendering the data just from the CSL. As a user I would rather like to see the page as part of the returned CSL. That muddies the water between the reference identified by the key, but I believe making the reference more specific by adding a specific page is acceptable. As CSL data in references is not dealt with properly yet this leaves it open a bit. I suggest to place the page data into the CSL field "locator" together with a static value "page" in the field "label". This appears to be the best fit: http://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cite-items
 and  https://aurimasv.github.io/z2csl/typeMap.xml

**Comment by ayco-at-naturalis** [comment]
Agree that ReferenceWithPage is ugly. I don't understand why we didn't rather make a subclass of Reference containing a "page" field. On-the-fly enrichment of the CSL seems a bit strange, but it certainly is the easiest way to solve it.

**Comment by mdoering** [comment]
if we want to use CSL libs clientside to render a reference (which I think we should make use of) then we need to get this into the CSL. And we cannot put it into the CSL of reference instance itself as we would then have lots of redundant references just differing by the page. Well, maybe that is expecting too much from our incoming data and we actually will see references just differing by their page. Hard to tell at this stage
